### ISSUE TITLE
MoneroV support

### ISSUE THREAD

**Issue by monerov-s** [dvandal/cryptonote-nodejs-pool#100]
Looking forward to MoneroV support, any ETA?

**Comment by dvandal** [comment]
You should be able to use MoneroV without any issues. Looking at the available infos it is still using original cryptonight algorithm, so settings should be something similar to:

cnAlgorithm: cryptonight
cnVariant: 0
cnBlobType: 0

**Comment by monerov-s** [comment]
It is using the same v7 algo but the block reward is different - split between the devs and the miners. Not sure if that requires any changes?

**Comment by dvandal** [comment]
Ok, then all you probably need is to set the networkFee setting

**Comment by Chinsusu** [comment]
x10 compare to XMR, all work fine

**Comment by bruceleeon** [comment]
what is the setting for this?
