### ISSUE TITLE
pool | Errors

### ISSUE THREAD

**Issue by bruceleeon** [dvandal/cryptonote-nodejs-pool#107]
not sure what this means, i am seeing a lot of these on one pool

[pool] (Thread 3) Invalid method: mining.subscribe (["bmminer/2.0.0"]) from

**Comment by PsychoSterope** [comment]
I've had the same issue for days. I had to start a 100% fresh VM for my pool and it still reappeared. From what I have been able to gather, it's an antminer trying to connect to the pool. bmminer/2.0.0 is the mining software used by the antminer s9+.
