### ISSUE TITLE
Orphaned Block

### ISSUE THREAD

**Issue by bruceleeon** [dvandal/cryptonote-nodejs-pool#112]
How would I go about trying to tell if the pool is trying to pay miners on orphaned blocks? We are getting failed payments due to error code -4 not enough money, and that is the only reason I can think of that there wouldn't be enough funds in the wallet. There were a number of orphaned blocks...

**Comment by dvandal** [comment]
Issue is probably that your transfer fee is too low combined with a pool fee also too low.

Orphaned blocks are not the cause of the issue, when a block is orphaned the pool don't take care of them for payments.
