### ISSUE TITLE
No chart showing user hash rate is displayed. Please repair, Payments diagram is normal! Please add my pool in your introduction, thank you https://walpool.com.

### ISSUE THREAD

**Issue by youzidebaba** [dvandal/cryptonote-nodejs-pool#116]
![image](https://user-images.githubusercontent.com/37879101/40010060-44007470-57d6-11e8-8b18-4d3888c1f7d8.png)
No chart showing user hash rate is displayed. Please repair, Payments diagram is normal! Please add my pool in your introduction, thank you https://walpool.com.
@dvandal

**Comment by dvandal** [comment]
Updated to lastest code ? Was fixed a few days ago.

**Comment by youzidebaba** [comment]
![image](https://user-images.githubusercontent.com/37879101/40021006-437504e2-57f6-11e8-8372-2c0dfe172bc3.png)
OK, can I be added here, https://walpool.com?
