### ISSUE TITLE
Setup SSL

### ISSUE THREAD

**Issue by uekdyr** [dvandal/cryptonote-nodejs-pool#117]
Can't seem to figure out how to enable SSL for the API.

Using the settings:

        "ssl": true,
        "sslPort": 8119,
        "sslCert": "./cert.crt",
        "sslKey": "./cert.key",
        "sslCA": "./ca.pem",
        "trustProxyIP": true

Using the 8117 port everything works fine, but as soon as I change the API port to 8119 the API won't load.

While connecting to my server trough it's IP using the Browser "xx.xxx.xx.xxx:8117" it says "Invalid API call" which means that the connection is working. But when trying to connect to "xx.xxx.xx.xxx:8119" it says "ERR_EMPTY_RESPONSE" which means the connection is not working.

How to setup it correctly?

**Comment by dvandal** [comment]
You have specified a valid SSL certificate ? Any SSL API error when starting pool ?

**Comment by dvandal** [comment]
I don't reproduce your issue, it may be because you are using a self signed certificated. Personally I use lets encrypt certificates.

**Comment by uekdyr** [comment]
Hmm this is very wierd. Removed the certs entirely from config, then it gave an error also when connecting to it trough the browser it says "connection refused", but when I created new certs (using Let's Encrypt), it didn't print errors at startup and still printing "ERR_EMPTY_RESPONSE"...

Don't know really what's wrong here, something is wrong on my end, but the question is what's wrong... :/
