### ISSUE TITLE
our algo not integrates

### ISSUE THREAD

**Issue by FndNur1Labs** [dvandal/cryptonote-nodejs-pool#118]
we not sure why our algos not integrated here....just cnv7 and heavy?

we have more smooth easy for gpu and cpu block mining and less chance about 10% of ASIC miner. with implement new string and variable there~

**Comment by dvandal** [comment]
For Cryptonight algorithm we are using node-cryptonight-hashing code from MoneroOcean. If you want to add support for your own algorithm you will need to ask them on their git page: https://github.com/MoneroOcean/node-cryptonight-hashing or develop your own variant and manually update the package.json in my code.
