### ISSUE TITLE
Does this work for DigitalNote?

### ISSUE THREAD

**Issue by DrCryptoToad** [dvandal/cryptonote-nodejs-pool#119]
Any luck with XDN?  I haven't tried myself.  Thanks.

**Comment by dvandal** [comment]
Yes it works.

**Comment by DrCryptoToad** [comment]
I am getting "Error: Failed to parse block" any ideas?

**Comment by DrCryptoToad** [comment]
NM "cnBlobType": 2 fixes it.  Thank you very much for your hard work.
