### ISSUE TITLE
IPBC ALLOY fix intu

### ISSUE THREAD

**Issue by sanich-rd** [dvandal/cryptonote-nodejs-pool#120]
Please check Your mail from admin@newpool.pw I showed you the fixes in the code for some coins. What you need to provide IPBC and ALLOY to set up I'll send you everything in the mail.

**Comment by sanich-rd** [comment]
When you create your pools newpool.pw I found many errors and marked by hand. I need a connection with you. We can help each other.

**Comment by dvandal** [comment]
I applied your fixes into current code. Thanks.
