### ISSUE TITLE
why with blocks unlock? Look at this

### ISSUE THREAD

**Issue by doubitcoin** [dvandal/cryptonote-nodejs-pool#124]
hi, i try mine for 1 blocks unlocked, but when blocks are open and rewards are earned
why not all rewards sent into the address pool?

1. one blocks unlocked = 3777 reward
![capture](https://user-images.githubusercontent.com/33892273/40080011-e6350548-58b3-11e8-88ca-cc8f2dd89d22.PNG)

2. on blockchain
![captureaaaa](https://user-images.githubusercontent.com/33892273/40080057-093ca398-58b4-11e8-932f-da8dfab68f67.PNG)

3. reward is divided into 2
![aaaaaa](https://user-images.githubusercontent.com/33892273/40080184-6e8477c6-58b4-11e8-9b4d-20449c157689.PNG)

4. Pool balance on statistic shows 3777 coins
![sssss](https://user-images.githubusercontent.com/33892273/40080208-7ae61f4c-58b4-11e8-925e-076105d22f83.PNG)

5. check on daemon/cli
![aaaaaaaaaaaaaaaaaaaaa](https://user-images.githubusercontent.com/33892273/40080286-a46573ea-58b4-11e8-93bb-caa4937200d4.PNG)
![ssssssssss](https://user-images.githubusercontent.com/33892273/40080305-b6f06e02-58b4-11e8-9eb4-148ea325c4dd.PNG)

6. and miner he needs a 3777 reward to get paid
![sssssssssssssss](https://user-images.githubusercontent.com/33892273/40080343-d5f32434-58b4-11e8-8e7f-7daae6df0c6f.PNG)

if like this the owner of the pool will lose?
what's wrong with such vague transactions?

my config 
    "blockUnlocker": {
        "enabled": true,
        "interval": 30,
        "depth": 60,
        "poolFee": 0.0,
        "devDonation": 0.0,
        "networkFee": 0.1
    },

thanks you

**Comment by dvandal** [comment]
Solace coin is taking "dev" and "charity" fees, see: https://bitcointalk.org/index.php?topic=3297659.0
You will need to update the networkFee percentage to current value (~6.5% I think).
