### ISSUE TITLE
pool compatible TRTL (cryptonight_light V1) ?

### ISSUE THREAD

**Issue by prox443** [dvandal/cryptonote-nodejs-pool#125]
Can you confirm that configuration for Turtlecoin is:

```
"cnAlgorithm": "cryptonight_light",
"cnVariant": 1,
"cnBlobType": 0,
```

Thk :)

**Comment by prox443** [comment]
Hi @dvandal 
I have a new problem after update my pool.
I'm using latest version of your pool and latest version of turtledaemon.

Pool:
`[payments] Error with transfer RPC request to wallet daemon {"code":-32601,"message":"Method not found"}`

Wallet: 
`
2018-Jun-05 17:08:11.860256 WARNING Requested method not found: getbalance
2018-Jun-05 17:08:36.558972 WARNING Requested method not found: transfer
`

**Comment by dahifi** [comment]
Your wallet won't start the RPC server unless you specify the port in the command line. It's likely that your daemon is listening on the port, and the pool is sending to the daemon instead of the wallet. 

Use netstat -tulpn as root and verify that the wallet is listening on the proper port.

**Comment by bruceleeon** [comment]
@prox443 were you able to sort this out? I had the same issue with 2ACoin, its an issue with the wallet and the pool software. Luckily 2ACoin had a legacy wallet that supported the commands that the pool uses... I don't see this for turtle. (2ACoin is a fork of turtle). In other words, I your same issue with my turtle pool.

**Comment by PsychoSterope** [comment]
@bruceleeon What was your solution for this for 2A? poolwallet throws a fit for me also.
