### ISSUE TITLE
Auto title

### ISSUE THREAD

**Issue by 20dec** [dvandal/cryptonote-nodejs-pool#129]
Hi,

Do you make a function to change title in homepage (index.html) to "coin" value in config.json file?

For example: if coin = ABC
Then title will be: ABC Mining Pool
Mining Pool is default in html file now (and can change manully), it will add ABC auto before Mining Pool

Thank you.
20dec

**Comment by dvandal** [comment]
It does.

<span id="coinSymbol"></span> <span tkey="miningPool">Mining Pool</span>

and:

updateText('coinSymbol', lastStats.config.symbol);

**Comment by bruceleeon** [comment]
<span id="coinSymbol"></span>

**Comment by 20dec** [comment]
I mean title of browser, not title of pool.

**Comment by 20dec** [comment]
Hi,

Please help with this.
Thanks

**Comment by 20dec** [comment]
I done with this.
`
// Update global informations
function updateIndex(){
    updateText('coinSymbol', lastStats.config.symbol);
	$('title').html(lastStats.config.coin + ' Pool');
`
