### ISSUE TITLE
CPU Usage on daemons

### ISSUE THREAD

**Issue by bruceleeon** [dvandal/cryptonote-nodejs-pool#131]
Has anyone experimented with using the nice command to curb CPU usage on daemons? If not nice, how are we doing this in the services we create?

**Comment by dvandal** [comment]
I don't have used it yet for crypto but used it with other projects and should works fine.

**Comment by jvmatamu** [comment]
use cpulimit, open 2 screen, 1 for daemon, 1 for cpulimit
cpulimit -e coind -l 40
it's normal for first sync blockchain, after fully sync only 2-6% cpu usage,

**Comment by bruceleeon** [comment]
cpulimit did the trick.
