### ISSUE TITLE
last reward issue 

### ISSUE THREAD

**Issue by rut78HR** [dvandal/cryptonote-nodejs-pool#132]
Hello 
i have setup pool to mine xmv. Block is found and reward is 17.9XMV put on web page it shows 
last reward 1.7935 XMV . Hot to fix these ?

**Comment by 20dec** [comment]
Check coinunit match with decimal display in github coins.

**Comment by rut78HR** [comment]
tnx .. fixed . now i found some new issue .  on desktop everithing is ok but on mobile i got this :

[url=https://ibb.co/jKJNJy][img]https://thumb.ibb.co/jKJNJy/Screenshot_Chrome_20180517_201303.png[/img][/url]

can this be fixed (so much decimal unit)
