### ISSUE TITLE
Payments issue?

### ISSUE THREAD

**Issue by jerkitu** [dvandal/cryptonote-nodejs-pool#133]
Hello,

With the latest version, the payments appear in the list separately. Payments appear individually in the payment list.

You can see the problem in my pool.

https://pool.croatpirineus.cat/#payments

This is the configuration:

 "payments": {
        "enabled": true,
        "interval": 600,
        "maxAddresses": 100,
        "mixin": 1,
        "priority": 0,
        "transferFee": 50000000,
        "dynamicTransferFee": false,
        "minerPayFee": false,
        "minPayment": 100000000000,
        "maxTransactionAmount": 500000000000000,
        "denomination": 100000000000
    },

Thank you,

**Comment by dvandal** [comment]
The payments are grouped per days only in worker statistics.

**Comment by jerkitu** [comment]
Hello, 

what I mean is that on the payments page.
The normal thing is to see a payment of x coins to several miners in a single payment. 

And what I find is that there are many payments at the same hour and minute and each one to a single miner.

**Comment by dvandal** [comment]
Are miners using integrated addresses ? What is your intAddressPrefix setting ?

**Comment by jerkitu** [comment]
No,

Only some miners are usin paymentid. 

intAddressPrefix is 70 fro CROAT.

Tnks.

**Comment by jerkitu** [comment]
I have removed the value of intAddressPrefix

I'll wait for the next mined block to see how it makes the payments.

Thank you

**Comment by jerkitu** [comment]
Now the payments are correct!

issue is resolved!
