### ISSUE TITLE
mobile version issue 

### ISSUE THREAD

**Issue by rut78HR** [dvandal/cryptonote-nodejs-pool#135]
Hello ..

On desktop everithing is OK but on mobile i have much more decimal unit displayed .. look at mobile screenshoot. Can this be fixed ?
![screenshot_chrome_20180517-201303](https://user-images.githubusercontent.com/22094734/40196422-bf713ed2-5a10-11e8-8573-84edbc2c8c4f.png)

**Comment by dvandal** [comment]
Clear browser cache on mobile device.
