### ISSUE TITLE
Payment error

### ISSUE THREAD

**Issue by nutsplus** [dvandal/cryptonote-nodejs-pool#137]
Hello. I created MoneroV mining pool.
Min payout: 0.1 xmv
![screenshot_2018-05-17-15-58-38-496_com yandex browser](https://user-images.githubusercontent.com/38542260/40217651-8cc78a7a-5a76-11e8-9508-352b9c8d0011.png)
![screenshot_2018-05-17-08-25-54-929_com yandex browser](https://user-images.githubusercontent.com/38542260/40217660-93257ab2-5a76-11e8-8332-b95fe5e775fa.png)
![screenshot_2018-05-17-08-21-31-023_com yandex browser](https://user-images.githubusercontent.com/38542260/40217663-97baa0a2-5a76-11e8-82ce-7de65a96cc1e.png)
[admin_log (1).txt](https://github.com/dvandal/cryptonote-nodejs-pool/files/2015572/admin_log.1.txt)
[admin_log.txt](https://github.com/dvandal/cryptonote-nodejs-pool/files/2015573/admin_log.txt)

**Comment by dvandal** [comment]
1. In first log file you have miners with minimum payout set.
2. In second log file when trying to send payment you don't have enough unlocked balance.
3. Looking at your pool, denomination is set to 1 XMV so no payments below this will be sent, you need to lower to 0.1 to match minimum payout.
4. Since you have a zero pool fee, you may need to set higher transaction fee to avoid balance negative.

**Comment by nutsplus** [comment]
What transaction fee for zero pool fee and 0.5% pool fee?

**Comment by nutsplus** [comment]
2018-05-18 21:33:14 Error with transfer RPC request to wallet daemon {"code":-37,"message":"not enough unlocked money"}
2018-05-18 21:33:14 Payments failed to send to {"amount":6000000000,"address":"46a7T4uPGCFVzNsAn242FCXJY4a7jpRyqZMKkXp1V7NNdduKw2aVGvL6VJmuzxAGyFWvyk2zziJFWM2beyhYdGhHDRYJMq8"} { amount: 66000000000,
  address: '47E9RRqh8MqcgLZgvuJNQNidCoE7DoVV7TBY1MjLBnbch3dCgERdHGNMoRpp8vDuWnE7qrCU77MChiZwAFCzxqSv976TSNY' } { amount: 36000000000,
  address: '45ourV1rMV3JaAndP1DizddNgsVCh8G7MGQ6x5WRNAx7fQtUPp5hsC361dxrLKMXPGCU4Ys3ie5ZyeaZENRHddPaNUfMZVf' } { amount: 36000000000,
  address: '47V5AAtw7RP5fTyNJQL2dLJbMtnk4qS3gWJzwYPdcpzvK2hEW9z1TS3EqHKgZAbWUrDK6QbdKnc6Q74NLdurFGwfFQPfrTZ' } { amount: 56000000000,
  address: '48eQSfaRQAiRXGCyaixNENLDfGgd4S9BCRPYuG6ihXMpamRHtMMEuuFCYWSu6RJ31HLEKGAYkk2MiLFP7w3LBqhE9ogxTpB' } { amount: 36000000000,
  address: '47zpHP1piVwBZYWGRgWrvnEzRHVmdo7JCUgw4cruotnsdkE7aqMfmkjQ9SLa96BnuECgSyK48acdyKfWTrKXr7Dg1xBuvSd' } { amount: 76000000000,
  address: '48n1k6DKjJ11ZteRCSXEx4hJSgyYHVWANL4fYeKMJQXieVEcxDEE4f3ZU35tXsxH3oLDM9Fqs41NdKNgBSH7kaXz7sjjyTB' } { amount: 56000000000,
  address: '49RYprcGwtDFrYEf6VfgBuek2EU8aKogsZ3LpbV4r5tPRcJTtga9tgg42mRPacwKaH9UGvoDMnYpHcBM3EYD6naWM2xSLz4' }
