### ISSUE TITLE
Website

### ISSUE THREAD

**Issue by uekdyr** [dvandal/cryptonote-nodejs-pool#138]
Could someone confirm that the latest website is working? Since I just updated and everything works except all the info bars like "CONNECTED MINERS N/A (N/A workers)" where it says N/A everywhere but I know there's workers connected. Not only the "Workers" bar, every bar such as "MINIMUM PAYOUT
N/A" says N/A.

I've cleared my Cache, same thing.

The issue began when I updated to the latest website files.
@dvandal Any suggestions?

**Comment by dvandal** [comment]
You need to have both pool and website code updated.

**Comment by bruceleeon** [comment]
Website works on my end... I did upgrade to 1.3.4 and noticed that I had to upgrade the website too.
