### ISSUE TITLE
Saving Data Question

### ISSUE THREAD

**Issue by CoFix** [dvandal/cryptonote-nodejs-pool#14]
Hello dvandal,

My blocks and all payments data is gone when i restart my server. This is problem or i mistake something?

**Comment by dvandal** [comment]
Seem like your REDIS Persistence / Background save is not working properly, please take a look at:

https://redis.io/topics/persistence

And:

https://stackoverflow.com/questions/24888519/could-not-find-the-redis-data-after-restart-of-server
