### ISSUE TITLE
Release a ban

### ISSUE THREAD

**Issue by bruceleeon** [dvandal/cryptonote-nodejs-pool#140]
Where can you release the ban of a user? I know its a time based thing, but I can't find anything in redis that indicates a ban or the ability to release the ban.

**Comment by dvandal** [comment]
There is no way to release a ban, its not saved in redis database but directly in pool. When a user is banned he need to wait the specified ban time in config (default 15 minutes), you can also restart the pool daemon which will release all bans.

**Comment by bruceleeon** [comment]
That is what I ended up doing, the ban was on me :)
