### ISSUE TITLE
payment with walletd instead of simplewallet

### ISSUE THREAD

**Issue by delarius** [dvandal/cryptonote-nodejs-pool#147]
Hi,

can you please implement the paymentprocessor for walletd instead of standard simplewallet ??
If you need some informations I could give you a link with a working paymentprocessor.js of the standard forknote pool.

Thank you !!

BR
Dela

**Comment by podvodnik** [comment]
could you please provide the link here, I will take a look at it.

**Comment by dvandal** [comment]
I started looking at bytecoin walletd RPC api, its a complex task but can be done. Can you provides the link to the paymentProcessor.js that you are talking about?

**Comment by Cideg** [comment]
Hi, there may be news about the implementation of Walletd.

Worktips Coin only supports Walletd, and it comes to error messages:

pool errors
{"code": - 32601, "message": "Method not found"}
(Entry in the Config.json / daemonType ":" default, does not fix the error.)


Wallet error
Start: ./walletd -w yourwalletfile -p yourwalletpassword --daemon-port = 18238 --bind-port = 8050 --rpc-legacy-security

Removing outdated pool transactions ...
2018-Jun-22 23: 46: 50.242338 INFO Wallet loading is finished.
2018-Jun-22 23: 46: 50.245318 INFO Outdated pool transactions processed
2018-Jun-22 23: 47: 27.489145 WARNING Requested method not found: getbalance
2018-Jun-22 23: 48: 27.490373 WARNING Requested method not found: getbalance
2018-Jun-22 23: 49: 27.491759 WARNING Requested method not found: getbalance
2018-Jun-22 23:50:27:495977 WARNING Requested method not found: getbalance
2018-Jun-22 23:51:27:49:89 WARNING Requested method not found: getbalance



For worktips the paymentProcessor.js can be found here:

https://github.com/worktips/worktips-pool/blob/master/lib/paymentProcessor.js


Many thanks in advance

**Comment by PsychoSterope** [comment]
@delarius Did you ever get this solved? I am working on a coin forked from turtle and it's driving me mad

**Comment by delarius** [comment]
@PsychoSterope yes it is working fine for me. I have added both (walletd, and rpc password).

**Comment by travis1234** [comment]
@delarius any chance you could share how you got it to work? Having a similar issue
