### ISSUE TITLE
Workers Data 

### ISSUE THREAD

**Issue by CoFix** [dvandal/cryptonote-nodejs-pool#15]
Hello Dvandal,

Our api page doesnt show workers information.

My Test Pool: https://images2.imgbox.com/45/e9/mUuSWLPb_o.png
Others Pool: https://images2.imgbox.com/98/7d/psaUAAPW_o.png

How we can add workers data to api?

Sorry for bad english.
Thank You.

**Comment by dvandal** [comment]
Hi, a new "workers" value has been added and "miners" is now used to return the unique miners (wallets) instead of "workers". Thanks!
