### ISSUE TITLE
Orphans in intucoin

### ISSUE THREAD

**Issue by ArqTras** [dvandal/cryptonote-nodejs-pool#151]
In past version 1.3.3 when blockManager add in line block.height + 1 there is no orphans now after update release its not full compatible

**Comment by dvandal** [comment]
Do you have enabled `"fixBlockHeightRPC": true` setting in blockUnlocker ?

**Comment by dlegend116** [comment]
where is this setting because I got like three orphans today alone

**Comment by dlegend116** [comment]
is this boolean in unlocker.js or in thee config.json so we add this line of code?

**Comment by ArqTras** [comment]
adding line to old config fixBlockHeightRPC": true solved problem
