### ISSUE TITLE
API request to cryptonator failed

### ISSUE THREAD

**Issue by Invisys** [dvandal/cryptonote-nodejs-pool#154]
Hello, Dvandal!

market_error.log

> 2018-05-25 11:21:19 API request to cryptonator has failed: SyntaxError: Unexpected token T
> 2018-05-25 11:23:04 API request to cryptonator has failed: SyntaxError: Unexpected token T
> 2018-05-25 11:24:10 API request to cryptonator has failed: SyntaxError: Unexpected token T
> 2018-05-25 11:24:40 API request to cryptonator has failed: SyntaxError: Unexpected token T
> 2018-05-25 11:24:40 API request to cryptonator has failed: SyntaxError: Unexpected token T
> 2018-05-25 11:24:43 API request to cryptonator has failed: SyntaxError: Unexpected token T
> 2018-05-25 11:24:43 API request to cryptonator has failed: SyntaxError: Unexpected token T
> 2018-05-25 11:24:47 API request to cryptonator has failed: SyntaxError: Unexpected token T
> 2018-05-25 11:24:47 API request to cryptonator has failed: SyntaxError: Unexpected token T
> 2018-05-25 11:24:57 API request to cryptonator has failed: SyntaxError: Unexpected token T
> 2018-05-25 11:24:57 API request to cryptonator has failed: SyntaxError: Unexpected token T
> 2018-05-25 11:25:08 API request to cryptonator has failed: SyntaxError: Unexpected token T
> 2018-05-25 11:25:08 API request to cryptonator has failed: SyntaxError: Unexpected token T

And alot of same lines in this log.

**Comment by citizenz7** [comment]
Same error here with last version.

**Comment by bruceleeon** [comment]
it happens... i see that it connects a little while later.

**Comment by dvandal** [comment]
I now limit API requests to 1 per 60 seconds, should be fine now.
