### ISSUE TITLE
Payments issue

### ISSUE THREAD

**Issue by prox443** [dvandal/cryptonote-nodejs-pool#156]
Hello.
I have a Massari pool with a payment problem. (no problem on my IntenseCoin pool).
The masari daemon is the last updated.
Here is the mistake I have. Without details ...

```
2018-05-26 01:49:31 [payments] Error with transfer RPC request to wallet daemon {}
2018-05-26 01:49:31 [payments] Payments failed to send to {"amount":49295000000000,"address":"5p5pUeoXTRsZHQbPnKYvP4AyZKQMWheZpfNsgLH2J6ji9mwSi17Bf4Q4AvZuUMgqXK95NT5wk6k1hLsaGdV3BMoHBK12knq"}
2018-05-26 01:49:31 [payments] Payments splintered and 0 successfully sent, 1 failed
```

Has anyone ever had this error?
Thk

**Comment by WaReZoR-UA** [comment]
check RPC ports of the server and that you propisan have config.json

**Comment by prox443** [comment]
The port is well informed and correct.
If I test by putting a bad port, I have a specific error.

`2018-05-30 01:04:04 [payments] Error with transfer RPC request to wallet daemon {"code":"ECONNREFUSED","errno":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":38084}
`

in my case I have no precision for the error which made it difficult to solve.

**Comment by Warix3** [comment]
I've had the same issue, fixed it by adding options --disable-rpc-login --trusted-daemon 
to the wallet rpc. Also the wallet rpc loads very slowly so you might need to wait 5-10 minutes for it to start. And sometimes it gets stuck in the background so you need to kill it manually.

**Comment by prox443** [comment]
perfect.
Thk @Warix3
