### ISSUE TITLE
How can i delete redis data?

### ISSUE THREAD

**Issue by CoFix** [dvandal/cryptonote-nodejs-pool#157]
I lived problem with transaction size is too big.

2018-05-26 08:42:22 Error with transfer RPC request to wallet daemon {"code":-4,"message":"Transaction size is too big"}
2018-05-26 08:42:22 Payments failed to send to {"amount":1319347280000000,"address":"walletadressxxx"}

I cant fix it and **i sent all balance manually to miners.** 

I learned how to do fix this problem now. but if i fix it, my pool send balance again. 

So i need delete pending balance.

It is possible?

Thank You.

**Comment by WaReZoR-UA** [comment]
play with the maxTransactionAmount parameter and restart pool

**Comment by CoFix** [comment]
Please read carefully what i wrote 

> I learned how to do fix this problem now. but if i fix it, my pool send balance again.

>

**Comment by bruceleeon** [comment]
Use redis commander to change data.

```
npm install -g redis-commander
pm2 start --name=redisc -- --port 8181 -–http-u someuser -–http-p somepassword
```

**Comment by jvmatamu** [comment]
if you prefer to reset default redis database, use this command, 
*note this command will reset all data*
redis-cli flushall
redis-cli flushdb

**Comment by CoFix** [comment]
@bruceleeon @jvmatamu 

I just want delete one user pending balance. Any easy command for delete it ?

**Comment by avense** [comment]
install redis-comander and then delete the pending balance of whoever you want

**Comment by bruceleeon** [comment]
How do we close this?

**Comment by skyclean906** [comment]
@CoFix  Can you tell me how could you solved above issue?

**Comment by alessiosavi** [comment]
It's a little bit tricky delete a single key in production. Before touch db, make sure that you have make a backup.
Locate the db: redis-cli config get dir
Stop db: redis-cli save && redis-cli shutdown
Once stopped make a copy of the db taking it by the location retrieved before. 
Restart redis and your production pool and have a look at the db with redis commander used before. A trick that you can use is to print the entire db (is a simple ascii file(json format)) and filter from your bad transaction: reset && cat dump.rdb | grep hash_bad_transaction --color=auto.
After simply scroll untill find the hilight

**Comment by GeorgeAlanis** [comment]
@CoFix , How you solve the error "2018-05-26 08:42:22 Error with transfer RPC request to wallet daemon {"code":-4,"message":"Transaction size is too big"}"?
