### ISSUE TITLE
Requested method not found: getbalance

### ISSUE THREAD

**Issue by sanich-rd** [dvandal/cryptonote-nodejs-pool#159]
hello
coin: WORKTIPS (WTIP)
demon:cd worktips/build/src && ./Worktipsd

wallet: ./walletd --container-file=Sanw --container-password=xxxxxx --daemon-port=18238 --bind-port=18242 --rpc-legacy-security

admin panel:

Wallet
Last check: about a minute ago
Last status: fail
Last response:
{"code":-32601,"message":"Method not found"}
Last fail: about a minute ago
Last fail response:
{"code":-32601,"message":"Method not found"}

wallet: 
2018-May-28 02:56:00.879101 INFO    walletd v1.0.2.3
2018-May-28 02:56:00.880157 INFO    Starting Payment Gate with remote node
2018-May-28 02:56:00.887040 INFO    Loading wallet
2018-May-28 02:56:00.887748 INFO    Loading container...
2018-May-28 02:56:01.033932 INFO    Consumer added, consumer 0x028d0e70, count 1
2018-May-28 02:56:01.215106 INFO    Loading...
2018-May-28 02:56:01.215460 INFO    Loaded
2018-May-28 02:56:01.268544 INFO    Starting...
2018-May-28 02:56:01.269018 INFO    Container loaded, view public key 6d854c3b68f2f6a5e2b1b35c8b49dd56950a3384aff72d4b9437e3ebdf418289, wallet count 1, actual balance 0.00000000, pending balance 0.00000000
2018-May-28 02:56:01.269797 INFO    Wallet loading is finished.
2018-May-28 02:56:01.269224 INFO    Removing outdated pool transactions...
2018-May-28 02:56:01.271227 INFO    Outdated pool transactions processed
2018-May-28 02:57:34.966313 WARNING Requested method not found: getbalance
2018-May-28 02:58:34.969073 WARNING Requested method not found: getbalance
2018-May-28 02:59:34.983425 WARNING Requested method not found: getbalance
2018-May-28 03:00:34.990031 WARNING Requested method not found: getbalance
2018-May-28 03:01:34.994237 WARNING Requested method not found: getbalance

**Comment by Cideg** [comment]
Is there any news, also have the problem since the server restart
