### ISSUE TITLE
Error when git pull and after npm update

### ISSUE THREAD

**Issue by WaReZoR-UA** [dvandal/cryptonote-nodejs-pool#165]
make: Entering directory '/home/loki/pool/node_modules/cryptonight-hashing/build'
  CXX(target) Release/obj.target/cryptonight-hashing/multihashing.o
../multihashing.cc:8:2: error: invalid preprocessing directive #elseif
 #elseif !defined(__APPLE__)

....................................................

In file included from ../multihashing.cc:5:0:
../../nan/nan.h:1618:3: note: declared here
   Call(int argc, v8::Local<v8::Value> argv[]) const {
   ^
cryptonight-hashing.target.mk:106: recipe for target 'Release/obj.target/cryptonight-hashing/multihashing.o' failed
make: *** [Release/obj.target/cryptonight-hashing/multihashing.o] Error 1
make: Leaving directory '/home/loki/pool/node_modules/cryptonight-hashing/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Linux 4.4.0-127-generic
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/loki/pool/node_modules/cryptonight-hashing
gyp ERR! node -v v8.11.2
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! cryptonight-hashing@2.0.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the cryptonight-hashing@2.0.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by dvandal** [comment]
What is your OS ?

Can you try this:
1. Delete node_modules/ folder
2. Delete packages-lock.json file
3. Do: git pull
4. Do: npm update

**Comment by WaReZoR-UA** [comment]
I have removed the folder with a pool completely. Later I have downloaded the latest version on git, then make npm update. The problem has repeated....

**Comment by citizenz7** [comment]
same here
Log file : 
[](https://framabin.org/p/?be66a82fd67a02e2#ibD6fFlXnIPIWT4v2KhPVWJy7lYYXJOt6FkaR9C4zIw=)

**Comment by WaReZoR-UA** [comment]
solved

**Comment by luaus** [comment]
I fixed this by switching to nodejs v4.9.1, it was doing the same on nodejs v8.X.X
