### ISSUE TITLE
node-pre-gyp ERR! Tried to download(403)

### ISSUE THREAD

**Issue by WaReZoR-UA** [dvandal/cryptonote-nodejs-pool#168]
The previous problem was solved, but in case of assembly of a pool the problem in the following anew appeared:

![image](https://user-images.githubusercontent.com/38248645/40668201-9297d28a-636c-11e8-91eb-1e06c2f30aa0.png)

**Comment by dvandal** [comment]
This error can be ignored. This is GYP trying to get a pre-compiled version but compile it instead locally.
