### ISSUE TITLE
Can you make a website homepage like this? 

### ISSUE THREAD

**Issue by youzidebaba** [dvandal/cryptonote-nodejs-pool#170]
Can you make a website homepage like this? The data looks very good. Next I will give three columns of the website homepage, they are excellent!
Https://easyhash.pro/
Https://mineallcrypto.com/
Https://miner.rocks/
@dvandal 

![3](https://user-images.githubusercontent.com/37879101/40694238-36f76c38-63ee-11e8-94db-ed23aa645c62.png)
![qq 2](https://user-images.githubusercontent.com/37879101/40694240-380c219a-63ee-11e8-9afd-deb1d5959e9c.png)
![qq 1](https://user-images.githubusercontent.com/37879101/40694241-386437d6-63ee-11e8-960c-a689046ca029.png)

**Comment by dvandal** [comment]
Yes I could but not something I will do, you can get all pools data from API and I already provides a sample landing page.

For market data you can use coinlib.io website widgets like you find on easyhash.pro: https://coinlib.io/widgets

**Comment by Chinsusu** [comment]
You have to calculate it.

**Comment by youzidebaba** [comment]
Can you do it

**Comment by Chinsusu** [comment]
I can, but having problem with getting API, there are some delay between getting api and calculating it.

**Comment by youzidebaba** [comment]
Can you send me the code you wrote? Thank you very much.

**Comment by youzidebaba** [comment]
website:https://walpool.com
email:5678164@qq.com
