### ISSUE TITLE
More Miner Statistics

### ISSUE THREAD

**Issue by CoFix** [dvandal/cryptonote-nodejs-pool#175]
Hi Dvandal,

Can you add more details about miner statistics?

https://images2.imgbox.com/da/fb/lDXHXcV7_o.png

Thank You.

**Comment by avense** [comment]
I added some functions you could do the same.
![funcoes](https://user-images.githubusercontent.com/15719937/40862197-a043610a-65e3-11e8-8232-fdb836cfda39.jpg)

**Comment by waterfallm** [comment]
How did you add this detail to the webpages? Do you have any HowTo docs? Does the API have any documentation around params that can be requested?

**Comment by avense** [comment]
@waterfallm I studied the code and implemented these functions.

Do you need some function?

**Comment by leisegang** [comment]
@avense could you share the code?
