### ISSUE TITLE
xmr-node-proxy Support

### ISSUE THREAD

**Issue by CoFix** [dvandal/cryptonote-nodejs-pool#180]
Hi Dvandal,

Can you add xmr-node-proxy support please?

https://github.com/MoneroOcean/xmr-node-proxy

Thank You.

**Comment by herominers** [comment]
I am getting this error when i am trying to connect pool.

> 1|proxy    | 2018-06-06 10:51:09:525 +00:00: TypeError: First argument must be a string, Buffer, ArrayBuffer, Array, or array-like object.
1|proxy    |     at Function.Buffer.from (buffer.js:183:11)
1|proxy    |     at new Buffer (buffer.js:158:17)
1|proxy    |     at new MasterBlockTemplate (/home/nodeproxy/xmr-node-proxy/lib/cryptonightv7.js:99:19)
1|proxy    |     at handleNewBlockTemplate (/home/nodeproxy/xmr-node-proxy/proxy.js:767:32)
1|proxy    |     at handlePoolMessage (/home/nodeproxy/xmr-node-proxy/proxy.js:742:17)
1|proxy    |     at Socket.socket.on (/home/nodeproxy/xmr-node-proxy/proxy.js:708:17)
1|proxy    |     at emitOne (events.js:116:13)
1|proxy    |     at Socket.emit (events.js:211:7)
1|proxy    |     at addChunk (_stream_readable.js:263:12)
1|proxy    |     at readableAddChunk (_stream_readable.js:246:13)

>

**Comment by CoFix** [comment]
I am getting this error when i am trying to connect pool.

> 1|proxy    | 2018-06-06 10:51:09:525 +00:00: TypeError: First argument must be a string, Buffer, ArrayBuffer, Array, or array-like object.
1|proxy    |     at Function.Buffer.from (buffer.js:183:11)
1|proxy    |     at new Buffer (buffer.js:158:17)
1|proxy    |     at new MasterBlockTemplate (/home/nodeproxy/xmr-node-proxy/lib/cryptonightv7.js:99:19)
1|proxy    |     at handleNewBlockTemplate (/home/nodeproxy/xmr-node-proxy/proxy.js:767:32)
1|proxy    |     at handlePoolMessage (/home/nodeproxy/xmr-node-proxy/proxy.js:742:17)
1|proxy    |     at Socket.socket.on (/home/nodeproxy/xmr-node-proxy/proxy.js:708:17)
1|proxy    |     at emitOne (events.js:116:13)
1|proxy    |     at Socket.emit (events.js:211:7)
1|proxy    |     at addChunk (_stream_readable.js:263:12)
1|proxy    |     at readableAddChunk (_stream_readable.js:246:13)

>

**Comment by bruceleeon** [comment]
that proxy is for nodejs-pool only. There is a proxy that works with this pool ... https://github.com/sebseb7/cryptonote-proxy

**Comment by VirtuBox** [comment]
[xmrig-proxy](https://github.com/xmrig/xmrig-proxy is an excellent alternative and is pretty easy to setup

**Comment by Ogy** [comment]
@CoFix 
+1
