### ISSUE TITLE
Admin Languages and Wallet Balance

### ISSUE THREAD

**Issue by xpctxmin** [dvandal/cryptonote-nodejs-pool#181]
Can you develop an option to change the language of the administration section?

Also, is it possible to add the real balance of the pool wallet to the administration statistics section?
I know that is seen in the monitoring section, but is possible seen in statistics page in a more readable way?

Thanks.

**Comment by dlegend116** [comment]
How do read the wallet balance on admin monitoring page? It’s 12 digit number but how do calculate true value represented in given coin?
