### ISSUE TITLE
Error with transfer RPC request to wallet daemon

### ISSUE THREAD

**Issue by prox443** [dvandal/cryptonote-nodejs-pool#192]
I have a new problem after update my pool.
I'm using latest version of your pool and latest version of turtledaemon.

My logs
Pool:
`[payments] Error with transfer RPC request to wallet daemon {"code":-32601,"message":"Method not found"}`

Wallet:
```
2018-Jun-05 17:08:11.860256 WARNING Requested method not found: getbalance 
2018-Jun-05 17:08:36.558972 WARNING Requested method not found: transfer
```

**Comment by avense** [comment]
/* Set daemon type. Supported values: default, forknote (Fix block height + 1), bytecoin (ByteCoin Wallet RPC API) */
"deamonType": "default",

**Comment by minereobot1** [comment]
> /* Set daemon type. Supported values: default, forknote (Fix block height + 1), bytecoin (ByteCoin Wallet RPC API) */
> "deamonType": "bytecoin",

where you set it ?
