### ISSUE TITLE
same telegram bot on different pools gives stats for both pools

### ISSUE THREAD

**Issue by TheSquiffy** [dvandal/cryptonote-nodejs-pool#193]
I have set the same bot into two different groups and configured for two different pool instances (different coins). Giving /stats command in one channel replies with stats from both pools. I believe it should give stats for the channel/pool it was asked for instead.

**Comment by TheSquiffy** [comment]
A little more on the issue: it gives stats for both pools if I, asking, I'm sitting on both channels. Anyone else asking and sitting on only one channel receives the correct stats for the pool.

**Comment by bruceleeon** [comment]
i bet you have the token incorrect on one pool

**Comment by TheSquiffy** [comment]
the token it's correct. trust me.

**Comment by bruceleeon** [comment]
Its not about trust, its about validation. Each pool needs its own token for its own group.
