### ISSUE TITLE
Network difficulty vastly different from other pools

### ISSUE THREAD

**Issue by travis1234** [dvandal/cryptonote-nodejs-pool#195]
Hello, 

Just wanted to confirm if there was an issue with my config or something else?

If you look at our pool http://electroneum.vip vs http://etn.spacepools.org there is huge difference in global network hashrate.

Is there a reason for the difference, and which is correct?
I know the blocktime doubled since the fork if that makes any difference...

Thanks in advance

**Comment by mannie65** [comment]
Have you adjusted your coindifficultytarget in config.json ?

**Comment by travis1234** [comment]
Hello, yes my mistake that has fixed the issue.

One other thing, when you compare the pools again the blockchain heights are off by one block.
Is there another setting that needs to be changed for this or does this software just report the heights differently?

Cheers.

**Comment by mannie65** [comment]
This pool display the next block to be mined - and other display the last block height mined.
I'm sue there is a setting for the block-height in one of the lib files which you could subtract 1 from , but never bothered my miners so never bothered

**Comment by jvmatamu** [comment]
Nothing wrong, because report the current mined block hashrate, also the "real" height witch is the height of the current mined block.

**Comment by travis1234** [comment]
Yep, that’s what I figured. Thanks guys.
