### ISSUE TITLE
Stellite fork

### ISSUE THREAD

**Issue by bruceleeon** [dvandal/cryptonote-nodejs-pool#197]
Do we have support for Stellite xtl cn variant (new fork)?

**Comment by bruceleeon** [comment]
Beuller Beuller?

**Comment by bruceleeon** [comment]
I got it working, left it at variant 3, accepting hashes from new miners

**Comment by PandemRus** [comment]
Did your pool open new blocks? Because my effort already more than 1000.

**Comment by WaReZoR-UA** [comment]
same

**Comment by bruceleeon** [comment]
yeah, they orphaned

**Comment by bruceleeon** [comment]
Well, it looks like this is out of  @dvandal 's hands. MoneroOcean doesn't support v4 in their https://github.com/MoneroOcean/node-cryptonight-hashing . Unless they update that, we are out of luck. Unless we try to use this one: https://github.com/ahmyi/xtlpool-cryptonote-util.git . I am going to experiment today.

**Comment by PandemRus** [comment]
bruceleeon, tell the results then, please.

**Comment by PandemRus** [comment]
This work for me

"cnAlgorithm": "cryptonight",
"cnVariant": 3,
"cnBlobType": 0,

**Comment by bruceleeon** [comment]
@PandemRus that doesn't seem to work for me.
