### ISSUE TITLE
error on npm update

### ISSUE THREAD

**Issue by leisegang** [dvandal/cryptonote-nodejs-pool#2]
npm ERR! git clone git://github.com/dvandal/node-multi-hashing.git Cloning into bare repository '/pinkstar/.npm/_git-remotes/git-github-com-dvandal-node-multi-hashing-git-d0610969'...
npm ERR! git clone git://github.com/dvandal/node-multi-hashing.git fatal: unable to connect to github.com:
npm ERR! git clone git://github.com/dvandal/node-multi-hashing.git github.com[0: 192.30.253.112]: errno=Connection refused
npm ERR! git clone git://github.com/dvandal/node-multi-hashing.git github.com[1: 192.30.253.113]: errno=Connection refused
npm ERR! git clone git://github.com/dvandal/node-cryptonote-util Cloning into bare repository '/pinkstar/.npm/_git-remotes/git-github-com-dvandal-node-cryptonote-util-b8547a6e'...
npm ERR! git clone git://github.com/dvandal/node-cryptonote-util fatal: unable to connect to github.com:
npm ERR! git clone git://github.com/dvandal/node-cryptonote-util github.com[0: 192.30.253.112]: errno=Connection refused
npm ERR! git clone git://github.com/dvandal/node-cryptonote-util github.com[1: 192.30.253.113]: errno=Connection refused

**Comment by dvandal** [comment]
Looks like you had connection issue with github.com due to the error Connection refused. Is it working now ?
