### ISSUE TITLE
SSL API Issue

### ISSUE THREAD

**Issue by flychicken123** [dvandal/cryptonote-nodejs-pool#206]
Could not start API listening on 0.0.0.0 port 8148 (SSL): SSL certificate authority not configured

    "api": {
        "enabled": true,
        "hashrateWindow": 600,
        "updateInterval": 20,
        "bindIp": "0.0.0.0",
        "port": 8147,
        "blocks": 30,
        "payments": 30,
        "password": "password",
        "ssl": true,
        "sslPort": 8148,
          "sslKey": "/etc/letsencrypt/live/domain.com-0004/privkey.pem",
        "sslCert": "/etc/letsencrypt/live/domain.com-0004/cert.pem",
        "sslca": "/etc/letsencrypt/live/domain.com-0004/chain.pem",
        "trustProxyIP": false
    },
var api = "//krb.mychainpools.com:8148";
    location ~ ^/api/(.*) {
        proxy_pass http://127.0.0.1:8147/$1$is_args$args;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

**Comment by PandemRus** [comment]
Check the rights of the user who runs the pool to these certificates
