### ISSUE TITLE
Haven V3 Fork

### ISSUE THREAD

**Issue by CoFix** [dvandal/cryptonote-nodejs-pool#213]
Hello Dvandal,

New haven fork doesnt work with new MoneroOcean repo.

https://github.com/MoneroOcean/node-cryptonight-hashing/commit/40d0f51dcff0ce6e4bcfd65bf5a67746f6d13841

You need update something?

Thank You.

**Comment by avense** [comment]
you need to change package.json

**Comment by CoFix** [comment]
@avense 
I dont want use haven official node-multi-hashing. I want run my pool with MoneroOcean repo.

**Comment by avense** [comment]
@CoFix 
Then you need to check the changes and compile the repo of the moneroOcean.

The danval walks a bit busy already gave up the pools, he said he would continue to make updates to the software, but will not be at this level ...

But wait for his answer.

**Comment by CoFix** [comment]
@avense 
How do you decide my problem is low level?

Are you the decision maker? What is happening to you? What's in and out of you?

**Comment by dvandal** [comment]
Please stay calm. I just submitted a patch to support Cryptonight Heavy variants. You need to use the "cryptonight_heavy" algorithm and cnVariant 1 for XHV to use the new variant added in MoneroOcean code.

**Comment by dvandal** [comment]
Please make sure to update node.js package : npm update

**Comment by avense** [comment]
@CoFix 

But what is this?
What happened to respond like this?
I only said what the danval announced here days ago, nothing more.

Whenever you have any doubts on my part you will not have an answer, they look like kids

**Comment by HKoody** [comment]
Can someone help me please?
I already did it: 
1º git pull to get the latest cryptonote-nodejs-pool code 
2° delete node_modules directory
3° npm update to force updating/reinstalling of the dependencies
4° install version 3 forked daemon wallet rpc haven
5° add "cryptonight_heavy" algorithm and cnVariant 1 to Haven.Json
6° using xmr-stak 2.4.5 compatible with Haven fork
The miner receives the blocks but the pool is rejecting all the shares, before the fork everything was working perfectly. I have to edit something else?
Thanks.
