### ISSUE TITLE
[pool] (Thread 1) Malformed message from ::ffff:105.186.149.234 generated an exception.

### ISSUE THREAD

**Issue by hypeboard** [dvandal/cryptonote-nodejs-pool#217]
[pool] (Thread 1) Malformed message from ::ffff:105.186.149.234 generated an exception. Message: {"method":"login","params":{"login":"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx","pass":"x","rigid":"","agent":"xmr-stak/2.4.5/b3f79de3/master/win/nvidia-amd-cpu/aeon-cryptonight-monero/20"},"id":1}

  "poolHost": "festival.multiminer.us",

    "coin": "festival",
    "symbol": "FEST",
    "coinUnits": 1000000000,
    "coinDecimalPlaces": 4,
    "coinDifficultyTarget": 120,

    "daemonType": "default",
    "cnAlgorithm": "cryptonight",
    "cnVariant": 1,
    "cnBlobType": 0,

**Comment by bruceleeon** [comment]
im getting the same errors on a bbscoin pool

**Comment by hypeboard** [comment]
Ok fixed my problem so closing this issue. 


{
    "poolHost": "festival.multiminer.us",

    "coin": "festival",
    "symbol": "FEST",
    "coinUnits": 1000000000000,
    "coinDecimalPlaces": 4,
    "coinDifficultyTarget": 120,

    "cnAlgorithm": "cryptonight",
    "cnVariant": 1,
    "cnBlobType": 2,
