### ISSUE TITLE
If orphan block rewards issue

### ISSUE THREAD

**Issue by vahidshaik1901** [dvandal/cryptonote-nodejs-pool#219]
Hi,

If orphan block found rewards will 0 but it's added to miners pending balance. Please fix for me.

**Comment by HKoody** [comment]
@vahidshaik1901 
You need to check the blockUnlocker.js, this js check if blocks are orphaned or not.

To delete the incorrect balance you need to edit Redis database, on KEY haven:workers:address and FIELD balance.

**Comment by vahidshaik1901** [comment]
Ok thank you
