### ISSUE TITLE
Miner connecting to pool

### ISSUE THREAD

**Issue by userid2018** [dvandal/cryptonote-nodejs-pool#222]
Hi All,

As soon as I start the pool, a new miner shows up in the dashboard. even though I am not broadcasting the pool address as I want to have this private pool server.

How do i ensure or remove the miner which gets connected on start of the pool?

**Comment by bruceleeon** [comment]
use a firewall and block everything but your IP address.

**Comment by HKoody** [comment]
@userid2018 you can use password to conect the miners, you can disable automatic payment (only the wallet you choose will receive the rewards).
