### ISSUE TITLE
Admin Statistics issue

### ISSUE THREAD

**Issue by jerkitu** [dvandal/cryptonote-nodejs-pool#224]
Hi,

I have detected that with the value of "cleanupInterval" of the redis database, this applies a TTL to the keys of "workers" and "payments".

The problem is that when some of these keys expire, the administration statistics values ​​stop being the correct ones. They are not real.

Specifically the values ​​of:

totalPaid, totalRevenue, totalOwned

Can it be solved in some way?

Thank you.

**Comment by HKoody** [comment]
@jerkitu you can set TTL to -1 instead 1295969 (15 days TTL) to never expire and delete the data.

**Comment by HKoody** [comment]
@jerkitu you can set TTL to -1 instead 1295969 (15 days TTL) in Redis database to never expire and delete the data.

**Comment by ridd84** [comment]
Hi, I have the same problem,

**Comment by travis1234** [comment]
Same problem here too, total paid is off by a lot and causing profit value to be way off too. 
Thought I was hacked for a second when the wallet balance didn’t match the admin stats.

Would be great if someone could raise a PR to fix this.

**Comment by xpctxmin** [comment]
http://yourpool.com/admin.html
