### ISSUE TITLE
Score changes -- migration resets current block

### ISSUE THREAD

**Issue by jagerman** [dvandal/cryptonote-nodejs-pool#231]
The Score/slush reward changes in PR #227 have an unpleasant effect of resetting the current block when the pool is restarted with the updated code (even if using prop).  This happens because the score (whether flat with prop or exponential with score) now gets recorded into the `scores` key, while `shares_actual` records the actual shares submitted; since neither of these exist, the new pool acts as if on a new block.

I'm not sure exactly how best to deal with this.  One possibility is, during initialization, to check whether `coin:shares_actual:roundCurrent` and `coin:scores:roundCurrent` don't exist, *and* the pool is in prop reward mode, *and* `coin:shares:roundCurrent` exists then it could rename the current `coin:shares:roundCurrent` key to `coin:shares_actual:roundCurrent` and also copy it to `coin:scores:roundCurrent`.

**Comment by travis1234** [comment]
Is this still an issue or did you fix this already in the follow up PR?

**Comment by jagerman** [comment]
No, it's still an issue.  I was hoping for some guidance for @dvandal on how to approach a solution here.

There is actually a closely related issue that one person ran into (and I helped him sort it out manually): if an upgrade and restart happens while there are pending not-yet-unlocked blocks the payment may not get sent out (because it won't find any scores with the `coin:scores:roundXXX` name).

I think an outline of an approach to solve this is as follows (but I'd appreciate input):
- on startup, look for a `coin:blocks:upgrade136` (or some similar name - or perhaps a `score` key of a `coin:blocks:upgrade` hash, to allow it to be used for future redis changes?).  If found, don't do anything.  Otherwise:
- look for `coin:shares:roundCurrent` and any `coin:shares:roundXXX` for each `XXX` listed in `coin:blocks:candidates`.  If the key exists, and a `coin:scores:roundCurrent` or `coin:scores:roundXXX` *doesn't* exist, rename `coin:shares:roundWhatever` to `coin:shares_actual:roundWhatever` and also copy it to `coin:scores:roundWhatever`.
- set the `coin:blocks:upgrade136` key (or the hash key) so that this upgrade checking is only done once.

In fact, now that I think about it, it might be cleaner to do all of the above in a single lua script (so that it can be done synchronously in a single transaction).

**Comment by travis1234** [comment]
@jagerman I think I've run into the same issue. Block was unlocked but no payments have been sent. Before the block worker scores were saying either 0 or infinite.

I'm not sure if this was caused by restarting the pool or I also changed the database cleanup to 1 day and the block tool 3 days?

Either way would you be able to help with fixing the issue?

**Comment by travis1234** [comment]
@jagerman would you be able to help with manual payments for a previous block that didn't payout?

**Comment by jagerman** [comment]
Yes; I'm writing up some redis code right now that should fix this.

**Comment by travis1234** [comment]
thanks mate!
