### ISSUE TITLE
Add PPLNS

### ISSUE THREAD

**Issue by flychicken123** [dvandal/cryptonote-nodejs-pool#234]
Is there anyway to add pplns or pps to the payout?

**Comment by avense** [comment]
Yes you can add pps mode on pools.js if you know the comand for that......

**Comment by PandemRus** [comment]
avense, can you share code for pps?

**Comment by flychicken123** [comment]
@avense I don't know the command....Do you want to share?

**Comment by PsychoSterope** [comment]
I know there is a way to add PPS, PROP, and PPLNS to the universal/forknote pools which this one shares a core with. I've been trying to figure out how for the last two weeks, but I'm not smart enough for it. You can see it in action on one of the miner.rocks pools. (C.U.P. pool)

**Comment by mannie65** [comment]
@avense - If you could share that would be great, i'm also interested - TY

**Comment by mannie65** [comment]
OK, I'll have a look in my spare time and contribute it once I figure it out.

**Comment by sanich-rd** [comment]
Looking for a programmer who will make a pool of PROP in PPLNS. For work.$  Telegram @https_ssl
