### ISSUE TITLE
New Masari Algo (fast) is this pool setup for this algo?

### ISSUE THREAD

**Issue by theAltaran** [dvandal/cryptonote-nodejs-pool#236]
Been running your pool software for 24 hours now and im 300% effort.  Still haven't found a block.  Something just seems off to me.  Just wondering if this pool is setup to use MSR fast and what settings do I need to change?

![msr2](https://user-images.githubusercontent.com/36441358/41813088-19c3336e-76fd-11e8-8941-c72accd151d9.PNG)

Is this the right config I am supposed to be using?

**Comment by theAltaran** [comment]
This cant be right.......someone help?

![capture](https://user-images.githubusercontent.com/36441358/41814206-8df5b308-7714-11e8-80ae-10a09f1ceab0.PNG)

**Comment by theAltaran** [comment]
http://masari.altaran.us

**Comment by PsychoSterope** [comment]
It's not the pool, it's the competition. Two pools are sucking up all the blocks fast. One has a consistant 5.5MH/s and the other has 2-5MH/s. I have the same problem with my pool. I stopped mining on it for this week. https://masari.cnpools.space/
You can see them here. https://miningpoolstats.stream/masari

**Comment by theAltaran** [comment]
thanks......this effort is awful....figured we would of found 1 block by now
