### ISSUE TITLE
Frontend on a separate host, the separate server for a pool + cloudflare ssl

### ISSUE THREAD

**Issue by WaReZoR-UA** [dvandal/cryptonote-nodejs-pool#239]
Hi everybody!
there don't take place API inquiries if use https
who knows how it uses?

I apologize for my English =)

**Comment by PsychoSterope** [comment]
You must use the SSL api port 8119

**Comment by WaReZoR-UA** [comment]
If I change API port, and in the pool of config.json in frontend conf allow API SSL port, then nothing changes.

**Comment by WaReZoR-UA** [comment]
I ask you to describe the moment of installation of certificates a little in more detail pleas
Duplicate of

**Comment by PsychoSterope** [comment]
I just allowed cerbot to put them where it does and then pointed the config.json to the location. From your pic, it looks like you did the same thing.

When you start up your api, on the pool server, does it look similar to the pic I posted? If is does, then you need to make sure your config.js on your web host is pointing to the SSL api.
![sslapi](https://user-images.githubusercontent.com/22012344/42057437-ebb2e2aa-7ae2-11e8-8eaf-e80430251304.PNG)

**Comment by WaReZoR-UA** [comment]
![image](https://user-images.githubusercontent.com/38248645/42081327-d1352f36-7b8d-11e8-804e-3295b3ba23ed.png)
in frontend config I change port from 8004 to 8005
![image](https://user-images.githubusercontent.com/38248645/42081715-d2979bec-7b8e-11e8-9aaa-9e0d61d9870d.png)

**Comment by WaReZoR-UA** [comment]
I will try to explain everything step by step.
I have a domain and several subdomains. On them there are frontend of pools. All of them perfectly work without SSL. 
After I was registered on Cloudflare, have undergone testing of the domain and have received Origin Certificate for the domain and its sabdomens.

**Comment by PsychoSterope** [comment]
I understand now. Mine pools are setup exactly the same. When I added Cloudflare, no one was able to reach my websites because the web browser was saying they weren't safe. In my case I had to change the subdomain for each site and allow Cloudflare to handle the SSL for them.

Is this the problem you are having?

**Comment by WaReZoR-UA** [comment]
No, I have SSL on domain and subdomains to, sites opened with https can't reach API data because cert from cloudflare is incorect fore pool server. Other certificate is necessary for me for the API server, something like "letsencrypt"....

**Comment by PsychoSterope** [comment]
I think I am understanding your frustration. I decided upgrade my last pool to SSL today and it cannot load the API nor can I mine to the SSL socket. I have all of my pools setup the same way and with the latest update, suddenly I can't use SSL... I am not sure what's different, but something is.
