### ISSUE TITLE
Web port issue

### ISSUE THREAD

**Issue by PsychoSterope** [dvandal/cryptonote-nodejs-pool#24]
OK, so after a week of banging my head against my desk I think I have figured out my issue. I am currently running the same run of the mill forknote pool and I find it boring. I LOVE this one. I can get this pool up and running beautifully with Masari.

But here is my issue, I own and host my own server. It's a dual Xeon server board, 12 core 24 thread 48gb ecc ram beast, in my house with my ISP blocking port 80. So I go to apache/nginx and change the listening port to 8090. With the other forknote pool, no problem, works perfectly. With nodejs-pool, the webpage loads, but none of the stats or anything work. I've changed the config.js to reflect the proper localhost:8090. So what else do I need change in order for the webpages to populate correctly?

**Comment by VirtuBox** [comment]
If your ISP block the port 80, you can host the frontend on a cheap vps or even on a shared hosting plan. You will just have to edit the api variable in config.js.
Otherwise, you can use a proxy or a VPN to be able to use the port 80.

**Comment by PsychoSterope** [comment]
Seems like I got it solved!! http://www.masaripool.us/ Thanks!
