### ISSUE TITLE
What changed? 

### ISSUE THREAD

**Issue by bruceleeon** [dvandal/cryptonote-nodejs-pool#240]
I updated a couple of days ago... now when a miner has been mining a block for a while and they leave, they get nothing when the block hits.

**Comment by bruceleeon** [comment]
Upon further review, it looks like these commits screwed up my pools: https://github.com/dvandal/cryptonote-nodejs-pool/commit/f143ff83ad351695c0d30b72f33c3fd61cd8adcc

**Comment by bruceleeon** [comment]
His commits put round contributions on static on the worker contribution page, they make current estimate 0, and depreciate a worker's shares over the course of the block. In fact, if someone brings a block to 400% effort and leaves the pool, they can lose all their share of that block if the effort goes high enough without the worker there. My miners are pissed!

**Comment by flychicken123** [comment]
Man. You don't pay this guy. He is working for free.

**Comment by travis1234** [comment]
Just revert your code to before that commit and wait for a fix. Pretty simple workaround.

**Comment by bruceleeon** [comment]
@flychicken123 Bad assumption on your part (I have donated to dvandal - not jagerman that made the commit) Your statement offers nothing constructive, go stand under a falling rock.  @travis1234 That is what I am in the process of doing (restoring from backup).

**Comment by bruceleeon** [comment]
@dvandal please remove the slush mining updates from jagerman... it screwed up the normal pool stuff on the worker_stats page.

**Comment by travis1234** [comment]
@jagerman your contribution is definitely appreciated mate, especially since dvandal hasn't been contributing new code recently.

**Comment by bruceleeon** [comment]
@jagerman no snarky attitude, sorry if you took it that way. However, tagged releases aren't happening.
