### ISSUE TITLE
Fee wrong display

### ISSUE THREAD

**Issue by 20dec** [dvandal/cryptonote-nodejs-pool#242]
Hi,

If set fee 100 -> display 100%
If set fee 30 -> display 3%
If set fee 1 -> display 1%
![capture](https://user-images.githubusercontent.com/26274812/41954990-5b97fb22-7a08-11e8-9edd-391ed8345b71.PNG)

**Comment by 20dec** [comment]
Please give example if i wanna set 30% in config file. Thank you.

**Comment by PsychoSterope** [comment]
It depends on your coin. I also misstated. If you want a 30% then you would add a zero, I think, I am just guessing because I don't know what coin you are trying to setup.

**Comment by 20dec** [comment]
The fee is setting for pool. Why it's up to coins?
If block reward 1000, i set 30% then miners rewards is 700 and distribute.

**Comment by PsychoSterope** [comment]
I am making my self look like a dumbass.. I am tired I am sorry. Try putting a decimal place, like 30.0. Like on one of my pools for 1% I have 1.0 and it's 0.5% on the other so it's 0.5 in the config.

**Comment by 20dec** [comment]
30.0 is same 30 and display correct as my image in 1st post.
I think some code in frontend html file to display incorrect :(

**Comment by 20dec** [comment]
config.json convert to api display on browser is difference.
![untitled](https://user-images.githubusercontent.com/26274812/42041143-79403f40-7b1b-11e8-906f-e01a84284d63.png)

**Comment by PsychoSterope** [comment]
![pool_fee](https://user-images.githubusercontent.com/22012344/42043027-0abd41b8-7abb-11e8-940d-94084078eca0.PNG)

I just changed my Masari pool fee to do a test, it changed just fine. There must be another setting we are missing.
