### ISSUE TITLE
Instead of the wallet address, numbers were displayed. How to fix?

### ISSUE THREAD

**Issue by sanich-rd** [dvandal/cryptonote-nodejs-pool#251]
Tell me how to fix this record here. How could she have come?
![screenshot_8](https://user-images.githubusercontent.com/32831429/42051962-2582bed2-7b16-11e8-94ca-c0be7e110715.png)

**Comment by sanich-rd** [comment]
How to fix and remove this line?

**Comment by PsychoSterope** [comment]
Numbers are being displayed because in the config you have + setup as the diff and the . as the payment ID.

I can't answer on how to recover the lost hashes.

**Comment by muscleman** [comment]
remove from redis
