### ISSUE TITLE
DERO fix pls 

### ISSUE THREAD

**Issue by sanich-rd** [dvandal/cryptonote-nodejs-pool#255]
2018-06-29 21:15:22 [pool] (Thread 16) Error polling getblocktemplate {"code":-32600,"message":"Too many get block template requests per sec rejected by chain."}
"poolServer": {
        "enabled": true,
        "clusterForks": "auto",
        "poolAddress": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
        "intAddressPrefix": null,
        "blockRefreshInterval": 1000,
        "minerTimeout": 900,
        "sslCert": "./cert.pem",
        "sslKey": "./privkey.pem",
        "sslCA": "./chain.pem",
        "ports": [

**Comment by minhnt812018** [comment]
did you can mine by this dvandal pool.js

**Comment by sanich-rd** [comment]
I'm using the latest pool code.https: / / github.com / dvandal/

**Comment by muscleman** [comment]
yeah a fix for a dero pool would be nice, whats the eta?
