### ISSUE TITLE
RYO

### ISSUE THREAD

**Issue by BaikalMine** [dvandal/cryptonote-nodejs-pool#260]
Will there be added support for RYO?
https://github.com/ryo-currency

**Comment by bruceleeon** [comment]
no need to add support, it is already supported. Our pool will be up and running as soon as daemon syncs.
https://ryo.codpool.com

**Comment by DeadMan993** [comment]
# New miner address formats & prefixes

Preferably, use the ryo-address-validator tool that is built along with the daemon to verify miner's addresses. Please see the below commit to the official pool on how to integrate it:

https://github.com/ryo-currency/cryptonote-ryo-pool/commit/46dec687b1b3822b4e840a8a851c505c1d727171

Alternatively, below are the new prefixes

Legacy Long (Sumo): 0x2bb39a = 2864026
Legacy Sub (Subo): 0x8319a = 536986
Ryo Long (RYoL): 0x2ce192 = 2941330
Ryo Sub (RYoS): 0x2fe192 = 3137938
Ryo Kurz (RYoK): 0x2c6192 = 2908562
Ryo Kurz Sub (RYo): 0x3fe192 = 4186514 (Kurz sub-addresses are not yet supported by the core daemon or wallet binaries)

Note that the Kurz addresses are shorter (55 characters) and the default pool software may not recognize it is as valid.

**Comment by catalystjmf** [comment]
SO back to the original question, will RYO be supported on the dvandal fork?

**Comment by catalystjmf** [comment]
Bump!
