### ISSUE TITLE
Payment Processor Not Working

### ISSUE THREAD

**Issue by SixLitr** [dvandal/cryptonote-nodejs-pool#262]
I recently migrated my pool to a new VPS server and thought everything was working fine, until we hit a block and then a second one. Payments pending show 0 for all miners (myself included) and although the blocks are unlocked and the balance is in the wallet, payment processor (which is not throwing any errors) says "NO worker's balances reached the minimum payment threshold"

I'm losing miners here, and I can pay them manually, but that's not he point. I did a git pull for all the latest thinking that would help fix it, and even did a redis flushall because it was a fresh start, no luck.

I've been very happy with the pool for months, any help is appreciated - can provide any files code if needed.

Pool Website: https://loki-us-west.blockfoundry.org/#

**Comment by avense** [comment]
show your config.json

**Comment by SixLitr** [comment]
`{
    "poolHost": "loki-us-west.blockfoundry.org",

    "coin": "loki",
    "symbol": "LOKI",
    "coinUnits": 1000000000,
    "coinDecimalPlaces": 4,
    "coinDifficultyTarget": 120,
    "cnAlgorithm": "cryptonight_heavy",
    "cnVariant": null,
    "cnBlobType": 0,

    "logging": {
        "files": {
            "level": "info",
            "directory": "logs",
            "flushInterval": 5
        },
        "console": {
            "level": "info",
            "colors": true
        }
    },

    "poolServer": {
        "enabled": true,
        "clusterForks": "auto",
        "poolAddress": "xxxxxxxxxxx",
        "intAddressPrefix": 115,
        "blockRefreshInterval": 1000,
        "minerTimeout": 900,
        "sslCert": "../certs/cert.pem",
        "sslKey": "../certs/privkey.pem",
        "sslCA": "../certs/chain.pem",
        "ports": [
            {
                "port": 3131,
                "difficulty": 10000,
                "desc": "Low end hardware"
            },
            {
                "port": 3232,
                "difficulty": 10000,
                "desc": "Low end hardware - SSL",
		"ssl": true
            },
            {
                "port": 4141,
                "difficulty": 50000,
                "desc": "Mid range hardware"
            },
	    {
		"port": 4242,
		"difficulty": 50000,
		"desc": "Mid range hardware - SSL",
		"ssl": true
	    },
	    {
		"port": 5151,
		"difficulty": 100000,
		"desc": "High end hardware"
	    },
	    {
		"port": 5252,
		"difficulty": 100000,
		"desc": "High end hardware - SSL",
		"ssl": true
	    },
	    {
		"port": 7171,
		"difficulty": 1000000,
		"desc": "Cloud Mining / NiceHash"
	    },
            {
                "port": 8888,
                "difficulty": 200000,
                "desc": "Hidden port",
                "hidden": true
	    }
        ],
        "varDiff": {
            "minDiff": 5000,
            "maxDiff": 2000000,
            "targetTime": 120,
            "retargetTime": 30,
            "variancePercent": 30,
            "maxJump": 100
        },
        "paymentId": {
            "addressSeparator": "+"
        },
        "fixedDiff": {
            "enabled": true,
            "addressSeparator": "."
        },
        "shareTrust": {
            "enabled": true,
            "min": 10,
            "stepDown": 3,
            "threshold": 10,
            "penalty": 30
        },
        "banning": {
            "enabled": true,
            "time": 600,
            "invalidPercent": 25,
            "checkThreshold": 30
        },
        "slushMining": {
            "enabled": false,
            "weight": 300,
            "blockTime": 60,
            "lastBlockCheckRate": 1
         }
    },

    "payments": {
        "enabled": true,
        "interval": 1800,
        "maxAddresses": 50,
        "mixin": 10,
        "priority": 0,
        "transferFee": 50000000,
        "dynamicTransferFee": true,
        "minerPayFee" : true,
        "minPayment": 2000000000,
        "maxTransactionAmount": 0,
        "denomination": 100000000
    },

    "blockUnlocker": {
        "enabled": true,
        "interval": 30,
        "depth":30,
        "poolFee": 0.0,
        "devDonation": 0.0,
        "networkFee": 5.0
    },

    "api": {
        "enabled": true,
        "hashrateWindow": 600,
        "updateInterval": 5,
        "bindIp": "0.0.0.0",
        "port": 8117,
        "blocks": 30,
        "payments": 30,
        "password": "xxxxxxxxxxx",
        "ssl": true,
        "sslPort": 8118,
        "sslCert": "../certs/cert.pem",
        "sslKey": "../certs/privkey.pem",
        "sslCA": "../certs/chain.pem",
        "trustProxyIP": false
    },

    "daemon": {
        "host": "127.0.0.1",
        "port": 22023
    },

    "wallet": {
        "host": "127.0.0.1",
        "port": 22025
    },

    "redis": {
        "host": "127.0.0.1",
        "port": 6379,
        "auth": null,
        "db": 0,
        "cleanupInterval": 15
    },

    "notifications": {
        "emailTemplate": "email_templates/default.txt",
        "emailSubject": {
            "emailAdded": "Your email was registered",
            "workerConnected": "Worker %WORKER_NAME% connected",
            "workerTimeout": "Worker %WORKER_NAME% stopped hashing",
            "workerBanned": "Worker %WORKER_NAME% banned",
            "blockFound": "Block %HEIGHT% found !",
            "blockUnlocked": "Block %HEIGHT% unlocked !",
            "blockOrphaned": "Block %HEIGHT% orphaned !",
            "payment": "We sent you a payment !"
        },
        "emailMessage": {
            "emailAdded": "Your email has been registered to receive pool notifications.",
            "workerConnected": "Your worker %WORKER_NAME% for address %MINER% is now connected from ip %IP%.",
            "workerTimeout": "Your worker %WORKER_NAME% for address %MINER% has stopped submitting hashes on %LAST_HASH%.",
            "workerBanned": "Your worker %WORKER_NAME% for address %MINER% has been banned.",
            "blockFound": "Block found at height %HEIGHT% by miner %MINER% on %TIME%. Waiting maturity.",
            "blockUnlocked": "Block mined at height %HEIGHT% with %REWARD% and %EFFORT% effort on %TIME%.",
            "blockOrphaned": "Block orphaned at height %HEIGHT% :(",
            "payment": "A payment of %AMOUNT% has been sent to %ADDRESS% wallet."
        },
        "telegramMessage": {
            "workerConnected": "Your worker _%WORKER_NAME%_ for address _%MINER%_ is now connected from ip _%IP%_.",
            "workerTimeout": "Your worker _%WORKER_NAME%_ for address _%MINER%_ has stopped submitting hashes on _%LAST_HASH%_.",
            "workerBanned": "Your worker _%WORKER_NAME%_ for address _%MINER%_ has been banned.",
            "blockFound": "*Block found at height* _%HEIGHT%_ *by miner* _%MINER%_*! Waiting maturity.*",
            "blockUnlocked": "*Block mined at height* _%HEIGHT%_ *with* _%REWARD%_ *and* _%EFFORT%_ *effort on* _%TIME%_*.*",
            "blockOrphaned": "*Block orphaned at height* _%HEIGHT%_ *:(*",
            "payment": "A payment of _%AMOUNT%_ has been sent."
        }
    },

    "email": {
        "enabled": true,
        "fromAddress": "support@blockfoundry.org",
        "transport": "sendmail",
        "sendmail": {
            "path": "/usr/sbin/sendmail"
        },
        "smtp": {
            "host": "smtp.example.com",
            "port": 587,
            "secure": false,
            "auth": {
                "user": "username",
                "pass": "password"
            },
            "tls": {
                "rejectUnauthorized": false
            }
        },
        "mailgun": {
            "key": "your-private-key",
            "domain": "mg.yourdomain"
        }
    },

    "telegram": {
        "enabled": false,
        "botName": "",
        "token": "",
        "channel": "",
        "channelStats": {
            "enabled": false,
            "interval": 30
        },
        "botCommands": {
            "stats": "/stats",
            "enable": "/enable",
            "disable": "/disable"
        }
    },
    
    "monitoring": {
        "daemon": {
            "checkInterval": 60,
            "rpcMethod": "getblockcount"
        },
        "wallet": {
            "checkInterval": 60,
            "rpcMethod": "getbalance"
        }
    },

    "prices": {
        "source": "cryptopia",
        "currency": "USD"
    },
    
    "charts": {
        "pool": {
            "hashrate": {
                "enabled": true,
                "updateInterval": 60,
                "stepInterval": 1800,
                "maximumPeriod": 86400
            },
            "miners": {
                "enabled": true,
                "updateInterval": 60,
                "stepInterval": 1800,
                "maximumPeriod": 86400
            },
            "workers": {
                "enabled": true,
                "updateInterval": 60,
                "stepInterval": 1800,
                "maximumPeriod": 86400
            },
            "difficulty": {
                "enabled": true,
                "updateInterval": 1800,
                "stepInterval": 10800,
                "maximumPeriod": 604800
            },
            "price": {
                "enabled": true,
                "updateInterval": 1800,
                "stepInterval": 10800,
                "maximumPeriod": 604800
            },
            "profit": {
                "enabled": true,
                "updateInterval": 1800,
                "stepInterval": 10800,
                "maximumPeriod": 604800
            }
        },
        "user": {
            "hashrate": {
                "enabled": true,
                "updateInterval": 180,
                "stepInterval": 1800,
                "maximumPeriod": 86400
            },
            "payments": {
                "enabled": true
            }
        }
    }
}
`

**Comment by avense** [comment]
try put this
"fixBlockHeightRPC": true


```
"blockUnlocker": {
    "enabled": true,
    "interval": 30,
    "depth":30,
    "poolFee": 0.0,
    "devDonation": 0.0,
    "networkFee": 5.0,
    "fixBlockHeightRPC": true
```

reload pool and wait for block and test it

**Comment by SixLitr** [comment]
Thanks, I added it.  We are syncing to the latest block height however, how does this help with payments? (curious, in learning mode)

**Comment by avense** [comment]
Friend simply because it's not a payments problem.

The blockunlocker is not giving the share reward to the miners.

**Comment by SixLitr** [comment]
Found a new block, and its still unlocking, but the unlocker is throwing this error `2018-07-02 16:38:21 [unlocker] No blocks candidates in redis
2018-07-02 16:38:51 [unlocker] Error with getblockheaderbyheight RPC request for block ba598a8e0f883e5fd321a4ee5836f9f14de30dd4e60587e10bacd8e1c4020c56:1530574722:2293974059:2161929718:2161929718 - {"code":-2,"message":"Too big height: 44098, current blockchain height = 44098"}
`

**Comment by SixLitr** [comment]
A second block now, and its orphaned. I am removing the line `"fixBlockHeightRPC": true ` as it seems to be making things worse. I have this pool setup for LOKI and have not needed this before.

**Comment by travis1234** [comment]
Maybe rebuild the node deamon from source and re import the blockchain. Sounds like a deamon error maybe.

**Comment by SixLitr** [comment]
Actually, funny you mention that I did just see a potential daemon error. I restarted it.

**Comment by SixLitr** [comment]
Quick update, if anyone is reading this thread. In the end, even a daemon re-sync didn't work and I had to wipe the server and rebuild it. Wish I knew what the actual issue was.
