### ISSUE TITLE
Deamon method not found 

### ISSUE THREAD

**Issue by samvicky26** [dvandal/cryptonote-nodejs-pool#273]
Daemon

Last check: about a minute ago
Last status: failLast response:{"code":-32601,"message":"Method not found"}
Last fail: about a minute ago
#
![screenshot_20180709-095426_samsung internet](https://user-images.githubusercontent.com/13923408/42430662-2c9e8354-835e-11e8-8d37-ef6b50ef7f07.jpg)
Last fail response:{"code":-32601,"message":"Method not found"}

**Comment by avense** [comment]
Not software problem.
its rpc call
But try this: "sync_blocks"
You have to know the rpc call of the daemon

**Comment by flychicken123** [comment]
@avense I got the same issue here. wallet shows fine, but daemon shows same error message here. how to run that sync_blocks command.
