### ISSUE TITLE
Lost Connect when two miner running together

### ISSUE THREAD

**Issue by flychicken123** [dvandal/cryptonote-nodejs-pool#276]
I am not sure this problem is the pool or miner itself. They said their miner got tons of bad hash when they were running two miner together.

**Comment by avense** [comment]
se your "vardiff" function on config file

**Comment by flychicken123** [comment]
@avense       "minDiff": 2000,
            "maxDiff": 20000000,
            "targetTime": 60,
            "retargetTime": 30,
            "variancePercent": 30,
            "maxJump": 100
this is mine

**Comment by avense** [comment]
mine is that

"varDiff": {
            "minDiff": 100,
            "maxDiff": 100000000,
            "targetTime": 120,
            "retargetTime": 30,
            "variancePercent": 30,
            "maxJump": 25
