### ISSUE TITLE
Anybody know what option should I put on current ETN?

### ISSUE THREAD

**Issue by flychicken123** [dvandal/cryptonote-nodejs-pool#277]

**Comment by avense** [comment]
what option?

**Comment by flychicken123** [comment]
@avense cnBlobType

**Comment by avense** [comment]
@flychicken123  i tkink 2

**Comment by DigitalDeviator** [comment]
For sure ETN is not a Forknote coin, so it's definitely not cnBlobType:2

ETN is a Monero-clone so it should be cnBlobType:0
