### ISSUE TITLE
Custom Translations

### ISSUE THREAD

**Issue by felix920506** [dvandal/cryptonote-nodejs-pool#284]
Not every language is supported and I want the ability to make custom translations to make the site easier for more people to read.

**Comment by swa74** [comment]
Пишите разработчику и отправляйте готовый перевод ему

**Comment by felix920506** [comment]
Sorry I can’t read that.

**Comment by Stardock2018** [comment]
Пишите разработчику и отправляйте готовый перевод ему
Write to the developer and send the finished translation to him
