### ISSUE TITLE
Dero Coin

### ISSUE THREAD

**Issue by swa74** [dvandal/cryptonote-nodejs-pool#29]
"coin": "dero",
    "symbol": "DERO",
    "coinUnits": 1000000000000,
    "coinDifficultyTarget": 120, 
    "cnVariant": null,

You can add an example, the pool has earned
http://dero.minexmr24.ru

**Comment by swa74** [comment]
{
    "coin": "dero",
    "symbol": "DERO",
    "coinUnits": 1000000000000,
    "coinDifficultyTarget": 120,
    "cnVariant": null,

    "logging": {
        "files": {
            "level": "info",
            "directory": "logs",
            "flushInterval": 5
        },
        "console": {
            "level": "info",
            "colors": true
        }
    },

    "poolServer": {
        "enabled": true,
        "clusterForks": "auto",
        "poolAddress": "dERoRbLPV3SbUbcQwXKhKyKSZommw3PbyeRJxAsZAwbjAZin1Twj8dWTLcGq79v3ogQFNHhhB2DXFWNM6HQKvqWC8Aa3L9CnG7",
        "blockRefreshInterval": 1000,
        "minerTimeout": 900,
        "sslCert": "./cert.pem",
        "sslKey": "./privkey.pem",
        "sslCA": "./chain.pem",
        "ports": [
 		    {
                "port": 42222,
                "difficulty": 100,
                "desc": "Low end hardware"
            },
            {
                "port": 43333,
                "difficulty": 1000,
                "desc": "Low end hardware"
            },
            {
                "port": 44444,
                "difficulty": 5000,
                "desc": "Mid range hardware"
            },
            {
                "port": 45555,
                "difficulty": 10000,
                "desc": "High end hardware"
            },
            {
                "port": 47777,
                "difficulty": 400000,
                "desc": "Cloud-mining / NiceHash"
            }
        ],
        "varDiff": {
            "minDiff": 10,
            "maxDiff": 500000,
            "targetTime": 20,
            "retargetTime": 30,
            "variancePercent": 30,
            "maxJump": 100
        },
        "paymentId": {
            "addressSeparator": "+"
        },
        "fixedDiff": {
            "enabled": true,
            "addressSeparator": "."
        },
        "shareTrust": {
            "enabled": true,
            "min": 10,
            "stepDown": 3,
            "threshold": 10,
            "penalty": 30
        },
        "banning": {
            "enabled": true,
            "time": 600,
            "invalidPercent": 25,
            "checkThreshold": 30
        },
        "slushMining": {
            "enabled": false,
            "weight": 300,
            "blockTime": 60,
            "lastBlockCheckRate": 1
         }
    },

    "payments": {
        "enabled": true,
        "interval": 300,
        "maxAddresses": 50,
        "mixin": 5,
        "priority": 0,
        "transferFee": 50000000,
        "dynamicTransferFee": true,
        "minerPayFee" : true,
        "minPayment": 1000000000000,
        "maxTransactionAmount": 0,
        "denomination": 1000000000
    },

    "blockUnlocker": {
        "enabled": true,
        "interval": 30,
        "depth": 10,
        "poolFee": 0.5,
        "devDonation": 0.2
    },

    "api": {
        "enabled": true,
        "hashrateWindow": 600,
        "updateInterval": 5,
        "port": 8117,
        "blocks": 30,
        "payments": 30,
        "password": "2012",
        "ssl": false,
        "sslPort": 8119,
        "sslCert": "./cert.pem",
        "sslKey": "./privkey.pem",
        "sslCA": "./chain.pem",
        "trustProxyIP": false
    },

    "daemon": {
        "host": "127.0.0.1",
        "port": 18060
    },

    "wallet": {
        "host": "127.0.0.1",
        "port": 18061
    },

    "redis": {
        "host": "127.0.0.1",
        "port": 6379,
        "auth": null,
        "cleanupInterval": 1
    },

    "email": {
        "enabled": false,
        "templateDir": "email_templates",
        "templates": ["worker_connected", "worker_banned", "worker_timeout"],
        "variables": {
            "POOL_HOST": "poolhost.com"
        },
        "fromAddress": "your@email.com",
        "transport": "sendmail",
        "sendmail": {
            "path": "/usr/sbin/sendmail"
        },
        "smtp": {
            "host": "smtp.example.com",
            "port": 587,
            "secure": false,
            "auth": {
                "user": "username",
                "pass": "password"
            }
        },
        "mailgun": {
            "key": "your-private-key",
            "domain": "mg.yourdomain"
        }
    },
    
    "monitoring": {
        "daemon": {
            "checkInterval": 60,
            "rpcMethod": "getblockcount"
        },
        "wallet": {
            "checkInterval": 60,
            "rpcMethod": "getbalance"
        }
    },

    "prices": {
        "source": "cryptonator",
        "currency": "USD"
    },

    "charts": {
        "pool": {
            "hashrate": {
                "enabled": true,
                "updateInterval": 30,
                "stepInterval": 180,
                "maximumPeriod": 86400
            },
			"miners": {
                "enabled": true,
                "updateInterval": 30,
                "stepInterval": 180,
                "maximumPeriod": 86400
            },			
            "workers": {
                "enabled": true,
                "updateInterval": 30,
                "stepInterval": 180,
                "maximumPeriod": 86400
            },
            "difficulty": {
                "enabled": true,
                "updateInterval": 60,
                "stepInterval": 180,
                "maximumPeriod": 604800
            },
            "price": {
                "enabled": true,
                "updateInterval": 180,
                "stepInterval": 1080,
                "maximumPeriod": 604800
            },
            "profit": {
                "enabled": true,
                "updateInterval": 180,
                "stepInterval": 1080,
                "maximumPeriod": 604800
            }
        },
        "user": {
            "hashrate": {
                "enabled": true,
                "updateInterval": 30,
                "stepInterval": 180,
                "maximumPeriod": 86400
            },
            "payments": {
                "enabled": true
            }
        }
    }
}

**Comment by dvandal** [comment]
Thanks, example configuration has been added.
