### ISSUE TITLE
No data on website

### ISSUE THREAD

**Issue by dahifi** [dvandal/cryptonote-nodejs-pool#295]
I've tried serving the files in both apache and nxginx, and I got nothing. The home page has a spinning circle, and other pages just give me n/a where the data is supposed to be. 

config.json:
```
   "api": {
        "enabled": true,
        "hashrateWindow": 600,
        "updateInterval": 5,
        "bindIp": "0.0.0.0",
        "port": 8117,
        "blocks": 30,
        "payments": 30,
        "password": "myPassword",
        "ssl": false,
        "sslPort": 8119,
        "sslCert": "./cert.pem",
        "sslKey": "./privkey.pem",
        "sslCA": "./chain.pem",
        "trustProxyIP": true
    },

```
config.js
var api = "http://publicIP:8117"

'curl http://<publicIP>:8117/stats' returns a host of JSON data.

**Comment by swa74** [comment]
Для примера что должно показываться 
http://minexmr24.ru:8117/stats

**Comment by dahifi** [comment]
I was able to get it working by saving my index.html and config.js files locally and opening it that way. Then the pool page started working on the remote server. 

Not sure what the hell was the problem.
