### ISSUE TITLE
Admin Area Block Payments

### ISSUE THREAD

**Issue by swanseahost** [dvandal/cryptonote-nodejs-pool#296]
Hi All,

I have an ombre pool and the block reward is 90.  I have mined 490 blocks so this should be 490 * 90 = 44,000 approx.

In the admin area it is showing 440,000 and payments are going out with the extra 0 but not sure if the payments are right as there is a decimal issue somewhere.

Thanks

**Comment by DigitalDeviator** [comment]
Do you have the right number set in the config.json for "CoinUnits"?

coinUnits | Minimum units in a single coin, see COIN constant in DAEMON_CODE/src/cryptonote_config.h
