### ISSUE TITLE
Block reward bonuses

### ISSUE THREAD

**Issue by helbadini** [dvandal/cryptonote-nodejs-pool#301]
Would it be possible to make it so pool owners can chose to increase the block reward paid to miners as an incentive? Such as +25%, +50%, +75% and +100%, etc...

Thanks!

**Comment by avense** [comment]
@helbadini  like that?
![minerreward](https://user-images.githubusercontent.com/15719937/42941495-d7ff4c3a-8b54-11e8-9cec-f173e804d09a.jpg)

**Comment by travis1234** [comment]
@avense I would be interested in your block reward bonus feature for the miner who finds the block.... would you be able to share your changes to enable that?

@helbadini global bonus feature would also be cool.

**Comment by avense** [comment]
@helbadini nooooooooooooo


is not slush is disable.

It's me who adds in the code a formula that the one who finds the block receives 1% more even if the shares are less than the others.
In other words, the miner that finds the block receives according to the shares of the round plus 1% of the block bonus.

Okay but if you do not want, it's okay.

Here's an example of how my pools are

`Block 54761 reward to miner ZuCCfkHNJMvGdDucbb4LisTZM4zQmHz4EAs1NK1FHNLVPShYqmuL4DH1JtEW2mdh5vBdtAPxvxxxxxxxxxxxxxxxxK3yb9xuaBMxzNZ as 1 percent of reward: 316948308000`

**Comment by helbadini** [comment]
@avense actually i would love to use your code if you're willing to share it... Regardless yes the bonus I'm suggesting would come out of the pools own wallet and profits.

**Comment by SixLitr** [comment]
@avense I am also interested in this block reward bonus. I am willing to try it out and report back how it works as well.

**Comment by avense** [comment]
@helbadini  So if you want to give a reward of the profits to those who find the block then you have to write in redis and use this for example

redisClient.hincrby (config.coin + ': workers:' + miner.login, 'balance', rewardAmount, function (err, result)

I use this form in my bytecoin pool who find the block receives a reward and this reward comes from the profits

**Comment by OptimusBlue** [comment]
@avense 
This would be a fantastic feature, could you maybe elaborate more on how to implement?
Thanks
