### ISSUE TITLE
Turtlecoin config.json 

### ISSUE THREAD

**Issue by nDman** [dvandal/cryptonote-nodejs-pool#302]
Please share your Turtlecoin config file, Thank.

**Comment by Z3RO-COOL** [comment]
you getting errors too?

**Comment by prox443** [comment]
Have you managed to send payments from the pool?
This pool no longer seems compatible with the turtlecoin ./walletd

**Comment by avense** [comment]
@prox443  This is because you do not read.

daemonType: bytecoin
Easy

**Comment by close0ne** [comment]
daemonType: bytecoin doesnt work, you will find block etc. but blocks will not bu unlocked and will be showned as orphans, even if they are valid blocks.

I let daemontype default and just edit /lib/paymentProcessor.js so paymans works as for daemonType byecoin

**Comment by wahaobi** [comment]
@close0ne paymentProcessor.js   How to modify

**Comment by muscleman** [comment]
new config available
