### ISSUE TITLE
No charts available on Dashborad after latest branch update 

### ISSUE THREAD

**Issue by tetyanamyr** [dvandal/cryptonote-nodejs-pool#317]
After latest update no charts available on Dashboard (all charts enabled in config file).

**Comment by zairoo** [comment]
pool upgrade no display 1h 6h 24h charts

**Comment by fmarines** [comment]
same thing here, no charts available.

**Comment by tetmyr** [comment]
@bruceleeon thanks for your advice! 
I downloaded release version 1.3.5, but that didn't solve my issue with charts. 
By some reason API does not return charts objects at all, it has only "blocks" object info.
Any ideas how to fix it and where I should look into?
Thanks.

**Comment by muscleman** [comment]
see #314
