### ISSUE TITLE
Ban Address

### ISSUE THREAD

**Issue by DigitalDeviator** [dvandal/cryptonote-nodejs-pool#319]
Hi, I was wondering if there is a way to ban/block a specific address. 

I want to block a botnet that is using a dynamic IP, so simply firewalling it doesn't work.

Any suggestions?

**Comment by xlp0rk0lx** [comment]
I think that the best solution will be share the log with us. Maybe a little bash script that read the log file and set specific iptables rule at runtime can be enough

**Comment by muscleman** [comment]
yeah, this is prolly a networking issue.
pool bans are temporary
