### ISSUE TITLE
It is strongly required to add this function to display

### ISSUE THREAD

**Issue by youzidebaba** [dvandal/cryptonote-nodejs-pool#321]
It is strongly required to add this function to display,It is better to show the state of the ore pool.
https://crypto9coin.cf/pyx/
@dvandal 
![image](https://user-images.githubusercontent.com/37879101/43460690-f81a100a-9503-11e8-9cc6-08e79ef4f3a1.png)

![image](https://user-images.githubusercontent.com/37879101/43460629-c2d67fbe-9503-11e8-9a1e-9a058e1932cf.png)

**Comment by avense** [comment]
@youzidebaba  nice template.
Make a pull request please
