### ISSUE TITLE
Invalid password on all log files. 

### ISSUE THREAD

**Issue by dahifi** [dvandal/cryptonote-nodejs-pool#322]
I'm a bit unclear on how to properly set this up. My node files are running under a user home directory, and static web files under /var/www. The log directory is writing to the user home. 

I assume that I need to change the config.json logging directory to write to the static web directory?

**Comment by muscleman** [comment]
depending on the coin you'll need to --rpc-disable-login or --rpc-legacy-security at the wallet rpc end or use the muscleman fork on github
