### ISSUE TITLE
I'm I missing something?

### ISSUE THREAD

**Issue by TheBudda** [dvandal/cryptonote-nodejs-pool#33]
Hi, love the pool and the front end. Well done dude \o/

I have followed your install notes, but I get an error with pool.js, well, that's what it looks like to me. I have attached some screenshots for you to view

I am 60 years old housebound and look to run my own pool, for fun and something to do. Sorry for the noob here, I am new to all this mining pool stuff but not mining!! 

![screenshot 2018-04-24 09 17 17](https://user-images.githubusercontent.com/16983376/39174837-a9f50b92-47a0-11e8-93f6-3b7fc9fa59fc.png)
![graft pool error](https://user-images.githubusercontent.com/16983376/39174838-aa104222-47a0-11e8-96d0-8488d53c8035.png)

**Comment by swa74** [comment]
{
                "port": 9999,
                "difficulty": 20000,
                "desc": "SSL connection",
                "ssl": **false**
            }
