### ISSUE TITLE
[FEATURE REQUEST] Ability to customize when emails are sent.

### ISSUE THREAD

**Issue by unsivilaudio** [dvandal/cryptonote-nodejs-pool#332]
First off let me just say that this project is amazing.  Started my first pool [here](http://stellite.ethospool.org) and was fairly easy to set up and configure.

I did opt to use mailgun's services, and was thinking with the 10k free email limit, a good portion of that would get used up with superfluous messages in the current configuration.  For example I don't need to know every time my worker gets connected to the pool or when the pool unlocks a block.  I, and others I'm sure, would appreciated a way to disable some notification emails.  Wasn't sure if I could just comment out the code in the config.json or not.  Any help would be greatly appreciated in this issue.

Thanks
Admin
stellite.ethospool.org

**Comment by ossii79** [comment]
I'm interested in this as well, some 1/0 or true/false for the various types of notifications would be nice.
As OP also asks, is a workaround simply to comment out the whole line? or empty the text?

Ossii
