### ISSUE TITLE
Pool found block but it's not unblocked the block!

### ISSUE THREAD

**Issue by javietanh** [dvandal/cryptonote-nodejs-pool#333]
Please check it, what the problem here? problem with redis or pool software?
![image](https://user-images.githubusercontent.com/5907838/44068766-00f2e164-9fa6-11e8-84d3-83ef059d235f.png)
![image](https://user-images.githubusercontent.com/5907838/44068781-12db4c04-9fa6-11e8-8fbc-6943e17f15a1.png)
![image](https://user-images.githubusercontent.com/5907838/44068806-23c9bd66-9fa6-11e8-976e-8f55e5ee23dd.png)
![image](https://user-images.githubusercontent.com/5907838/44068822-30cd8ba0-9fa6-11e8-9c2c-4550f7020092.png)

Cheers.

**Comment by nathjyo** [comment]
It looks like you haven’t put the pool address in the front end config.json file

**Comment by javietanh** [comment]
already but not work. anyway my api query for block not working
https://poolhost/get_blocks -> (This page isn’t working) other api working fine.

**Comment by prox443** [comment]
Same issue.
