### ISSUE TITLE
Algorithm: Cryptonight (Monero v7)

### ISSUE THREAD

**Issue by TheBudda** [dvandal/cryptonote-nodejs-pool#335]
Hi,

How can I change my pools to show the correct Algorithm: Graft, Stellite, Electroneum, are showing all Monero V7. How can I change this? Also, how can I change the decimal point on my Stellite pool for the reward? Mine is showing 151.5482 XTL! It should show 15154.820000? 

Please help

**Comment by avense** [comment]
"cnAlgorithm":"cryptonight","cnVariant":1,"cnBlobType":0,

**Comment by TheBudda** [comment]
Hi avense,

this is my Stellite.json file

 "daemonType": "default",
    "cnAlgorithm": "cryptonight",
    "cnVariant": 1,
    "cnBlobType": 0,

**Comment by TheBudda** [comment]
![screenshot 2018-08-14 19 09 53](https://user-images.githubusercontent.com/16983376/44109742-af03023a-9ff5-11e8-8898-459c64ac7a3c.png)

**Comment by TheBudda** [comment]
you can see in my screenshot above its saying (Algorithm: Cryptonight (Monero v7)

**Comment by avense** [comment]
now understand

"cnAlgorithm":"cryptonight","cnVariant":3,"cnBlobType":0,

**Comment by unsivilaudio** [comment]
set coin units to 100, and coin decimal places 4, at least thats what I figured out for my [pool](http://stellite.ethospool.org)

**Comment by TheBudda** [comment]
yes yes, that worked! now showing> Algorithm: Cryptonight (Stellite v7)

thank you avense and unsivilaudio much appreciated your help

**Comment by TheBudda** [comment]
@avense and @unsivilaudio 

Can you please tell the cnVariant": for Electroneum (ETN) I am showing (Cryptonight (Monero v7) when it should be Cryptonight (Original)

**Comment by avense** [comment]
cnAlgorithm":"cryptonight","cnVariant":0,"cnBlobType":0

**Comment by TheBudda** [comment]
@avense  thank you, dude, I really appreciate your help. I am now all sorted
