### ISSUE TITLE
Block orphaned

### ISSUE THREAD

**Issue by Stardock2018** [dvandal/cryptonote-nodejs-pool#337]
Can someone help me were to track down a problem? About 4 days ago every block orphaned

Myztic 

I did not change anything no updates

8/16/2018, 12:02:49 PM | 0 | 48699 | 6250274 | a93e2e77ddf2b42bef59f3e53c0f5b2d425675d30a5e6f53d7e4ff02ddee422f | 2434% |  
-- | -- | -- | -- | -- | -- | --
8/16/2018, 10:31:18 AM | 0 | 48653 | 6403264 | a13426478b12c438e3fbb099dd9c50ce6a7c55c9eabc5f452874fd2acac4f351 | 51% |  
8/16/2018, 10:13:54 AM | 0 | 48639 | 5754200 | db9b9b78b997d754a43fbaf92aca88a9e3e41e47952fe66d0540f3795423214a | 30% |  
8/16/2018, 9:47:45 AM | 0 | 48622 | 4641614 | 12207374bc3944d5ef74ccc611aa756a830f4e8bfe476aaaf7eb7a260f896711 | 4% |  
8/16/2018, 9:46:44 AM | 0 | 48621 | 4718823 | acd0036da7b110247941602e3adbddd9b5bf8ed0475f058cc365417edab5f233 | 98% |  
8/16/2018, 8:47:00 AM | 0 | 48595 | 5742598 | 849ed0da940d9b8dc749551070abb691fe17133bb3cb92709ca0eca8ac68194b | 2398% |  
8/14/2018, 7:37:36 AM | 0 | 47130 | 5489732 | 39f7842d96d6eb5a2ce8e69e757b8b1f0d1ae43861cdb40bf3e0c55006a1ee8b | 2073% |  
8/14/2018, 6:35:33 AM | 0 | 47098 | 5199740 | 2905ddf6420ba5b745267a119a90f7f8b0ebb85a930465e8ee622a68064898ab | 310% |  
8/14/2018, 5:00:20 AM | 0 | 47061 | 7394549 | 33e2f83cd0cc358c3e9b3ae02dc483d84ba5cbe53e9da5dfbfbdcf17d10aa072 | 1452% |  
8/14/2018, 3:26:11 AM | 0 | 47013 | 7230131 | 33742c5932af8f0fb17d99f521220b4d3d43760d64703a55677faf1b10997f16 | 84% |  
8/14/2018, 2:26:46 AM | 0 | 46983 | 6829738 | 007f1a30ffe43f9c2ba0581c1408d7c7c78f0a9f3377f61a932fa871be824c32 | 1465% |  
8/13/2018, 11:58:03 PM | 0 | 46902 | 5489248 | 09bc269237e9300ef3c516c48a62c6b98f09ad8a7a8ee47a4eef089182e629f6 | 45% |  
8/13/2018, 11:36:39 PM | 0 | 46887 | 5047411 | 676f6b48c034cfd308eba4398fc729586a3d781a91dad2ac37df6a1c5a7b2031 | 15% |  
8/13/2018, 11:29:14 PM | 0 | 46882 | 4727543 | c9ea0b97c4e3b030876fbac3eb9de2ff0cce4d42ea4a023afc3353aa14ac0a27 | 1745% |  
8/13/2018, 9:01:29 PM | 0 | 46817 | 5490809 | 2f3b1d5eacb921e4a5cc22fb5a6c843373a6cc3c5615d7473b1dc18803fbc5d9 | 103% |  
8/13/2018, 8:22:43 PM | 0 | 46789 | 4158346 | 19e1682bd8459ac936a2abe0fbf122620ae51ca91078603202ddff50268957c6 | 1477% |  
8/13/2018, 6:33:48 PM | 0 | 46733 | 3912085 | 5caaf82fdf80f358141c3c7d543ed35f93c7b5e4a188126d994265742a1b6658 | 66% |  
8/13/2018, 6:15:25 PM | 0 | 46722 | 3604572 | d393c45166d364a506653a1e4a9cbc554112f2be51a69b8b883583d5d40d67ef | 1041% |  
8/13/2018, 5:50:22 PM | 0 | 46708 | 3531974 | f0c4ede1c5ee747c12049f9d72696d8fc2d5a6abaec6933002a03accf76c2fc5 | 26% |  
8/13/2018, 5:43:03 PM | 0 | 46702 | 3893057 | 007f6de4874d8f991d0b6be0a61256b67241e8295b0ac061ad08d2711a9528f5 | 74% |  
8/13/2018, 5:15:23 PM | 0 | 46690 | 3617132 | 0df9380867926601b1f9890b23c9b58a6c931eef77f0bf2f3979034db13e6132 | 71% |  
8/13/2018, 4:35:28 PM | 0 | 46676 | 4271355 | 589f3338047350cdf446139652b9d79cba5dab64cbb2fa59bd4d25d2104d30ff | 154% |  
8/13/2018, 3:27:37 PM | 0 | 46646 | 4718958 | 3df9157bd90f59723273e4c2c0594ad134ac2f82ae27fb080d3009d8ff208f7b | 746% |  
8/13/2018, 1:26:58 PM | 0 | 46585 | 4801881 | 83913dfb2c8e8f9394cd190d6c11422f6d1ef30f29f6c1f861204f8abec7ede7 | 16% |  
8/13/2018, 1:21:23 PM | 0 | 46581 | 5357081 | 82a262998d60c08f547db84050b1635592ff647e39a23f853e96dc434bf336b5 | 80% |  
8/13/2018, 12:39:11 PM | 0 | 46564 | 4896547 | 1c05384333816d18f9a37ecb18f61e65d3e42adde275675f1c097290897b08d5 | 305% |  
8/13/2018, 12:23:39 PM | 0 | 46555 | 5166745 | 407ca487fd073f8e1ac9776caa66a01fe15a46e7b1c704804d0044b6e926e010 | 103% |  
8/13/2018, 11:27:24 AM | 0 | 46502 | 4833194 | 71e3ed2cd11a6217b3622c664f2f6a230389e14fdf2809e072f7ab1ea1a502e6 | 93% |  
8/13/2018, 10:47:58 AM | 0 | 46501 | 5477074 | cc10bff1ce0001352221366680ce2cdb432f59d56149414bb9b3a497a7c49fbb | 29% |  
8/13/2018, 10:36:17 AM | 0 | 46500 | 6207736 | b28913a3f5823e36c4e531e5863e7262874e0d69ce1b2912fa2370a40491ab93 | 32%

**Comment by avense** [comment]
You have to give more information on how you have the configuration of the pool.

Mine does not have problems

http://mzt.avensat.com

**Comment by Stardock2018** [comment]
this just started on the 9:27 am On the 13 your pool hasn't mined anything since the  Aug 2
my daemon always run i shut the pool down for now.

  "poolHost": "myztic",
    "coin": "myztic",
    "symbol": "MZT",
    "coinUnits": 1000000000,
    "coinDecimalPlaces": 4,
    "coinDifficultyTarget": 120,

    "daemonType": "default",
    "cnAlgorithm": "cryptonight",
    "cnVariant": 1,
    "cnBlobType": 0,

    "logging": {
        "files": {
            "level": "info",
            "directory": "logs",
            "flushInterval": 5
        },
        "console": {
            "level": "info",
            "colors": true
        }
    },

**Comment by Stardock2018** [comment]
Question in the peers list what is grey and white. Does that mean the same as grey and white list in firewall config in router? 
Sorry for the dum question

**Comment by avense** [comment]
i think its your daemon,because the setup its everything ok

**Comment by Stardock2018** [comment]
2018-08-17 18:51:18.079 [P2P6]  WARN    net.p2p src/p2p/net_node.inl:755        [67.205.140.68:18190 OUT] COMMAND_HANDSHAKE invoke failed. (-4, LEVIN_ERROR_CONNECTION_TIMEDOUT)
2018-08-17 18:51:18.079 [P2P4]  WARN    net.p2p src/p2p/net_node.inl:804        [67.205.140.68:18190 OUT] COMMAND_HANDSHAKE Failed
2018-08-17 18:51:18.079 [P2P4]  WARN    net.p2p src/p2p/net_node.inl:1191       Failed to connect to any of seed peers, trying fallback seeds
2018-08-17 18:51:18.079 [P2P4]  WARN    net.p2p src/p2p/net_node.inl:1202       Failed to connect to any of seed peers, continuing without seeds

**Comment by pcca-matrix** [comment]
@Stardock2018 
is the demon and the pool on the same server ?
do you have enough cpu power ?

try "blockRefreshInterval": 1500

**Comment by Stardock2018** [comment]
Yes the Demon and the pool are on the same server and yes enough cpu power i am runnning 3 coins on the 1 machine. and the same thing is happening to all the coins. I have tried shutting down all but 1 coin and i still get the same error.

**Comment by Stardock2018** [comment]
westcoastxmr.ca

**Comment by pcca-matrix** [comment]
@Stardock2018 

Orphaned block are generally caused by daemon out of sync or too much upload bandwith 

Try with only 1 coin with "blockRefreshInterval": 1500
and limit-rate-up=150 on your daemon to see if that help

**Comment by pcca-matrix** [comment]
@Stardock2018 
looking at your pool , excessive effort to find a block is for sure a daemon problem.

**Comment by Stardock2018** [comment]
Ok I will try that thank you for the help

**Comment by Stardock2018** [comment]
Not getting anymore errors now let's see if I find a block. Ty pcca

**Comment by pcca-matrix** [comment]
It seems that your blocks found are not really orphaned  ! if you look at your pool wallet it must be there.
because when you look at blockexplorer your blocks is valid.
for failed to connect to any of seed peers , trying to fall back seeds i have lots in my log too on small coin like Itns or myztic.
grey list is just a list of offline node , if your ip is listed that's mean  your are not reachable by the network ! Is your p2p daemon port is open ?

I'm pretty sure you have problem with your server and daemons eat all your ressources cpu ram or hdd.

for example my old vps is 4 cores 8gb ram HDD (no SSD) and it's limit with 2 coins  if i put 3 coins , i start same problems as you.

i have upgraded to 16 core 32gb with SSD and no more orphaned block or excessive efforts.

**Comment by Stardock2018** [comment]
Thank you for the help
