### ISSUE TITLE
Empty Blocks

### ISSUE THREAD

**Issue by swa74** [dvandal/cryptonote-nodejs-pool#34]
Hi
I made a pool on the script - http://sup.minexmr24.ru 
I found several blocks, but they are all empty and in http://superior-coin.info:8081/block/9cc98badf40a2688b9b30f9b0592568200e7701c4d15c18c25cb01462d09f432 there are no such blocks

Pool-Found Blocks
Cant get block <5ee6c6bc7ff7c6d6d859f60673ff88e7d620f8928a9f3689db2491d0ef52f07a> for some uknown reason
Cant get block <22d9607c400dbf40961f6de480063451e56be2bb14e4eadb78e510ddadf9896a> for some uknown reason
Cant get block <164e991edc5336ad89f06cc1ea5519dc22f31936fb31170e7ebf57047f56a63e> for some uknown reason
Cant get block <9cc98badf40a2688b9b30f9b0592568200e7701c4d15c18c25cb01462d09f432> for some uknown reason

What could be the problem ?

![default](https://user-images.githubusercontent.com/34404806/39190448-4e0cc86e-47dd-11e8-8361-1e6f6e33006d.JPG)

**Comment by dvandal** [comment]
Since its a low difficulty coin, it could be that some other pool found the block just before yours and that daemon was out of sync with the network or maybe your daemon is on an alternate chain instead of main network.

**Comment by swa74** [comment]
In the demon there are a couple of errors - one concerns DNS, but as I understand it's not scary, but the second batch mode. How to fix it and can it affect?

![1](https://user-images.githubusercontent.com/34404806/39192152-3c9f6790-47e1-11e8-8599-45800bbc7467.JPG)

And how to fix it?

**Comment by swa74** [comment]
and what is the alternative chain, how to fix it?

**Comment by dvandal** [comment]
What is the result of " sync_info" and " alt_chain_info" commands ?

**Comment by swa74** [comment]
![2](https://user-images.githubusercontent.com/34404806/39192799-b0f43408-47e2-11e8-8e5e-e20cbe71ba6f.JPG)
![3](https://user-images.githubusercontent.com/34404806/39192800-b120c874-47e2-11e8-88ec-ace84d3c5985.JPG)

**Comment by swa74** [comment]
current block 197025

**Comment by dvandal** [comment]
I don't see what is wrong, the daemon seem to be in sync with the network but I see that your blocks found are on different hashes than the blocks found on block explorer at same blockchain height.

**Comment by swa74** [comment]
So with what it can be connected?
Especially for the check I bought 8 kh / s and it looks like an empty ...

**Comment by swa74** [comment]
Is there still capacity for testing? Can the truth be worth more to give speed?

**Comment by swa74** [comment]
"coin": "SuperiorCoin",
    "symbol": "SUP",
    "coinUnits": 100000000,
    "coinDifficultyTarget": 120,
    "cnVariant": null, ???
can be replaced by  "cnVariant": 1, ?

**Comment by dvandal** [comment]
If they have the cryptonight v1 (monero v7) fork then yes

**Comment by swa74** [comment]
Delivered, restarted the pool, watched

**Comment by swa74** [comment]
Another block and the same thing

**Comment by swa74** [comment]
and yet, why do the blocks that find my pool go into an alternative chain and are not taken into account?

**Comment by dvandal** [comment]
I can't tell but the issue look specific to Superior coins and I think you will need to check with them.
