### ISSUE TITLE
Payment Problem with NCP

### ISSUE THREAD

**Issue by mobbil** [dvandal/cryptonote-nodejs-pool#340]
Dvandal, i have installed for NewtonCoin but the payments are not processing www.ncppool.com the balance ncp is there but is not transfering the error into the log file is:

in admin show this
Last fail response:
{"code":"ECONNREFUSED","errno":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":22236}

and in log file:
 Error with transfer RPC request to wallet daemon {"code":"ECONNREFUSED","errno":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":22236}

**Comment by avense** [comment]
Friend danval does not have to answer that because it is not a problem in the pool software.

This is you who are throwing your wallet badly as the error demonstrates.

You go to the coin github and check how the wallet is posted.

I could put you here as an example but you do not learn.
greetings

**Comment by avense** [comment]
I'll leave you an example.
./simplewallet --wallet-file=wallet_name --password=pass --rpc-bind-port=22236

**Comment by mobbil** [comment]
dont need to be rude man, that was just one asking for help, since i have follow all the steps and its not working properly the payments, dont need to offend man,  if you can help fine if not why send those kind of message, github is made for this to help errors, i never said was his problem or anyone problem, so please if you can help fine if not dont lose our time thanks

**Comment by mobbil** [comment]
i did that ./simplewallet --wallet-file=wallet_name --password=pass --rpc-bind-port=22236 same problem

**Comment by avense** [comment]
@mobbil  I'm sorry, you're going to ask danval why your pool does not make payments, making you believe that it's the pool software's fault.

Then you ask for help and do not come and ask danval that your pool does not make payments.

For God's sake,,,,,,,,,,

**Comment by mobbil** [comment]
i never said the problem is on his script, rea read my post

**Comment by avense** [comment]
@mobbil  Prove that you're doing it this way because I do not believe it.
It shows photos of the command that you give to launch the wallet and shows your config.

But my help ends here .........
Do you wanna know?

**Comment by mobbil** [comment]
./simplewallet --wallet-file=wallet_name --password=pass --rpc-bind-port=22236 i was doing this also with rpc-bind-ip

**Comment by mobbil** [comment]
$ ./simplewallet --wallet-file=xxxxxxxxxxxx  --password=xxxxxxxxx --rpc-bind-port=22236
2018-Aug-20 22:18:49.963026 INFO    Newton wallet v2.5.0.0 ()
2018-Aug-20 22:18:49.963369 INFO    Loading wallet...
2018-Aug-20 22:18:50.020611 INFO    available balance: 94506.67982487, locked amount: 361493.64665918
2018-Aug-20 22:18:50.020705 INFO    Loaded ok
2018-Aug-20 22:18:50.020762 INFO    Starting wallet rpc server
terminate called after throwing an instance of 'std::runtime_error'
  what():  TcpListener::TcpListener, bind failed, result=98, Address already in use
Aborted

**Comment by mobbil** [comment]
this is your help?

**Comment by mobbil** [comment]
that is an easy why to fix without change the port you should know that no call others idiot in fact i think you are worse than idiot just an stupid programmer or kid trying to be programmer..lol be a man and find a girl to you spend sometime like a man

**Comment by avense** [comment]
It's the solution to your problem.
You have this port in use, or you change the door of the wallet and changes in the config and you reload the pool.

Or you cancel the service that you are using port 22236 for the wallet to work

Paddy next leaves the danval in peace because he has done a work of excellence, and will ask idiotic questions in the right place

**Comment by mobbil** [comment]
i ask question whatever i want to ask

**Comment by avense** [comment]
And I answer what I want to answer

**Comment by mobbil** [comment]
and why are you answering
and lose your time, dont lose my and your time

**Comment by mobbil** [comment]
lol you like to lose your time calling others idiot
go find girls man

**Comment by mobbil** [comment]
this is kind of man without girls..lol

**Comment by avense** [comment]
Wow, then this man who says go to the girls has always helped you.

Stupid idiot, come here to draw compliments to the danval of a stupid mistake of the pool operator.

Anyway .........

![nabo](https://user-images.githubusercontent.com/15719937/44400195-31feb200-a542-11e8-8286-f95dd1949696.jpg)

**Comment by mobbil** [comment]
i didnt draw compliments against Danval, i asked how to fix and help just it, and you start with calling me idiot this is not good to trate people like this, i never called anyone as idiot, everybody has the opportunity to trate and you as a contributor should not tell this to anyone, im not GOD to know everything i like to learn and thanks for your help but i dont accept to be called as idiot because im not and i can prove this to anyone including one i can send you one air ticket to you visit my company and see with who you are calling idiot and check if this is really the correct way to trate people.. 

also when someone is unhappy with his life is normal to call others with bad words like what you did, 
also i didnt fixed changing ports i changed the code with one friend but anyway thanks and God Bless to you .. bye

**Comment by avense** [comment]
New port wallet
Port 20236 (TCP)

I hope no one else will help you.

Besides you idiot, you're a liar.
Have a good time.

**Comment by mobbil** [comment]
lol you are really stupid man, in fact you are not a man, why you are losing your time with one idiot? lol kkkkkkk also why you are protecting dvandal, you looks like be an bootlicker ..lol no ? maybe you are a gay lol lol lol... my dog has more experience and education compared to you .. lol... do you have a house ? car? bike? or you use skate .. or just have a computer ..lol be smart and learn with someone how to be a nice person more one time bye
