### ISSUE TITLE
Not Paying out correctly

### ISSUE THREAD

**Issue by TheBudda** [dvandal/cryptonote-nodejs-pool#341]
Hi,

My Stellite (XTL)  pool is working great. We found our 1st block a couple of days ago. I had an email from a miner saying that my pool is not paying correctly. How can I check if my payments setting are correct? my payments configs are below, are this configs correct? I look forward to your replies

   "payments": {
        "enabled": true,
        "interval": 900,
        "maxAddresses": 50,
        "mixin": 6,
        "priority": 0,
        "transferFee": 100,
        "dynamicTransferFee": true,
        "minerPayFee" : true,
        "minPayment": 1000,
        "maxPayment": null,
        "maxTransactionAmount": 0,
        "denomination": 10000
    },

Kind regards
TheBudda

**Comment by avense** [comment]
Ask his wallet and check what the miner means he was not paid correctly

**Comment by TheBudda** [comment]
@avense  I have done dude below is his email. I do not get where he is getting his figures from! We only found 1 block lol

Hi Budda

Thanks for quick reply i do see what you mean but I did have a figure over 40000 XTL i have mined a few pools to try them out and I usually get around 24000 a day or just less I thought it was strange I was getting double from here I wish I had a picture I would have emailed it to you but never mind just hope it doesn’t happen to anybody else don’t want you getting in trouble.

This was late last night and then I checked this morning to see if it had payed anything out as it says it pays at 30 minute intervals and it showed a pay out estimate very low and I thought where has the 40000 odd gone that’s when I thought I had better get in touch and let you know.

Anyway I will put my miner back on tomorrow and see how its goes if it works out ok I will get my friends to join the same pool as it seems very good apart from this issue. Thanks again and lets see how it goes.
Best regards
*****

**Comment by nathjyo** [comment]
1 block is around 15000 lol, so not sure where he is getting 40k from on estimated payout

I had the same issue ur max payout is 0, I read elsewhere and changed it to 50000000 I also changed my min payout to 500 for the low end miners. Ur max pay out should always be larger than ur min payout. Hope it helps,

On another note that xtl config.json file seems to be broken and needs updating,

**Comment by TheBudda** [comment]
@avense  Yes, where did he get this 40k from lol I have changed the above setting you gave me. Now have to wait for the next block to see what happens! my XTL pool is running sweet!

On another note that xtl config.json file seems to be broken and needs updating??

**Comment by nathjyo** [comment]
I mean it’s broken doesn’t work anymore whit it’s current set up

**Comment by TheBudda** [comment]
@nathjyo  ah ok dude. We found another back and that miner is back so all much be good now! Thank you for your support with my issue dude
