### ISSUE TITLE
GreenWallet support?

### ISSUE THREAD

**Issue by similar75** [dvandal/cryptonote-nodejs-pool#346]
Any chance to make this pool software work with GreenWallet (walletd) instead of simplewallet?
Thank you.

**Comment by similar75** [comment]
OMG, thank you! :)

**Comment by similar75** [comment]
Makes payments for old blocks but cant unlock the new. Pool reports, e.g.:

> 2018-08-31 10:56:31 Error with getblockheaderbyheight RPC request for block e0f7da04f37a8c6abb65ee75d377480caab1cf7ee1e9faf604e1ec46058e267f:1535702100:68652106:64804000:64804000 - {"code":-2,"message":"To big height: 217022, current blockchain height = 217022"}

And wallet:

> 2018-Aug-31 10:56:31.286790 WARNING Requested method not found: balance

Is there other options that i must change?

**Comment by similar75** [comment]
Hm, is "fixBlockHeightRPC":false related to this error for block unlock?
Maybe i should set it to true?

And for wallet warning for method not found i think that the method must be "getBalance" not "getbalance" for GreenWallet..

**Comment by similar75** [comment]
I found that the pool always add +1 to the block height if daemontype is "bytecoin", even if fixBlockHeightRPC in config is false.

See line 67 in lib\blockUnlocker.js:
var blockHeight = (daemonType === "forknote" || daemonType === "bytecoin" || `config.blockUnlocker.fixBlockHeightRPC) ? block.height + 1 : block.height;`

Just removed "+1" from there (ugly fix) and all works like a charm.

**Comment by DarkMoonCBK** [comment]
Front panel can not display blocks and payment information, loading more will lead to collapse.
