### ISSUE TITLE
Ports for front end

### ISSUE THREAD

**Issue by Franzferdinan51** [dvandal/cryptonote-nodejs-pool#347]
Okay so everything is running good except the front end for the life of me when you access it remotely it'll load forever but like only partially you click worker starts and go back to dashboard it loads but everything says "N/A" if anyone could help me fix it that'd be appreciated! It's also worth noting when I put in an address at the worker stats I get connection error

[](https://ibin.co/4E6OAmSjnBbk.jpg)
![](https://ibin.co/4E6OYVdMlE0O.jpg)

**Comment by hypeboard** [comment]
make sure your port for your API is open

**Comment by Franzferdinan51** [comment]
That's 8117 correct?

**Comment by hypeboard** [comment]
Yes. If you have it opened already make sure you've edited config.js to the
correct values as well.

**Comment by Franzferdinan51** [comment]
And those values would be the public IP? Sorry I think you was saying yes to both but I'm trying to be detailed because this issue is aggravating me to death lol

**Comment by unsivilaudio** [comment]
Yes it need to be the public ip, because its js, all api calls are done on the client side.

**Comment by hypeboard** [comment]
Correct

**Comment by Franzferdinan51** [comment]
Awesomeness just got home I'll give that a go in sure that's the issue now that you've mentioned it because it makes sense otherwise it's my ports but I'm pretty sure i would've even be able to access the site at all if that was the case Cheers 🥂🍻
