### ISSUE TITLE
Bittube v2 still can't run

### ISSUE THREAD

**Issue by WaReZoR-UA** [dvandal/cryptonote-nodejs-pool#348]
Help please, already long time I try to start bittube. But all attempts are unsuccessful. I tried to install the node-multi-hashing module from tube develoers, nothing has turned out.

**Comment by funkypenguin** [comment]
I've tried this myself, but don't understand enough to make all the necessary changes to lib/pool.js - anybody got a successful example of this working?

**Comment by gosdor-xda** [comment]
work on https://tube.asiapool.io/

**Comment by funkypenguin** [comment]
@gosdor-xda any idea what code changes were required to make node-multi-hashing work?

**Comment by muscleman** [comment]
multi-hashing package. prolly change to the muscleman github fork of this pool

**Comment by WaReZoR-UA** [comment]
Thanks, is not relevant long ago.
