### ISSUE TITLE
Malformed message - Failed to parse block for LOKI pool

### ISSUE THREAD

**Issue by SixLitr** [dvandal/cryptonote-nodejs-pool#350]
Been running a LOKI pool for some time without issue. Tried moving it to a new server using the latest build and I am getting a malformed message error that it cannot parse the LOKI headers anymore. Seems to be between the pool.js and the node_modules.

`2018-09-04 21:52:53 [pool] (Thread 2) Malformed message from ::ffff:72.194.252.248 generated an exception. Message: {"id":1,"jsonrpc":"2.0","method":"login","params":{"login":"---LOKI ADDRESS---","pass":"6lca02","agent":"XMRig/2.6.1 (Linux x86_64) libuv/1.8.0 gcc/5.4.0"}}`

**Comment by xmpcross** [comment]
I"m having the same problem too, have you found a solution by any chance ?

**Comment by SixLitr** [comment]
Update: for anyone else looking at this issue, that was in fact an issue with earlier versions of 0.3.0. Occasional Odin, v0.2.0 worked fine. I had cloned from the latest release for the new SN code

**Comment by mvilera** [comment]
@SixLitr this means that this repo ain't compatible with lastest lokid release? Magic Mani 1.0.0 RC 3

**Comment by SixLitr** [comment]
@mvilera Indeed, that was the case, but the LOKI dev's were very quick to issue a fix and the current Magic Mani 1.0.0 RC3 is now compatible.

**Comment by WaReZoR-UA** [comment]
stop daemon
stop rpc
update daemon to 1.0.1
dell nod modules in pool dir
git pull
npm update
in pool config change blob type to 5
start daemon, rpc, pool
check

**Comment by mvilera** [comment]
You're right @WaReZoR-UA, thanks for the information!.
