### ISSUE TITLE
Best way to host multiple coin pools per server

### ISSUE THREAD

**Issue by GusWard** [dvandal/cryptonote-nodejs-pool#353]
Hi,

I currently have a single server hosting two coin pools. As it stands there is two separate instances of cryptonote-nodejs-pool, but i can see that the pool is made up of self contained modules, so is there not a more efficient way to do this? 

i.e. could I run a single instance of the API module to serve stats for both coin pools?

Thanks!

**Comment by 20dec** [comment]
copy to other folders, bind to other ports.
For example:
coinA/pool
bind port 1001 1002 1003 1004
coinB/pool
bind port 2001 2002 2003 2004
