### ISSUE TITLE
2018-09-13 05:12:16 [pool] (Thread 8) Invalid address used for login (prefix: N/A): Drupal64

### ISSUE THREAD

**Issue by Franzferdinan51** [dvandal/cryptonote-nodejs-pool#356]
2018-09-13 05:12:16 [pool] (Thread 8) Invalid address used for login (prefix: N/A): Drupal64 streams constant after node init.js

**Comment by avense** [comment]
coin?

**Comment by unsivilaudio** [comment]
I assume its the same issue they posted about earlier, monero.
https://github.com/dvandal/cryptonote-nodejs-pool/issues/352

**Comment by Franzferdinan51** [comment]
yes it is sorry didnt realize i made that twice ill close this one
