### ISSUE TITLE
New bytecoin walletd

### ISSUE THREAD

**Issue by 20dec** [dvandal/cryptonote-nodejs-pool#359]
Hi @dvandal

Can you take a look with new walletd rpc json?
https://github.com/bcndev/bytecoin/wiki/Bytecoin-Wallet-Daemon-JSON-RPC-API

They have a new way to send transaction which cannot use with current pool software for payment.

Thank you
20dec

**Comment by 20dec** [comment]
New bytecoin don't have simplewallet, then I ask. And some coin must use walletd as payment service, and they use old rpc, I still can make it work well. But not this new.

**Comment by avense** [comment]
my pool works great with the new comand....
https://bytecoin.pt

**Comment by 20dec** [comment]
@avense : yes. need change. but i don't know code. can you share me paymentProcess.js and apiInterfaces.js via email: 20dec.20dec@gmail.com

Thank you very much
20dec
