### ISSUE TITLE
Question: Multiple stratum nodes support

### ISSUE THREAD

**Issue by gokul57** [dvandal/cryptonote-nodejs-pool#36]
Hai,
Is it possible to add multiple stratum nodes as leaf nodes to this pool?

**Comment by gokul57** [comment]
@dvandal Your suggestions please :)

**Comment by dvandal** [comment]
This is not planned soon and you can already run the same code base with multiple coins by running each daemons like this:

node init.js --config coin1.json
node init.js --config coin2.json
node init.js --config coin3.json

**Comment by gokul57** [comment]
Thanks for your reply. It would be nice to have support for multiple stratum nodes for a single coin with geo-distributed daemons, as miners to connect to the nearest stratum servers. This is not an important feature. This would be a nice addition to this awesome pool software to set up a global pool. Consider this in future. And once again thanks for your awesome work :)

**Comment by dvandal** [comment]
For geo-distributed daemons, you could do it using a centralized redis database (for miners and pool data) and point the daemons to this redis database.

**Comment by gokul57** [comment]
Thanks, I will try this.
