### ISSUE TITLE
not working front-end.  

### ISSUE THREAD

**Issue by msmmi** [dvandal/cryptonote-nodejs-pool#365]
I am serving the pool from localhost  back end works but not front end is working. I am serving front end from http://127.0.0.1:8080. 

My config.json look like : 
 "poolHost": "127.0.0.1:8080" 

    "api": {
        "enabled": true,
        "hashrateWindow": 600,
        "updateInterval": 5,
        "bindIp": "0.0.0.0",
        "port": 8117,
        "blocks": 30,
        "payments": 30,
        "password": "x"
        
    },

config.js:- 
var api = "0.0.0.0:8117";
var poolHost = "127.0.0.1:8080";

here is the http server error :- 
 "GET /0.0.0.0:8117/stats" Error (404): "Not found"
please help if possible

**Comment by xpctxmin** [comment]
Change var api to 127.0.0.1:877 at config.json

**Comment by msmmi** [comment]
> Change var api to 127.0.0.1:877 at config.json

GET /127.0.0.1:877/stats" Error (404): "Not found"
and tried var api to 127.0.0.1:8117 not working either.

**Comment by msmmi** [comment]
> Change var api to 127.0.0.1:877 at config.json

and i can see the api response on browser : http://0.0.0.0:8117/stats... it shows every thing

**Comment by msmmi** [comment]
I found the problem is occurring because I am using vps. It works locally fine but problem with broadcasting. Still I don't know what to do.
