### ISSUE TITLE
TritaniumCoin Orphan Block

### ISSUE THREAD

**Issue by xenhim** [dvandal/cryptonote-nodejs-pool#367]
`2018-10-05 05:35:36 [unlocker] Error with getblockheaderbyheight RPC request for block d6b70adf083c296086477bc7ecb9cac4157a5689d03bbefb0a0e35ffb488cb61:1538717723:60433745:59513843:643837808 - {"code":-2,"message":"To big height: 30419, current blockchain height = 30418"}`
Help me.
how to fix Orphan ?

**Comment by avense** [comment]
daemontype bytecoin
