### ISSUE TITLE
np update errors

### ISSUE THREAD

**Issue by efraim007** [dvandal/cryptonote-nodejs-pool#369]
Helo,

please help me..
I run teh npm update but i get these erors:
How ti fix it?

cryptonight-hashing.target.mk:113: recipe for target 'Release/obj.target/cryptonight-hashing/multihashing.o' failed
make: *** [Release/obj.target/cryptonight-hashing/multihashing.o] Error 1
make: Leaving directory '/root/pool/node_modules/cryptonight-hashing/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/root/.nvm/v0.10.48/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Linux 4.4.0-133-generic
gyp ERR! command "node" "/root/.nvm/v0.10.48/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /root/pool/node_modules/cryptonight-hashing
gyp ERR! node -v v0.10.48
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok
_
npm ERR! Linux 4.4.0-133-generic
npm ERR! argv "/root/.nvm/v0.10.48/bin/node" "/root/.nvm/v0.10.48/bin/npm" "update"
npm ERR! node v0.10.48
npm ERR! npm  v2.15.1
npm ERR! code ELIFECYCLE

npm ERR! cryptonight-hashing@3.0.5 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the cryptonight-hashing@3.0.5 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the cryptonight-hashing package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs cryptonight-hashing
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls cryptonight-hashing
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/pool/npm-debug.log

**Comment by avense** [comment]
nvm install 4.0
nvm use 4.0

**Comment by djavdat** [comment]
Same problem, what to do in this case? 
Ubuntu 16.04 LTS

**Comment by avense** [comment]
if you use this pool software my solution works.

Do not forget to delete the "node_modules" folder.
Then you use "nvm install 4.0" and then you do "nvm use 4.0" and then "npm update"

if you do, I guarantee you that it works

**Comment by djavdat** [comment]
Again same stuff...

npm ERR! Linux 4.4.0-104-generic
npm ERR! argv "/home/exb/.nvm/v0.10.48/bin/node" "/home/exb/.nvm/v0.10.48/bin/npm" "update"
npm ERR! node v0.10.48
npm ERR! npm  v2.15.1
npm ERR! code ELIFECYCLE

npm ERR! cryptonight-hashing@3.0.5 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the cryptonight-hashing@3.0.5 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the cryptonight-hashing package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs cryptonight-hashing
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls cryptonight-hashing
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/exb/pool/npm-debug.log

**Comment by efraim007** [comment]
Thanks i wil triy this today.

**Comment by efraim007** [comment]
Yes, npm upade OK. Thank.
But After node init.js get same error:
Please help.
root/pool/lib/pool.js:202
        let buffer = new Buffer(result.blocktemplate_blob, 'hex');
            ^^^^^^
SyntaxError: Unexpected identifier
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/root/pool/init.js:29:13)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
2018-10-08 10:28:09 [master] Pool fork 1 died, spawning replacement worker...

/root/pool/node_modules/mailgun.js/lib/client.js:18
class Client {
^^^^^
SyntaxError: Unexpected reserved word
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/root/pool/node_modules/mailgun.js/index.js:5:14)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
2018-10-08 10:28:09 [master] Payment processor died, spawning replacement...

**Comment by djavdat** [comment]
@avense Thank you ! Now npm compilation done without errors. 
But when i start the pool script i faced same problem which already described above by @efraim007: /home/exb/pool/lib/pool.js:202
        let buffer = new Buffer(result.blocktemplate_blob, 'hex');
            ^^^^^^
SyntaxError: Unexpected identifier
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/exb/pool/init.js:29:13)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)

**Comment by djavdat** [comment]
So no any suggestions?

**Comment by avense** [comment]
daemon not syncronized

**Comment by djavdat** [comment]
@avense No, daemon completely synchronized.
everything is ok. Only i have this error. I also reinstall everything. Nothing was changed, this error comes and comes again.  Please help to find the reason - why this pool doesn't working :(

**Comment by efraim007** [comment]
My daemon runing without error. Wallet runing. I create the pool same server (screen). But I get this error....

**Comment by shadowq7** [comment]
@avense 

I ' ve done npm update without any error but when i write "node init.js"

https://github.com/dvandal/cryptonote-nodejs-pool/issues/386

this error happened ? Like aboe @efraim007 , @djavdat 

Is there any solution ?
