### ISSUE TITLE
Hardfork support

### ISSUE THREAD

**Issue by vvzar** [dvandal/cryptonote-nodejs-pool#377]
Will pool supports next monero hardfork (october 18)?

**Comment by mdm001** [comment]
I'm interested in the answer to this as well.  I upgraded my daemon / wallet and now it doesn't seem to work.

**Comment by cryptosk** [comment]
We need V8 support @dvandal

**Comment by mdm001** [comment]
Or, please, an answer of yes or no.  If yes, then a completion time would also be helpful.  Thank you.

**Comment by nssy** [comment]
Its pretty easy to run v8/v9 hard fork version. Just change in config.json
"cnVariant": 1, to
"cnVariant": 2, 
After the fork.
But you also need to upgrade the node-cryptonight-hashing by doing `npm upgrade`

**Comment by mdm001** [comment]
Thank you nssy.  After changing to 8, it did start working properly with your instructions above.  I do get these occasional "ghost" warnings about being banned and then connected again.  I don't know if this is happening to anyone else.  Doesn't seem to be impacting anything else though.  Now, if I can only get my miners to update and stop filling up my logs!

**Comment by mdm001** [comment]
> 
> 
> Thank you nssy. After changing to 8, it did start working properly with your instructions above. I do get these occasional "ghost" warnings about being banned and then connected again. I don't know if this is happening to anyone else. Doesn't seem to be impacting anything else though. Now, if I can only get my miners to update and stop filling up my logs!

After a few days, these did stop.  I think maybe they were caught in the queue or something.

**Comment by SixLitr** [comment]
> The configurations that show are outdated and / or for example purposes only. One should follow the miner specific instructions for the particular version being used in order to configure properly. The pool does work for me on v8 of monero. But, good point, it could confuse some people. I wouldn't consider this to be an issue as the pool works. It's just something to clean up on the web front end.

Are you saying that essentially the pool works and miners can mine using the v8 algo on their miners, the page just reflects the wrong algo?  I will be trying a miner out now to see. If its just a cosmetic change I can fix that, no big deal.

**Comment by mdm001** [comment]
Yes, exactly.  The config examples on the "getting started" page haven't been exact since at least May when I started using this code.  I have a few miners running v8 code and have no issues. It's an easy cosmetic fix.  I just put a notice on mine that it's for example purposes only and to check miner software for exact configuration information.

**Comment by SixLitr** [comment]
For anyone else looking, I can *mostly* confirm that the cnVariant of 8 works (just waiting for the first block)...all shares are accepted and everything seems normal, except for the pool showing the algorithm as Cryptonight (Original)

**Comment by pcca-matrix** [comment]
Change in pages/getting_started.html

        else {
            if (cnVariant === 1) {
                algorithm = 'Cryptonight (Monero v7)';
                xmrstakAlgo = 'cryptonight_v7';
            } else if (cnVariant === 3) {
                algorithm = 'Cryptonight (Stellite v7)';
                xmrstakAlgo = 'cryptonight_v7_stellite';
	    } else if (cnVariant === 4) {
                algorithm = 'Cryptonight Fast (Masari)';
                xmrstakAlgo = 'cryptonight_masari';
		} else if (cnVariant === 8) {
                algorithm = 'Cryptonight Variant 2 (Cryptonight v8)';
                xmrstakAlgo = 'cryptonight_v8';
            } else {
                algorithm = 'Cryptonight (Original)';
                xmrstakAlgo = 'cryptonight';
            }
        }

**Comment by mdm001** [comment]
Thank you pcca-matrix!  Works perfectly!
