### ISSUE TITLE
low difficulty share

### ISSUE THREAD

**Issue by nutsplus** [dvandal/cryptonote-nodejs-pool#38]
I instal your pool. Download sumokoin.json and run pool.

I use srb miner 1.4.3 - it work good!
But,
If I use "cryptonight_type" : "normal" (old cryptonight) -  Pool accepted result
If I use "cryptonight_type" : "heavy" -  Pool rejected result 0x000100B3 (low difficulty share)

What's problem?
Thx!

**Comment by Jockeyvb** [comment]
same issue

**Comment by nutsplus** [comment]
Jockeyvb, XTL use cryptonight v7. Just edit config.json 
/* Set Cryptonight variant. Set 0 for original Cryptonight algorithm and 1 for Cryptonight v1 / Monero v7 algorithm. If empty will use automatic detection. Set -1 to disable. */
"cnVariant": null,

Set "cnVariant": 1,

**Comment by nutsplus** [comment]
But SUMO use cryptonight heavy! what variant I need set for cryptonight heavy?

**Comment by dvandal** [comment]
I added support for Cryptonight Heavy (Sumokoin fork) into lastest code. To make it works you need to set "cnAlgorithm" to "cryptonight_heavy" and "cnVariant" to "null".

**Comment by nutsplus** [comment]
Where I can change "cnAlgorithm" to "cryptonight_heavy"??
And what about "Could not start server listening on port 9999 (SSL): SSL certificate file not found"?
Very big thx!!

**Comment by nutsplus** [comment]
https://drive.google.com/open?id=1htBN1dRAkP1IPHhdY4LcDYgRq1S6Cbe6
https://drive.google.com/open?id=1PmgmJTUHv7NvCFjgt5_dk6Ga5dD4eGVM
Do you have ideas?

**Comment by dvandal** [comment]
Are you using the lastest code?
git pull

**Comment by dvandal** [comment]
Also you will need to reinstall npm packages since I now have hashing modules for multiple cryptonight algorithms
