### ISSUE TITLE
Error: Failed to parse block

### ISSUE THREAD

**Issue by madman-genchie** [dvandal/cryptonote-nodejs-pool#380]
i have opted to use this pool software for my dero pool but as soon as i try to connect the miner it throws out the Error: Failed to parse block.......error     
i have tried deleting the node modules and npm update but still the same error, ive tried downgrading the npm to v4 from v8 and again still not working.....

**Comment by wahaobi** [comment]
I am also the problem, how can I solve it?

**Comment by wahaobi** [comment]
@dvandal

**Comment by wahaobi** [comment]
Are you doing it?

> i have opted to use this pool software for my dero pool but as soon as i try to connect the miner it throws out the Error: Failed to parse block.......error
> i have tried deleting the node modules and npm update but still the same error, ive tried downgrading the npm to v4 from v8 and again still not working.....

**Comment by madman-genchie** [comment]
? Am I doing what I’m not the developer lol

Sent from my iPhone

On 19 Oct 2018, at 11:57, wahaobi <notifications@github.com<mailto:notifications@github.com>> wrote:


Are you doing it?

i have opted to use this pool software for my dero pool but as soon as i try to connect the miner it throws out the Error: Failed to parse block.......error
i have tried deleting the node modules and npm update but still the same error, ive tried downgrading the npm to v4 from v8 and again still not working.....

**Comment by wahaobi** [comment]
Is your swimming pool done?

**Comment by papka039** [comment]
I have the same problem on any coin.
