### ISSUE TITLE
let buffer = new Buffer(result.blocktemplate_blob, 'hex');

### ISSUE THREAD

**Issue by shadowq7** [dvandal/cryptonote-nodejs-pool#386]
I am trying to open MASARI pool. But i got this error

/root/pool/lib/pool.js:202
        let buffer = new Buffer(result.blocktemplate_blob, 'hex');
        ^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:413:25)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/root/pool/init.js:29:13)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
2018-10-31 03:31:06 [master] Pool fork 2 died, spawning replacement worker...

**Comment by shadowq7** [comment]
config.json

{
    "poolHost": "178.62.250.244",

    "coin": "masari",
    "symbol": "MSR",
    "coinUnits": 1000000000000,
    "coinDecimalPlaces": 4,
    "coinDifficultyTarget": 120,

    "daemonType": "default",
    "cnAlgorithm": "cryptonight",
    "cnVariant": 4,
    "cnBlobType": 3,

    "logging": {
        "files": {
            "level": "info",
            "directory": "logs",
            "flushInterval": 5
        },
        "console": {
            "level": "info",
            "colors": true
        }
    },

    "poolServer": {
        "enabled": true,
        "clusterForks": "auto",
        "poolAddress": "5mAUHndjw4PbVgAMziJ57iSB3GMHaY8qxGJAVEgVZNarXNYyt9W9btg7v2yUbrK43vCaSrUK9VyjyUaH1Pe1c4oTDvR3Zwr",
        "intAddressPrefix": null,
        "blockRefreshInterval": 1000,
        "minerTimeout": 900,
        "sslCert": "./cert.pem",
        "sslKey": "./privkey.pem",
        "sslCA": "./chain.pem",
        "ports": [
            {
                "port": 3333,
                "difficulty": 5000,
                "desc": "Low end hardware"
            },
            {
                "port": 4444,
                "difficulty": 15000,
                "desc": "Mid range hardware"
            },
            {
                "port": 5555,
                "difficulty": 25000,
                "desc": "High end hardware"
            },
            {
                "port": 7777,
                "difficulty": 500000,
                "desc": "Cloud-mining / NiceHash"
            },
            {
                "port": 8888,
                "difficulty": 25000,
                "desc": "Hidden port",
                "hidden": true
            },
            {
                "port": 9999,
                "difficulty": 20000,
                "desc": "SSL connection",
                "ssl": true
            }
        ],
        "varDiff": {
            "minDiff": 100,
            "maxDiff": 100000000,
            "targetTime": 120,
            "retargetTime": 30,
            "variancePercent": 30,
            "maxJump": 100
        },
        "paymentId": {
            "addressSeparator": "."
        },
        "fixedDiff": {
            "enabled": true,
            "addressSeparator": "+"
        },
        "shareTrust": {
            "enabled": true,
            "min": 10,
            "stepDown": 3,
            "threshold": 10,
            "penalty": 30
        },
        "banning": {
            "enabled": true,
            "time": 600,
            "invalidPercent": 25,
            "checkThreshold": 30
        },
        "slushMining": {
            "enabled": false,
            "weight": 300,
            "blockTime": 60,
            "lastBlockCheckRate": 1
         }
    },

    "payments": {
        "enabled": true,
        "interval": 1800,
        "maxAddresses": 50,
        "mixin": 5,
        "priority": 0,
        "transferFee": 5000000000,
        "dynamicTransferFee": true,
        "minerPayFee" : true,
        "minPayment": 1000000000000,
        "maxPayment": null,
        "maxTransactionAmount": 0,
        "denomination": 100000000000
    },

    "blockUnlocker": {
        "enabled": true,
        "interval": 30,
        "depth": 60,
        "poolFee": 0.8,
        "devDonation": 0.2,
        "networkFee": 0.0
    },

    "api": {
        "enabled": true,
        "hashrateWindow": 900,
        "updateInterval": 5,
        "bindIp": "0.0.0.0",
        "port": 8117,
        "blocks": 30,
        "payments": 30,
        "password": "test123",
        "ssl": false,
        "sslPort": 8119,
        "sslCert": "./cert.pem",
        "sslKey": "./privkey.pem",
        "sslCA": "./chain.pem",
        "trustProxyIP": true
    },

    "daemon": {
        "host": "127.0.0.1",
        "port": 38081
    },

    "wallet": {
        "host": "127.0.0.1",
        "port": 38083
    },

    "redis": {
        "host": "127.0.0.1",
        "port": 6379,
        "auth": null,
        "db": 0,
	"cleanupInterval": 15
    },

    "notifications": {
        "emailTemplate": "email_templates/default.txt",
        "emailSubject": {
            "emailAdded": "Your email was registered",
            "workerConnected": "Worker %WORKER_NAME% connected",
            "workerTimeout": "Worker %WORKER_NAME% stopped hashing",
            "workerBanned": "Worker %WORKER_NAME% banned",
            "blockFound": "Block %HEIGHT% found !",
            "blockUnlocked": "Block %HEIGHT% unlocked !",
            "blockOrphaned": "Block %HEIGHT% orphaned !",
            "payment": "We sent you a payment !"
        },
        "emailMessage": {
            "emailAdded": "Your email has been registered to receive pool notifications.",
            "workerConnected": "Your worker %WORKER_NAME% for address %MINER% is now connected from ip %IP%.",
            "workerTimeout": "Your worker %WORKER_NAME% for address %MINER% has stopped submitting hashes on %LAST_HASH%.",
            "workerBanned": "Your worker %WORKER_NAME% for address %MINER% has been banned.",
            "blockFound": "Block found at height %HEIGHT% by miner %MINER% on %TIME%. Waiting maturity.",
            "blockUnlocked": "Block mined at height %HEIGHT% with %REWARD% and %EFFORT% effort on %TIME%.",
            "blockOrphaned": "Block orphaned at height %HEIGHT% :(",
            "payment": "A payment of %AMOUNT% has been sent to %ADDRESS% wallet."
        },
        "telegramMessage": {
            "workerConnected": "Your worker _%WORKER_NAME%_ for address _%MINER%_ is now connected from ip _%IP%_.",
            "workerTimeout": "Your worker _%WORKER_NAME%_ for address _%MINER%_ has stopped submitting hashes on _%LAST_HASH%_.",
            "workerBanned": "Your worker _%WORKER_NAME%_ for address _%MINER%_ has been banned.",
            "blockFound": "*Block found at height* _%HEIGHT%_ *by miner* _%MINER%_*! Waiting maturity.*",
            "blockUnlocked": "*Block mined at height* _%HEIGHT%_ *with* _%REWARD%_ *and* _%EFFORT%_ *effort on* _%TIME%_*.*",
            "blockOrphaned": "*Block orphaned at height* _%HEIGHT%_ *:(*",
            "payment": "A payment of _%AMOUNT%_ has been sent."
        }
    },

    "email": {
        "enabled": false,
        "fromAddress": "your@email.com",
        "transport": "sendmail",
        "sendmail": {
            "path": "/usr/sbin/sendmail"
        },
        "smtp": {
            "host": "smtp.example.com",
            "port": 587,
            "secure": false,
            "auth": {
                "user": "username",
                "pass": "password"
            },
            "tls": {
                "rejectUnauthorized": false
            }
        },
        "mailgun": {
            "key": "your-private-key",
            "domain": "mg.yourdomain"
        }
    },

    "telegram": {
        "enabled": false,
        "botName": "",
        "token": "",
        "channel": "",
        "channelStats": {
            "enabled": false,
            "interval": 30
        },
        "botCommands": {
            "stats": "/stats",
            "report": "/report",
            "notify": "/notify",
            "blocks": "/blocks"
        }
    },
    
    "monitoring": {
        "daemon": {
            "checkInterval": 60,
            "rpcMethod": "getblockcount"
        },
        "wallet": {
            "checkInterval": 60,
            "rpcMethod": "getbalance"
        }
    },

    "prices": {
        "source": "tradeogre",
        "currency": "USD"
    },
    
    "charts": {
        "pool": {
            "hashrate": {
                "enabled": true,
                "updateInterval": 60,
                "stepInterval": 1800,
                "maximumPeriod": 86400
            },
            "miners": {
                "enabled": true,
                "updateInterval": 60,
                "stepInterval": 1800,
                "maximumPeriod": 86400
	    },
            "workers": {
                "enabled": true,
                "updateInterval": 60,
                "stepInterval": 1800,
                "maximumPeriod": 86400
            },
            "difficulty": {
                "enabled": true,
                "updateInterval": 1800,
                "stepInterval": 10800,
                "maximumPeriod": 604800
            },
            "price": {
                "enabled": true,
                "updateInterval": 1800,
                "stepInterval": 10800,
                "maximumPeriod": 604800
            },
            "profit": {
                "enabled": true,
                "updateInterval": 1800,
                "stepInterval": 10800,
                "maximumPeriod": 604800
            }
        },
        "user": {
            "hashrate": {
                "enabled": true,
                "updateInterval": 180,
                "stepInterval": 1800,
                "maximumPeriod": 86400
            },
            "worker_hashrate": {
                "enabled": true,
                "updateInterval": 60,
                "stepInterval": 60,
                "maximumPeriod": 86400
            },
            "payments": {
                "enabled": true
            }
        },
        "blocks": {
            "enabled": true,
            "days": 30
        }
    }
}

**Comment by shadowq7** [comment]
package.json


{
    "name": "cryptonote-nodejs-pool",
    "version": "1.3.5",
    "license": "GPL-2.0",
    "author": "Daniel Vandal",
    "repository": {
        "type": "git",
        "url": "https://github.com/dvandal/cryptonote-nodejs-pool.git"
    },
    "dependencies": {
        "async": "1",
        "base58-native": "*",
        "bignum": "*",
        "cli-color": "*",
        "cryptonote-util": "git://github.com/masari-project/node-cryptonote-util#msr",
        "cryptoforknote-util": "git://github.com/MoneroOcean/node-cryptoforknote-util.git",
        "cryptonight-hashing": "git://github.com/MoneroOcean/node-cryptonight-hashing.git",
        "dateformat": "*",
        "mailgun.js": "*",
        "node-telegram-bot-api": "*",
        "nodemailer": "2.7.2",
        "nodemailer-sendmail-transport": "*",
        "redis": "*",
        "socket.io": "^2.1.1",
        "time-ago": "*"
    },
    "engines": {
        "node": ">=4.0"
    }
}

**Comment by caokun320** [comment]
i have the same error ,wait someone help

**Comment by shadowq7** [comment]
@caokun320  are you trying for MASARI ?

**Comment by caokun320** [comment]
> @ caokun320 你在试用MASARI吗？

i try ccx

**Comment by shadowq7** [comment]
@caokun320  do you use nvm v4.0.0 ?

**Comment by mannie65** [comment]
Did anyone resolve this - I am having this issue now after an npm update which I did to update my Graft pool for CNv2 ?

**Comment by mannie65** [comment]
FYI - resolved for me by updating to node 8.12.0 and npm 6.4.1 - downloading a clean copy and then doing an npm update

**Comment by shadowq7** [comment]
I change it v8.0.0 nvm and everything is well now

**Comment by caokun320** [comment]
emmm，i use v8.0.0 it work
