### ISSUE TITLE
Conceal Config.js

### ISSUE THREAD

**Issue by shadowq7** [dvandal/cryptonote-nodejs-pool#387]
Anyone else have conceal (ccx) config.js ?

**Comment by muscleman** [comment]
easy way to work out a suitable config is to visit another pool. F12 and find the stats call in the network tab of chrome. copy the url and paste into the browser.
this usually tells you alot of the settings you pool will require. 
failing that, look in the src directory for the coin for a file called cryptonight config.h scroll around in there and find some information.
