### ISSUE TITLE
Cryptonight V8 Setting (Caliber)

### ISSUE THREAD

**Issue by shadowq7** [dvandal/cryptonote-nodejs-pool#389]
Anyone Knows 

    "cnAlgorithm": "?????",
    "cnVariant": ???? ,
    "cnBlobType": ????,

settings

**Comment by prox443** [comment]
Try,

"cnAlgorithm": "cryptonight",
"cnVariant": 8 ,
"cnBlobType": 0,

**Comment by kikophenix** [comment]
variant 2

**Comment by Swericor** [comment]
> Try,
> 
> "cnAlgorithm": "cryptonight",
> "cnVariant": 8 ,
> "cnBlobType": 0,

This works.
