### ISSUE TITLE
Wallet {"bytesParsed":0,"code":"HPE_INVALID_CONSTANT"}

### ISSUE THREAD

**Issue by oxzhor** [dvandal/cryptonote-nodejs-pool#395]
Hi,

In /admin.html#monitoring see the follow error:

![wallet](https://user-images.githubusercontent.com/19476081/48285388-ba666200-e462-11e8-8fc0-bb67b39c993f.png)

root@xcash:~# netstat -tlunp
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 0.0.0.0:18280           0.0.0.0:*               LISTEN      2822/xcashd
tcp        0      0 127.0.0.1:18281         0.0.0.0:*               LISTEN      2822/xcashd
tcp        0      0 127.0.0.1:18282         0.0.0.0:*               LISTEN      2822/xcashd
tcp        0      0 127.0.0.1:18283         0.0.0.0:*               LISTEN      3046/xcash-wallet-r
tcp        0      0 127.0.0.1:6379          0.0.0.0:*               LISTEN      647/redis-server 12
tcp        0      0 0.0.0.0:10000           0.0.0.0:*               LISTEN      10470/perl
tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN      666/apache2
tcp        0      0 0.0.0.0:8117    0.0.0.0:*               LISTEN      2200/node
tcp6       0      0 :::4444                 :::*                    LISTEN      2200/node
tcp6       0      0 :::7777                 :::*                    LISTEN      2200/node
tcp6       0      0 :::3333                 :::*                    LISTEN      2200/node
tcp6       0      0 :::9999                 :::*                    LISTEN      2200/node
tcp6       0      0 :::5555                 :::*                    LISTEN      2200/node
tcp6       0      0 :::8888                 :::*                    LISTEN      2200/node

How i can debug this error and solve it?
If more info needed please let me know.

**Comment by paulbrasted** [comment]
Not a solution for you..  but I raised similar error 388 a couple of days ago

I am running aeond 11181 and aeond-wallet-rpc 11182 and kept getting this error from the payments module 
.
All ports are open

I am trying to solo mine using xmr-stak 

Do you know any method to test this software before running it for days waiting for a block which will then fail to pay ????

**Comment by oxzhor** [comment]
Which startup line do you use for aeond and aeond-wallet-rpc?

**Comment by paulbrasted** [comment]
hi, im doubling up on my other post here ..this is what I am using

Thanks I will try this now. These are my two commands for launching daemon and wallet
.\aeond --data-dir=H:\aeon --rpc-bind-ip 0.0.0.0 --confirm-external-bind
and this with your suggestion
.\aeon-wallet-rpc --daemon-address localhost:11181 --rpc-bind-ip 0.0.0.0 --rpc-bind-port 11182 --confirm-external-bind --wallet-file my wallet name --prompt-for-password --disable-rpc-login --trusted-daemon --log-file rpc.log --log-level 4

**Comment by oxzhor** [comment]
problem solved i change the port --rpc-bind-port 18285
