### ISSUE TITLE
Want a Donation ...Then help me rely on this software working!!!

### ISSUE THREAD

**Issue by paulbrasted** [dvandal/cryptonote-nodejs-pool#396]

**Comment by hypeboard** [comment]
what are you having trouble with?

**Comment by leisegang** [comment]
Really help ful desxription on the issue. Gives us nothing to work with except for that the poster dont understand anything

**Comment by paulbrasted** [comment]
Yes sorry , fair enough .  The issue I posted was number 388. 
bytesParsed":0,"code":"HPE_INVALID_CONSTANT" Revist ? 

I presume you will read so I will not  repost.

Further to this I have now downloaded redis-commander.
looking under the status key I am continually getting this message. 

Field | Value
-- | --
lastCheck | 1542012601
lastStatus | fail
lastResponse | {"bytesParsed":0,"code":"HPE_INVALID_CONSTANT"}
lastFail | 1542012601
lastFailResponse | {"bytesParsed":0,"code":"HPE_INVALID_CONSTANT"}

I have again tested all my ports using Test-NetConnection 127.00.1:11181 for aeon daemon  and 127.0.0.1:11182 for aeon wallet-rpc. I have synced the blockchain and have a local wallet and that all is working . Aeond has inbound and outbound connections on 11180



I

**Comment by paulbrasted** [comment]
Thanks I will try this now. These are my two commands for launching daemon and wallet 
.\aeond --data-dir=H:\aeon --rpc-bind-ip 0.0.0.0  --confirm-external-bind 

and this with your suggestion 

.\aeon-wallet-rpc --daemon-address localhost:11181 --rpc-bind-ip 0.0.0.0 --rpc-bind-port 11182 --confirm-external-bind --wallet-file <my wallet name> --prompt-for-password  --disable-rpc-login --trusted-daemon --log-file rpc.log --log-level 4

**Comment by paulbrasted** [comment]
It did not make any difference adding disable-rpc-login  I started using nodejs init.js and left it running and still the same issue when looking at redis-commander aeon/status/wallet .. I waited till the lastcheck value changed.

Field | Value
-- | --
lastCheck | 1542052814
lastStatus | fail
lastResponse | {"bytesParsed":0,"code":"HPE_INVALID_CONSTANT"}
lastFail | 1542052814
lastFailResponse | {"bytesParsed":0,"code":"HPE_INVALID_CONSTANT"}

**Comment by paulbrasted** [comment]
I have tried rebuilding aeon under ubuntu at work to day and still same same problem …

I have also realized that my nodejs is the latest 11.x but your docs on installing cryptonote-nodejs-pool say use 8.xx. I am going to downgrade and  see if this makes a difference

**Comment by paulbrasted** [comment]
Still the same

Any more suggestion anybody ..

**Comment by nox956** [comment]
Why would you bind your ip to 0.0.0.0? Rpc server should only be accessed by localhost, change it to `--rpc-bind-ip 127.0.0.1`  and make sure to change your config file of the pool:

```
    "wallet": {
        "host": "127.0.0.1",
        "port": 11182
    },
```

**Comment by paulbrasted** [comment]
Well I changed to --rpc-bind-ip  to 127.0.0.1 and I got this error when starting the wallet-rpc

2018-11-13 23:01:37.725 18288   FATAL   net     contrib/epee/include/net/abstract_tcp_server2.inl:856   Error starting server: bind: An attempt was made to access a socket in a way forbidden by its access permissions

This happened with or without  firewall on .. very odd

So I changed it to be --rpc-bind-ip 192.168.0.19 which is the actual IP of  my machine on my local network  of   and changed the address in config.json to be the same and low and behold

redis-commander for aeon/sattus/wallet gave 

Field | Value
-- | --
lastResponse | {"balance":23174000000000,"multisig_import_needed":false,"per_subaddress":[{"address":"Wmswr7wFCQh4xsf7tbReDCUgvAgQR9aCbTvE5fwwoFx1KCmjA9nAwXVXoCyjUxyjKuTefTLQZhizuUJjoT86DTSy1AWLYHvXv","address_index":0,"balance":23174000000000,"label":"Primary account","num_unspent_outputs":34,"unlocked_balance":23174000000000}],"unlocked_balance":23174000000000}
lastCheck | 1542149544
lastStatus | ok


Success !!!!  ..Thank you very much....Looks Like the original reason specified for this error was correct ..what a journey..

I still do not understand why have 127.0.0.1:11182 in config json and --rpc-bind-ip 0.0.0.0 in would not work though.



 
 
.

**Comment by paulbrasted** [comment]
Ok give me an address nox956  ….when I mine my first aeon block

**Comment by nox956** [comment]
Good for you!
`WzWP347dSczJVmPpw65AsAGi5WhT85z5n66D8vcT3RcxRBBj4tFiDcd2CVFcQ1bBpjNQD5Z5kbXrLjVidvoKFaFK6uhFmBQJy6d1QFdNqwM6`
