### ISSUE TITLE
7fb94e7fc700 ERROR default src/rpc/zmq_server.cpp:85 ZMQ error: Operation cannot be accomplished in current state

### ISSUE THREAD

**Issue by oxzhor** [dvandal/cryptonote-nodejs-pool#397]
Hi,

I have an error with xcash-wallet-rpc when i want to connect to xcashd.

Start xcashd
`./xcashd`

Start xcash-wallet-rpc
`./xcash-wallet-rpc --rpc-bind-port 18283 --wallet-file xcashw --password test1337 --daemon-port 18282`

At startup the xcash-wallet-rpc i get the follow error into xcashd:
![error](https://user-images.githubusercontent.com/19476081/48352246-92f2dd80-e68c-11e8-8297-ffbf277fdbec.png)

root@xcash:~# netstat -tlunp
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address Foreign Address State PID/Program name
tcp 0 0 0.0.0.0:18280 0.0.0.0:* LISTEN 2822/xcashd
tcp 0 0 127.0.0.1:18281 0.0.0.0:* LISTEN 2822/xcashd
tcp 0 0 127.0.0.1:18282 0.0.0.0:* LISTEN 2822/xcashd
tcp 0 0 127.0.0.1:18283 0.0.0.0:* LISTEN 3046/xcash-wallet-r
tcp 0 0 127.0.0.1:6379 0.0.0.0:* LISTEN 647/redis-server 12
tcp 0 0 0.0.0.0:10000 0.0.0.0:* LISTEN 10470/perl
tcp 0 0 0.0.0.0:80 0.0.0.0:* LISTEN 666/apache2
tcp 0 0 0.0.0.0:8117 0.0.0.0:* LISTEN 2200/node
tcp6 0 0 :::4444 :::* LISTEN 2200/node
tcp6 0 0 :::7777 :::* LISTEN 2200/node
tcp6 0 0 :::3333 :::* LISTEN 2200/node
tcp6 0 0 :::9999 :::* LISTEN 2200/node
tcp6 0 0 :::5555 :::* LISTEN 2200/node
tcp6 0 0 :::8888 :::* LISTEN 2200/node

**Comment by OptimusBlue** [comment]
Have you tried rpc with "--disable-rpc-login"?

./xcash-wallet-rpc --rpc-bind-port 18283 --wallet-file xcashw --password test1337 --daemon-port 18282 --disable-rpc-login

**Comment by oxzhor** [comment]
OK i setup an lethean pool without any issue. I think xcash is not supported into this software yet and thats why i cannot connect rpc.

**Comment by oxzhor** [comment]
Problem solved i change the port to --rpc-bind-port 18285
