### ISSUE TITLE
CPU Rejected share: invalid result GPU no problem 

### ISSUE THREAD

**Issue by oxzhor** [dvandal/cryptonote-nodejs-pool#399]
Hi,

I'm running an lethean pool and cannot connect with CPU's at the pool. With GPU's there are no problem.

`rejected (202/30) diff 100 "Rejected share: invalid result `

and then the ip get  banned.

What do i need to change into the config to give CPU's access?

**Comment by AluCoin** [comment]
yes nice question i have same issue

**Comment by muscleman** [comment]
client side algo is different for cpu and gpu?
