### ISSUE TITLE
No workers' balances reached the minimum payment threshold

### ISSUE THREAD

**Issue by WaReZoR-UA** [dvandal/cryptonote-nodejs-pool#400]
Hi all! The pool finds blocks, charges of balance take place correctly, but payments are not made. Min payout is 1 coin, 15min. period. No errors in logs.

![image](https://user-images.githubusercontent.com/38248645/48958150-01298100-ef66-11e8-9692-f062c92ff815.png)

![image](https://user-images.githubusercontent.com/38248645/48958170-143c5100-ef66-11e8-849c-a993eb407696.png)

![image](https://user-images.githubusercontent.com/38248645/48958234-6b422600-ef66-11e8-9006-e291288c97e2.png)

**Comment by muscleman** [comment]
what coin? what mixing. what do your payment logs say in admin?

**Comment by WaReZoR-UA** [comment]
> what coin? what mixing. what do your payment logs say in admin?

BLOC, mixin 0, after 24hr log startin says

![image](https://user-images.githubusercontent.com/38248645/48966199-33be9280-efd5-11e8-87f3-e52a482a50ee.png)

**Comment by WaReZoR-UA** [comment]
When I select "daemonType": "bytecoin", error change to 2018-11-24 10:31:10 [payments] Error with sendTransaction RPC request to wallet daemon {"code":-32601,"message":"Method not found"}

**Comment by WaReZoR-UA** [comment]
I found a problem. there was an introduced error in config file
