### ISSUE TITLE
Is BITTUBE last version supported ?

### ISSUE THREAD

**Issue by victoryvt** [dvandal/cryptonote-nodejs-pool#402]
I don't see any file named as "tube.json" or "bittube.json" or "ipbc.json" in /config_examples.
But in the List of Cryptonote coins
https://github.com/dvandal/cryptonote-nodejs-pool/wiki/Cryptonote-Coins
I see that IPBC is supported.
May I ask for viral data for exact BITTUBE config.json file ?
Regards,
Victor.

**Comment by muscleman** [comment]
muscleman pool has 1 of 2 custom hashing packages available. bittube needs multihashing.
