### ISSUE TITLE
Please add it !!! XFH FreeHaven protocol !!!

### ISSUE THREAD

**Issue by lamgztey** [dvandal/cryptonote-nodejs-pool#407]
[Website]
http://freehavenprotocol.space/

[ANN]
https://bitcointalk.org/index.php?topic=5071178

[Project's Github]
https://github.com/freehavenprotocol

[CLI Wallet]
https://github.com/freehavenprotocol/freehaven/releases/download/1.0.0/freehaven_1.0.0_win_cli.zip

[GUI Wallet]
https://github.com/freehavenprotocol/freehaven-gui
https://github.com/freehavenprotocol/freehavenprotocol/releases/download/v0.9/freehaven_win_gui.zip

[Paper Wallet]
https://github.com/freehavenprotocol/freehavenprotocol/blob/master/Freehavenaddr.html

[Miners]
https://github.com/killmak/xmr-stak/releases/latest <- Working AMD / Nvidia / CPU Miner
https://github.com/Bendr0id/xmrigCC/releases/latest
https://github.com/Bendr0id/xmrigCC-amd/releases/tag/1.8.4
http://www.gandalph3000.com/ Cast XMR 1.6.5

[Remote Nodes]
58.185.155.109:18850 (Special thanks to Reeyon)
Node.bitkitten.xyz:18850 (Special thanks to Rixxter)
node.pocketwhale.info:18850 (Special thanks to Leafy)

[Block Explorer]
https://freehaven.coinscope.cc/

**Comment by muscleman** [comment]
muscleman pool on github has option to use one of two hashing packages
