### ISSUE TITLE
Pool does not showing stats on dashboard :(

### ISSUE THREAD

**Issue by bl00dy** [dvandal/cryptonote-nodejs-pool#409]
Hello everyone. I have problem with my pool. On dashboard stats is (N/A) and when i try to get worker statistics, i get (Connection error). Pool is runing and is working getting share's reciving blocks... What can i do to fix that ? (Sorry for bad English)

**Comment by hypeboard** [comment]
make sure the port for API is open

**Comment by bl00dy** [comment]
8117 is open on my router and i checked on https://www.yougetsignal.com/tools/open-ports/ and its working

**Comment by bl00dy** [comment]
to api to point pool ?

**Comment by hypeboard** [comment]
var api =

**Comment by bl00dy** [comment]
"http://127.0.0.1:8117";

**Comment by hypeboard** [comment]
use the external IP or TLD instead of localhost

**Comment by bl00dy** [comment]
Its working now i use external IP. Thank you so much :)
