### ISSUE TITLE
Cryptonight V8 pool settings "cnVariant" ?

### ISSUE THREAD

**Issue by bl00dy** [dvandal/cryptonote-nodejs-pool#410]
for moner v8 what pool setting to use? 
"cnAlgorithm": ?
"cnVariant": ?
"cnBlobType": ?
is that it or i need to change other things ?
Thanks

**Comment by PsychoSterope** [comment]
"cnAlgorithm": cryptonight
"cnVariant": 8
"cnBlobType": 0

**Comment by bl00dy** [comment]
I found it. btw thank you :)

**Comment by prox443** [comment]
@bl00dy 
Can you share the right answer?
Thank you:)

**Comment by PsychoSterope** [comment]
@prox443 I posted the correct answer, I have 3 CNv8 pools.

"cnAlgorithm": "cryptonight",
"cnVariant": 8 ,
"cnBlobType": 0

**Comment by bl00dy** [comment]
yes its working
