### ISSUE TITLE
ryo can't work

### ISSUE THREAD

**Issue by caokun320** [dvandal/cryptonote-nodejs-pool#412]
![image](https://user-images.githubusercontent.com/37947730/50131035-40eb3c00-0278-11e9-9a3d-524584535d0b.png)

![image](https://user-images.githubusercontent.com/37947730/50130992-0aadbc80-0278-11e9-80f6-8c52fbf87f86.png)
![image](https://user-images.githubusercontent.com/37947730/50131045-46e11d00-0278-11e9-9565-81e42f5485b3.png)

**Comment by caokun320** [comment]
anybody can help me?

**Comment by muscleman** [comment]
you prolly need to contact the dev on discord. ryo has custom stuff you'll need to add
