### ISSUE TITLE
Wrong network hashrate & DIFFICULTY

### ISSUE THREAD

**Issue by lomax1981** [dvandal/cryptonote-nodejs-pool#414]
![image](https://user-images.githubusercontent.com/23190588/50333707-9e54e680-051f-11e9-8d28-235d46d47747.png)
    "coin": "monero",
    "symbol": "XMR",
    "coinUnits": 1000000000000,
    "coinDecimalPlaces": 4,
    "coinDifficultyTarget": 120,

How i can fix????
On this pool all is true
![image](https://user-images.githubusercontent.com/23190588/50333841-fb509c80-051f-11e9-81c9-1ac358b9e457.png)

**Comment by lomax1981** [comment]
monerod v 11 )))))))))))))))) download from monero.org

**Comment by muscleman** [comment]
wrong coindifficultytarget maybe?
