### ISSUE TITLE
Loki- blocks of 38 Loki

### ISSUE THREAD

**Issue by waterfallm** [dvandal/cryptonote-nodejs-pool#418]
Loki reward being overstated by a factor of x2.

Loki blocks displayed on website as 38 loki even though only 19 loki paided into wallet.

When payment due wallet unable to payout as trying to pay out twice as much as what came into wallet.

What is wrong in my config? used default loki config from site. Blocks being found and maturing just fine!

**Comment by ossii79** [comment]
This is due to the fact that LOKI blocks are indeed 38LOKI, but half of that goes to POS (masternodes).
If you implement these changes yourself it will work on your pool:
https://github.com/dvandal/cryptonote-nodejs-pool/pull/417/commits/1e04a3c800c1b13c5b9072eea0bfe76f797dc91c

**Comment by waterfallm** [comment]
I think i've appleid the fixes correctly but i've been getting following error.

TypeError: Cannot read property 'blocktemplate_blob' of undefined
    at /home/loki/pool/lib/pool.js:202:40
    at /home/loki/pool/lib/apiInterfaces.js:76:9
    at IncomingMessage.<anonymous> (/home/loki/pool/lib/apiInterfaces.js:46:13)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickCallback (internal/process/next_tick.js:181:9)

**Comment by muscleman** [comment]
usually mean wrong daemon port
