### ISSUE TITLE
Payments data (info) broken

### ISSUE THREAD

**Issue by sc0ch** [dvandal/cryptonote-nodejs-pool#42]
Payments collect block is broken, no data from API, no data change after block found. Tested on clean installation.

![image](https://user-images.githubusercontent.com/5249710/39333385-556a6508-49b3-11e8-9c51-c1f53b531248.png)

Current Payout Estimate not calculated too.

**Comment by dvandal** [comment]
Block has matured (unlocked) ?
Do you see any pending balance for other miners in admin interface?

Can you send me the content of theses logs files, if they exist: 
logs/unlocker_info.log
logs/unlocker_error.log
logs/payments_info.log
logs/payments_error.log

**Comment by sc0ch** [comment]
My bad... unlocker not started. By Current payout estimate still not calculated.

**Comment by dvandal** [comment]
What is your pool URL?

**Comment by dvandal** [comment]
Thanks, pool fee was removed from payout estimate.
