### ISSUE TITLE
XTL v9 fork compatiblity?

### ISSUE THREAD

**Issue by unsivilaudio** [dvandal/cryptonote-nodejs-pool#420]
I've updated my node-cryptonote-hashing from here

https://github.com/MoneroOcean/node-cryptonight-hashing

and changed "cnVariant" to 9 (and "coinTargetTime" to 300), however, something appears to be broken still, just wondering if it possibly could be pool related?  I've rebuilt my node modules several times, tried every combination of blob/variant type in my config, but still seem to get about 25% of shares coming from my miner, as "bad hash".

Any help from anyone reading this would be greatly appreciated.

ps I've eliminated the miners from being the issue as they don't experience rejects on other pools.

**Comment by muscleman** [comment]
not a pool issue, sounds like a miner issue
