### ISSUE TITLE
MASARI

### ISSUE THREAD

**Issue by gpuminingir** [dvandal/cryptonote-nodejs-pool#422]
Can anyone please make this work for the latest Masari update? or let me know how i can do it?

**Comment by muscleman** [comment]
gonna need masari hashing packages prolly. I'd look at the muscleman fork. i have logic to run with either forknote or hashing libraries

**Comment by gpuminingir** [comment]
for anyone else concerned, i managed to get it to work by changing the package.json file and replacing the following.

        "cryptoforknote-util": "git://github.com/masari-project/node-cryptonote-util",

also later after "npm update" in the node_modules renaming the cryptonote-util folder to "cryptoforknote-util".

**Comment by muscleman** [comment]
i think moneroocean package now supports fast v2
