### ISSUE TITLE
NPM UPDATE PROBLEM

### ISSUE THREAD

**Issue by shadowq7** [dvandal/cryptonote-nodejs-pool#425]
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack at ChildProcess.onExit (/root/.nvm/versions/node/v8.11.3/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack at emitTwo (events.js:126:13)
gyp ERR! stack at ChildProcess.emit (events.js:214:7)
gyp ERR! stack at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Linux 4.4.0-139-generic
gyp ERR! command "/root/.nvm/versions/node/v8.11.3/bin/node" "/root/.nvm/versions/node/v8.11.3/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /root/ryopool/node_modules/cryptonight-hashing
gyp ERR! node -v v8.11.3
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! cryptonight-hashing@6.0.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the cryptonight-hashing@6.0.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR! /root/.npm/_logs/2019-02-05T19_47_29_601Z-debug.log

**Comment by dendev83** [comment]
Its a big problem get it running... cost me 8 days.. Almost all i need to change nothing is up to date.. Got is working with nvm 8.15.0 and a lot of rebuild!

**Comment by muscleman** [comment]
"cryptonight-hashing": "git://github.com/MoneroOcean/node-cryptonight-hashing.git#e0704bd7e9e88f9bf8d8d5fe54766915b39b138b",

**Comment by shadowq7** [comment]
thank you so much, it solved
