### ISSUE TITLE
JsonValue type is not ARRAY or OBJECT

### ISSUE THREAD

**Issue by elphyrecoin** [dvandal/cryptonote-nodejs-pool#434]
Got an error in Admin Daemon section
Last status: fail
Last response: {"code":-32603,"message":"JsonValue type is not ARRAY or OBJECT"}

Though, it seems to work and blockchain height updating correctly...
Any idea ?

**Comment by disolutionsFL** [comment]
in lib/apiInterfaces.js:

add the following else in function rpc

    if(Object.keys(params).length !== 0) {
        options.json.params = params
    **}else{
        options.json.params = [];
    }**

**Comment by muscleman** [comment]
Yeah, i think i'm going to revert the apiInterfaces.js code back to a previous version.
