### ISSUE TITLE
Triton

### ISSUE THREAD

**Issue by pink68** [dvandal/cryptonote-nodejs-pool#439]
hi
Please send me config.json for triton coin

**Comment by pink68** [comment]
in other pool
network hash rate is 3.25MH/s

my : NETWORK HASH RATE
2.44 MH/sec

Does anyone know where the problem is?

**Comment by muscleman** [comment]
`    "symbol": "XTRI",
    "coinUnits": 10000,
    "coinDecimalPlaces": 4,
    "coinDifficultyTarget": 180,
    "daemonType": "default",
    "cnAlgorithm": "cryptonight_light",
    "cnVariant": 1,
    "cnBlobType": 1,
`
