### ISSUE TITLE
Discrod Notifications

### ISSUE THREAD

**Issue by CoFix** [dvandal/cryptonote-nodejs-pool#44]
Hello Dvandal,

Can you add discord webhook api for blocks, payments?

Thank You.

**Comment by dvandal** [comment]
I have some ideas on changes to notifications system in a more modular aproach so it will be easier to implement with any method choosen, will probably be one of my project next week.

**Comment by uekdyr** [comment]
Been trying to setup the email function, but can't get it to work with mailgun. @dvandal how to configure it correctly? I've edited the config.json both "email" section and "mailgun" section but it wont send email on miner disconnect etc. Is there any config I need to edit or what am I missing?

**Comment by dvandal** [comment]
Can you try using the new email test in Admin interface > Tools ? Then take a look at the email logs file to see what is wrong.

**Comment by bruceleeon** [comment]
@uekdyr I had issues with mailgun too, I gave up and use SMTP now. Email notifications working properly.

**Comment by bruceleeon** [comment]
@uekdyr @dvandal When using mailgun, the test sends successfully, the email log shows as sent, but mailgun never seems to receive anything. The mailgun logs are blank.

**Comment by uekdyr** [comment]
Did the same thing, using SMTP instead since mailguns IP addresses got banned every day..

Got it to work with mailgun tho. Are you using the latest build?

**Comment by travis1234** [comment]
Hey @dvandal I'd like to give my +1 for this feature too.

**Comment by helbadini** [comment]
Any progress on this issue? Discord notifications would be a huge feature...

**Comment by ossii79** [comment]
+1

**Comment by ossii79** [comment]
Any external tools for this maybe? Really prefer discord over telegram.
