### ISSUE TITLE
wownero can't work

### ISSUE THREAD

**Issue by caokun320** [dvandal/cryptonote-nodejs-pool#441]
![qq 20190226220001](https://user-images.githubusercontent.com/37947730/53418152-0962e380-39cf-11e9-862b-e58dfa536763.jpg)
![qq 20190226220018](https://user-images.githubusercontent.com/37947730/53418155-0c5dd400-39cf-11e9-9162-26b12e4ac572.jpg)
![qq 20190226220200](https://user-images.githubusercontent.com/37947730/53418185-1aabf000-39cf-11e9-8e1d-0ec7a964eb7e.jpg)
node use v8.11.3 
need help

**Comment by caokun320** [comment]
![qq 20190226220352](https://user-images.githubusercontent.com/37947730/53418305-665e9980-39cf-11e9-9096-5b9638f39e90.jpg)

**Comment by pcca-matrix** [comment]
Check my comment  for the fix !
https://github.com/dvandal/cryptonote-nodejs-pool/commit/614555e10b628b5c010ba7697a97efc00f0f20d7

**Comment by muscleman** [comment]
yeah i fixed it

**Comment by caokun320** [comment]
thanks
