### ISSUE TITLE
Problem in work. CN Fast

### ISSUE THREAD

**Issue by Bitfan1** [dvandal/cryptonote-nodejs-pool#442]
![default](https://user-images.githubusercontent.com/47179189/53435947-a9863000-3a02-11e9-8851-85979c84f19c.PNG)
Tell me what I did wrong?
In the screenshot launch:
node init.js -module = pool

**Comment by muscleman** [comment]
looks like your using the wrong variant and or blob type for Conceal

**Comment by Bitfan1** [comment]
Thank. I have already figured out! I looked at your answers in other questions and used them.
In particular, I used this advice:
https://github.com/dvandal/cryptonote-nodejs-pool/issues/387#issuecomment-449521691

**Comment by Bitfan1** [comment]
The truth is now there is a new message in the console:
![default](https://user-images.githubusercontent.com/47179189/53469570-18957000-3a67-11e9-934f-d921cf59fa8c.PNG)
How to fix, poke a finger :)

**Comment by Bitfan1** [comment]
Also, will the CCX fork soon support the script?

**Comment by muscleman** [comment]
so long as the moneroocean packages or mutli hashing packages support the new algo and you change the variant and blobtype you should be fine

**Comment by Bitfan1** [comment]
ОК
