### ISSUE TITLE
Is a pool software change required for next monero change on March 9?

### ISSUE THREAD

**Issue by mdm001** [dvandal/cryptonote-nodejs-pool#445]
Hi,

Not as much an issue and more of a question right now.

Will a pool change be necessary for the next Monero fork coming up around March 9 at block 1788000?  If yes, please provide any required configuration changes, etc.  I assume I'll at least need to change the cnVariant to a new parameter for CNv4 / cryptonightR, but don't know what that will be.  4?

Thank you!

**Comment by muscleman** [comment]
new flags and a correct package from moneroocean should be good.

**Comment by mdm001** [comment]
Thank you muscleman.  I'll try to figure this out.  I'm a bit of a noob.

**Comment by muscleman** [comment]
if it don't work. gimme a shout
