### ISSUE TITLE
auto variant xmrig

### ISSUE THREAD

**Issue by newsmoneymaker** [dvandal/cryptonote-nodejs-pool#448]
Good day,

please explain to me how this works.

I run two pools: a graft and a Lethean with the same configurations and the miner gives cn/2 and cn/1 if you leave just -cryptonight without --variant (auto).  How does the miner (xmrig) decide which option to use?

**Comment by muscleman** [comment]
this an issue still, have you upgraded xmrig?

**Comment by newsmoneymaker** [comment]
Good day, in the new miner is defined as cn/r и cn/1. 

Miner when automatically determining where it takes information from the pool, which option to put? This information "cnVariant" in config.json as a miner as if does not see with the automatic selection "--variant"

**Comment by pcca-matrix** [comment]
If what you want is your pool send the correct  algo (cn/variant) to mining client software , use

"includeAlgo": "cn/r" for lethean 
or 
"includeAlgo": "cn/rwz" for your graft pool

in your pool config.json

**Comment by newsmoneymaker** [comment]
Hooray!!!!!!!!!!!!!!!!!!!!!!! Thanks friends!

**Comment by newsmoneymaker** [comment]
Good afternoon, and you can somehow indicate on the pool that another algorithm was chosen without indication in the miner? eg cryptonight cryptonight-lite cryptonight-heavy

something like this
        if (typeof config.cnAlgorithm !== "undefined" && config.cnAlgorithm)
            this.cachedJob['cnAlgorithm'] = config.cnAlgorithm

sorry little understand this =)))))

**Comment by newsmoneymaker** [comment]
> If what you want is your pool send the correct algo (cn/variant) to mining client software , use
> 
> "includeAlgo": "cn/r" for lethean
> or
> "includeAlgo": "cn/rwz" for your graft pool
> 
> in your pool config.json

Good afternoon, and you can somehow indicate on the pool that another algorithm was chosen without indication in the miner? eg cryptonight cryptonight-lite cryptonight-heavy

something like this
if (typeof config.cnAlgorithm !== "undefined" && config.cnAlgorithm)
this.cachedJob['cnAlgorithm'] = config.cnAlgorithm

sorry little understand this =)))))

**Comment by newsmoneymaker** [comment]
> this an issue still, have you upgraded xmrig?

Good afternoon, and you can somehow indicate on the pool that another algorithm was chosen without indication in the miner? eg cryptonight cryptonight-lite cryptonight-heavy

something like this
if (typeof config.cnAlgorithm !== "undefined" && config.cnAlgorithm)
this.cachedJob['cnAlgorithm'] = config.cnAlgorithm

sorry little understand this =)))))
