### ISSUE TITLE
summary payment

### ISSUE THREAD

**Issue by minhnt812018** [dvandal/cryptonote-nodejs-pool#45]
Could you please function to summary payment as miner earned everyday?

**Comment by dvandal** [comment]
Can you give me more details of want you would like exactly? Not sure to understand your request.

**Comment by minhnt812018** [comment]
please view a pic
![1](https://user-images.githubusercontent.com/37006960/39414709-fa832b84-4c64-11e8-9a5f-b19f5fabc470.png)
ture

**Comment by dvandal** [comment]
Thanks, the feature has been added.

**Comment by minhnt812018** [comment]
hi, i found a bug when press Load more, it count not correct
