### ISSUE TITLE
Add SoftShell

### ISSUE THREAD

**Issue by arbourp** [dvandal/cryptonote-nodejs-pool#451]
Hi.
I'm trying to add amityCoin to the pool, and I'm more than happy to do the leg work.

Amitycoin is using the softshell algorithm.  I'm not sure where to start to add this in to the pool.

Thanks.

**Comment by muscleman** [comment]
which version, CalexCore, Watt3r or brandonlehmann

**Comment by muscleman** [comment]
looks like bytecoin based

**Comment by muscleman** [comment]
there is not algo support yet
