### ISSUE TITLE
Bug Pool.js

### ISSUE THREAD

**Issue by pcca-matrix** [dvandal/cryptonote-nodejs-pool#452]
line 406:
if (typeof config.includeAlgo !== "undefined" && config.includeHeight)
must be
if (typeof config.includeHeight !== "undefined" && config.includeHeight)

and 
this.cachedJob['algo'] = config.algo

this.cachedJob['algo'] = config.includeAlgo

**Comment by muscleman** [comment]
nice spotting the copy pasta bug
