### ISSUE TITLE
Bug JobRefresh

### ISSUE THREAD

**Issue by pcca-matrix** [dvandal/cryptonote-nodejs-pool#455]
Hi muscleman,

With static buffer method commited some time ago , there is a problem with the jobrefresh function.

if daemon crash or goes offline , pool also crash because result.blocktemplate_blob does not exist!

this stop the jobrefresh  for connected miner !

when daemon goes online again , there is no more jobs send to miners , miners work for nothing on an wrong old block until your restart the pool. 

here is the fixed function

`function jobRefresh(loop, callback){
    callback = callback || function(){};
    getBlockTemplate(function(error, result){
		
        if (loop)
            setTimeout(function(){
                jobRefresh(true);
            }, config.poolServer.blockRefreshInterval);
	
        if (error){
            log('error', logSystem, 'Error polling getblocktemplate %j', [error]);
            if (!poolStarted) log('error', logSystem, 'Could not start pool');
            callback(false);
            return;
        }
		
        let buffer = Buffer.from(result.blocktemplate_blob, 'hex');
        let new_hash = Buffer.alloc(32);
        buffer.copy(new_hash, 0, 7, 39);
		
        if (!currentBlockTemplate || result.height > currentBlockTemplate.height) {
            log('info', logSystem, 'New block to mine at height %d w/ difficulty of %d', [result.height, result.difficulty]);
            processBlockTemplate(result);
        }
        if (!poolStarted) {
            startPoolServerTcp(function(successful){ poolStarted = true });
        }
        callback(true);
    })
}`

**Comment by pcca-matrix** [comment]
also why are you using that ?

        let buffer = Buffer.from(result.blocktemplate_blob, 'hex');
        let new_hash = Buffer.alloc(32);
        buffer.copy(new_hash, 0, 7, 39);

var new_hash is not used anywhere on this function ?

**Comment by muscleman** [comment]
can you make a pull request

**Comment by muscleman** [comment]
So your fix amounts to removing the3 lines of ccode. I'll have to look at the commit history to determine when why it was added. And yes your correct it's not used

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by pcca-matrix** [comment]
i'm away from home  ,
 just remove the 3 lines of old code and put the loop condition in first , not error  !
