### ISSUE TITLE
high frequency pool.js issues with daemon timeout

### ISSUE THREAD

**Issue by gr8form** [dvandal/cryptonote-nodejs-pool#456]
Updated to latest version following pool.js update of 2 days ago (removed node_modules & npm updated following clone), but am receiving below error at a high frequency, pool configured for Monero/cryptonight-r algo:.  Note, I've changed the daemon ip address (x.x.x.x), port (yyyyy) & pool wallet (zzz.zzz) info.  The daemon node is running on the same server, there's plenty of CPU & RAM, it's been fully sync'd and not showing any errors.

2019-03-16 18:50:08 (Thread 2) Error polling getblocktemplate {"name":"RequestError","message":"Error: connect ETIMEDOUT x.x.x.x:yyyyy","cause":{"code":"ETIMEDOUT","errno":"ETIMEDOUT","syscall":"connect","address":"x.x.x.x","port":yyyyy},"error":{"code":"ETIMEDOUT","errno":"ETIMEDOUT","syscall":"connect","address":"x.x.x.x","port":yyyyy},"options":{"uri":"http://x.x.x.x:yyyyy/json_rpc","method":"POST","headers":{"Content-Type":"application/json","Accept":"application/json"},"json":{"id":"0","jsonrpc":"2.0","method":"getblocktemplate","params":{"reserve_size":17,"wallet_address":"zzz.zzz"}},"simple":true,"resolveWithFullResponse":false,"transform2xxOnly":false}}

Let me know what add'l info is needed that I can provide from the pool or the daemon
Thanks much in advance!

**Comment by gr8form** [comment]
Also seeing a lot of these errors in the api_error log, again, daemon is sync'd and on mainnet:

2019-03-17 13:30:33 Error getting last block data {"name":"RequestError","message":"Error: connect ETIMEDOUT x.x.x.x:yyyyy","cause":{"code":"ETIMEDOUT","errno":"ETIMEDOUT","syscall":"connect","address":"x.x.x.x","port":yyyyy},"error":{"code":"ETIMEDOUT","errno":"ETIMEDOUT","syscall":"connect","address":"x.x.x.x","port":yyyyy},"options":{"uri":"http://x.x.x.x:xxxxx/json_rpc","method":"POST","headers":{"Content-Type":"application/json","Accept":"application/json"},"json":{"id":"0","jsonrpc":"2.0","method":"getlastblockheader","params":{}},"simple":true,"resolveWithFullResponse":false,"transform2xxOnly":false}}
2019-03-17 13:30:33 Error collecting all stats

**Comment by muscleman** [comment]
wonder if they have moved to the newer version of GetBlockTemplate

**Comment by gr8form** [comment]
Happy to though bit unsure of the proper command syntax, is this correct with proper ip address, port & wallet info?

curl -i -X {"uri":"http://x.x.x.x:yyyyy/json_rpc","method":"POST","headers":{"Content-Type":"application/json","Accept":"application/json"},"json":{"id":"0","jsonrpc":"2.0","method":"getblocktemplate","params":{"reserve_size":17,"wallet_address":"abc.zzz"}},"simple":true,"resolveWithFullResponse":false,"transform2xxOnly":false}

**Comment by gr8form** [comment]
running it the below way results in:
curl -i -X GET http://x.x.x.x:yyyyy/json_rpc

HTTP/1.1 200 Ok
Server: Epee-based
Content-Length: 111
Content-Type: text/plain
Last-Modified: Sun, 17 Mar 2019 17:26:33 GMT
Accept-Ranges: bytes

{
  "error": {
    "code": -32600,
    "message": "Invalid Request"
  },
  "id": 0,
  "jsonrpc": "2.0"

**Comment by gr8form** [comment]
Also, FWIW, from the same host and to the destination daemon host, but with a different port that is setup to receive json, I'm get expected correct output from using curl command: curl -i -X GET http://x.x.x.x:8080/json_rpc

**Comment by gr8form** [comment]
FYI, tried applying the in-dev updated pool.js from https://github.com/dvandal/cryptonote-nodejs-pool/pull/457/files; same result as above.

**Comment by gr8form** [comment]
I've confirmed json_rpc works against my daemon by using the getmonero guide found here:
[https://www.getmonero.org/resources/developer-guides/daemon-rpc.html#get_block_template](url)
and the getblocktemplate example:
curl -X POST http://127.0.0.1:18081/json_rpc -d '{"jsonrpc":"2.0","id":"0","method":"get_block_template","params":{"wallet_address":"44GBHzv6ZyQdJkjqZje6KLZ3xSyN1hBSFAnLP6EAqJtCRVzMzZmeXTC2AHKDS9aEDTRKmo6a6o9r9j86pYfhCWDkKjbtcns","reserve_size":60}' -H 'Content-Type: application/json'
My output:
{
  "id": "0",
  "jsonrpc": "2.0",
  "result": {
    "blockhashing_blob": "0b0be0d9c2e40584424ff9424dc10a52f3300a3d3228e9f6a280ee64d39b34a76b300818bd11ad000000005bf20ef9f39bb9cad209144c08e1a58390546a28edeefc9d76f231831363d28304",
    "blocktemplate_blob": "0b0be0d9c2e40584424ff9424dc10a52f3300a3d3228e9f6a280ee64d39b34a76b300818bd11ad0000000002b6c06d01fffabf6d0198e587fef85702c2ab4ec7822b4a5be3a62113696d268b85f33799bf4dc7b29b0ba7b8c9bd26c3340139fffd66a962e706fee90c648e792619d27ba1eac5d83857deb4c1aa778649780211000000000000000000000000000000000000039e04a11f06a700f9211ba0421747f290ed15700b54140d98164fde82bb48265627b2e51eeefe0990a1f93d2efe85ef1872d6092007739c0ff5497f9856c57e0761006a184d0fa6f00555acf8327464a6db3747c8d5c9b7094a8880609cbd5e35",
    "difficulty": 35664010722,
    "expected_reward": 3021773861528,
    "height": 1794042,
    "prev_hash": "84424ff9424dc10a52f3300a3d3228e9f6a280ee64d39b34a76b300818bd11ad",
    "reserved_offset": 128,
    "status": "OK",
    "untrusted": false
  }
I also works when I change the reserve_size from 60 in the example to 17 from the initial error code above.  I think that rules out communicating with the daemon.

**Comment by muscleman** [comment]
this fixed?

**Comment by gr8form** [comment]
Not as of last week, hadn't see any new code changes, but retried on a different server with a different daemon, same result.

**Comment by muscleman** [comment]
well i don't think this rules out the daemon. The pool is throwing errors because it is unable to get the required result from the daemon in the allotted time. ie) timeout.
do you have multiple pools calling the same daemon?

**Comment by gr8form** [comment]
No I don’t and, to test just that same hypothesis, I used sammy007 stratum pool against the same daemon and it worked just fine. Frankly, I’ve been running that since my post though would rather use yours as I can I quickly change coins.  Thanks for checking
________________________________

**Comment by muscleman** [comment]
which sammy007 i'll look at the code

**Comment by muscleman** [comment]
monero-stratum

**Comment by muscleman** [comment]
hmm, well it's an interesting challenge. I'll need to dig in and take a look, could well be room to optimize this some. how much hash are you pushing into the pool?

**Comment by gr8form** [comment]
22k cryptonight_r.  Interestingly, I don’t experience it with a different coin, conceal network CCX, on your pool which uses a different daemon, just cn_r; so, I get the daemon hyposthesis
________________________________

**Comment by gr8form** [comment]
Correct, monero-stratum
________________________________

**Comment by muscleman** [comment]
22kh, yep you have something configured wrong

**Comment by muscleman** [comment]
so what pool coin are you mining for cryptonight_r

**Comment by gr8form** [comment]
Monero
________________________________

**Comment by pcca-matrix** [comment]
this can happen if you ask too often blocktemplate with a lot of threads at low refreshrate.

on my 32 cores server with refreshblocktemplate 250ms , daemon eat all the cpu power in minutes this end by a deamon timeout issue.

try to limit thread to see if it helps -> "clusterForks": 3

Or what i did is instead of pooling each time getblocktemplate (cpu intensive) , use getlastblockheader and when height and/or hash change , start pooling getblocktemplate. 
I can pool daemon every 100ms without trouble on 8 or 16 Threads.

If i have free time this week I'll make a pull request with that.

**Comment by muscleman** [comment]
I believe there is an optimized fix floating around someplace.

**Comment by gr8form** [comment]
hmm, ok; I get what you're saying.  My config is set to 1 sec block refresh and auto for cluster threads on my 32 core server also which I think starts at 5 threads, but will have to check that.  I know where in the config.json to change the refresh from getblocktemplate to getblockheader, but am unsure how to dynamically have it change back to getblocktemplate once a new block height occurs; are you using custom code or is there another setting in the config.json?  I'm up for testing your pull if you have the time.

One idea perhaps worth pursuing instead of polling the daemon consider coding, likely a major enhancement, to act as a p2p peer to get immediately notified once a new block occurs vs a json rpc call at a set time; should reduce latency and theoretically find new blocks faster.  That said, if you can resolve the thread issue and increasing the polling frequency works, then perhaps that's good enough.

________________________________

**Comment by muscleman** [comment]
Think node fires up a pool thread per cpu

**Comment by muscleman** [comment]
Set auto to 4-8

**Comment by pcca-matrix** [comment]
> Think node fires up a pool thread per cpu
it open a fork for each virtual or logical CPU/core

@gr8form yes i'm using custom code, pull request is submitted

**Comment by gr8form** [comment]
Awesome, thanks will give it a shot this weekend.

________________________________

**Comment by gr8form** [comment]
Spent a few hours this morning with pcca-matrix's repo (thanks very much!), I still ended up with a fair amount of the api errors still though at a lower frequency and noticed a blank monitoring page for the admin web page which was weird as all the other pages worked just fine.  I also tried different various non-auto settings for clusterforks as recommended with some higher or lower still, but had no improvement.  Appreciate all the help!  For now, I'm back to sammy's monero-stratum, actually, SmokinCache's fork of it which is working well for me.  So, I don't know if you want to close this or not; I'm good either way.  Cheers!

**Comment by pcca-matrix** [comment]
Strange that it does not work ! 
is your deamon is local or distant ?
also, blank web admin page is not normal

**Comment by gr8form** [comment]
Agreed strange, daemon is local to the pool server and it was just the monitoring page within the admin meaning that the other admin pages were fine...thanks much anyways guys.

________________________________

**Comment by muscleman** [comment]
implemented fix. based on pcca-matrix pull request
