### ISSUE TITLE
npm ERR! multi-hashing@0.0.9 install: `node-gyp rebuild`

### ISSUE THREAD

**Issue by leisegang** [dvandal/cryptonote-nodejs-pool#46]
make: *** [Release/obj.target/multihashing/cn_heavy/cn_slow_hash_hard_intel.o] Error 1
make: Leaving directory `/pinkstar/pool/node_modules/multi-hashing/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/pinkstar/.nvm/versions/node/v4.8.7/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:12)
gyp ERR! System Linux 3.13.0-139-generic
gyp ERR! command "/pinkstar/.nvm/versions/node/v4.8.7/bin/node" "/pinkstar/.nvm/versions/node/v4.8.7/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /pinkstar/pool/node_modules/multi-hashing
gyp ERR! node -v v4.8.7
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
npm ERR! Linux 3.13.0-139-generic
npm ERR! argv "/pinkstar/.nvm/versions/node/v4.8.7/bin/node" "/pinkstar/.nvm/versions/node/v4.8.7/bin/npm" "update"
npm ERR! node v4.8.7
npm ERR! npm  v2.15.11
npm ERR! code ELIFECYCLE

npm ERR! multi-hashing@0.0.9 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the multi-hashing@0.0.9 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the multi-hashing package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs multi-hashing
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls multi-hashing
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /pinkstar/pool/npm-debug.log

**Comment by dvandal** [comment]
npm ERR! Please include the following file with any support request:
npm ERR! /pinkstar/pool/npm-debug.log

Can you provides me the content of this file?

**Comment by dvandal** [comment]
Closing this ticket due to inactivity, if still an issue you can reopen it at any times.

**Comment by leisegang** [comment]
https://pastebin.com/aZDENskg

Error log.

**Comment by leisegang** [comment]
Tried with node 4.0.0
4.8.7 and 4.9.2

Will not work. What os and node do I have to use?

**Comment by dvandal** [comment]
Please try using lastest code (release 1.3.2)

**Comment by leisegang** [comment]
What node version and npm do you recommend?

**Comment by dvandal** [comment]
Node.JS 4.x or 8.x both works, I recommend 8.x

**Comment by dvandal** [comment]
Do you still have issues with lastest code? You may need to remove node_modules and package_lock.json
