### ISSUE TITLE
Package.json

### ISSUE THREAD

**Issue by waterfallm** [dvandal/cryptonote-nodejs-pool#468]
Looks to be an error on ln 18 "#ipbc" I had to remove and re npm update and updated pool started to accept conceal shares.

updated pool was rejecting ccx shares.

**Comment by muscleman** [comment]
you use this https://github.com/ConcealNetwork/node-cryptonight-hashing

and change the variant to 11 and algo to cryptonight?

**Comment by muscleman** [comment]
this fixed?

**Comment by waterfallm** [comment]
making the update as per comment #1 allow and removing "#ipbc" allowed the pool to process shares
