### ISSUE TITLE
Block unlocker marking all blocks as orphaned

### ISSUE THREAD

**Issue by coolsd** [dvandal/cryptonote-nodejs-pool#47]
![1](https://user-images.githubusercontent.com/7413058/39412822-988c2a30-4c54-11e8-8f08-866fcfa4c811.png)
![2](https://user-images.githubusercontent.com/7413058/39412825-9ccdd77e-4c54-11e8-8cd6-c4ea98e8444f.png)
![3](https://user-images.githubusercontent.com/7413058/39414180-43dc0ad8-4c67-11e8-93bd-d1b9c469287a.png)

**Comment by coolsd** [comment]
`{
    "coin": "intuCoin",
    "symbol": "INTU",
    "coinUnits": 100,
    "coinDifficultyTarget": 120,
    "cnAlgorithm": "cryptonight",
    "cnVariant": 1,

    "logging": {
        "files": {
            "level": "info",
            "directory": "logs",
            "flushInterval": 5
        },
        "console": {
            "level": "info",
            "colors": true
        }
    },

    "poolServer": {
        "enabled": true,
        "clusterForks": "auto",
        "poolAddress": "intuvSoW7Z42YTJuWFbyTQJmNResynTCdMXUVBtaayA93MmbEKeXz7EPPJxLVp7ZG873ugMvxfAhZcBdHPRmgEZrijq67gU1DPh",
        "blockRefreshInterval": 1000,
        "minerTimeout": 900,
        "sslCert": "./ssl/cert.pem",
        "sslKey": "./ssl/privkey.pem",
        "sslCA": "./ssl/chain.pem",
        "ports": [
            {
                "port": 10333,
                "difficulty": 5000,
                "desc": "Low end hardware"
            },
            {
                "port": 10444,
                "difficulty": 15000,
                "desc": "Mid range hardware"
            },
            {
                "port": 10555,
                "difficulty": 25000,
                "desc": "High end hardware"
            },
            {
                "port": 10777,
                "difficulty": 500000,
                "desc": "Cloud-mining / NiceHash"
            },
            {
                "port": 10999,
                "difficulty": 20000,
                "desc": "SSL connection",
                "ssl": false
            }
        ],
        "varDiff": {
            "minDiff": 100,
            "maxDiff": 1000000,
            "targetTime": 60,
            "retargetTime": 30,
            "variancePercent": 30,
            "maxJump": 100
        },
        "paymentId": {
            "addressSeparator": "."
        },
        "fixedDiff": {
            "enabled": true,
            "addressSeparator": "+"
        },
        "shareTrust": {
            "enabled": true,
            "min": 10,
            "stepDown": 3,
            "threshold": 10,
            "penalty": 30
        },
        "banning": {
            "enabled": true,
            "time": 600,
            "invalidPercent": 25,
            "checkThreshold": 30
        },
        "slushMining": {
            "enabled": false,
            "weight": 300,
            "blockTime": 60,
            "lastBlockCheckRate": 1
         }
    },

    "payments": {
        "enabled": true,
        "interval": 3600,
        "maxAddresses": 50,
        "mixin": 3,
        "priority": 0,
        "transferFee": 10,
        "dynamicTransferFee": true,
        "minerPayFee" : true,
        "minPayment": 1000,
        "maxTransactionAmount": 0,
        "denomination": 1
    },

    "blockUnlocker": {
        "enabled": true,
        "interval": 30,
        "depth": 100,
        "poolFee": 1.0,
        "devDonation": 0.0
    },

    "api": {
        "enabled": true,
        "hashrateWindow": 600,
        "updateInterval": 5,
        "bindIp": "0.0.0.0",
        "port": 10117,
        "blocks": 30,
        "payments": 30,
        "password": "******",
        "ssl": false,
        "sslPort": 8119,
        "sslCert": "./cert.pem",
        "sslKey": "./privkey.pem",
        "sslCA": "./chain.pem",
        "trustProxyIP": false
    },

    "daemon": {
        "host": "127.0.0.1",
        "port": 31570
    },

    "wallet": {
        "host": "127.0.0.1",
        "port": 31571
    },

    "redis": {
        "host": "127.0.0.1",
        "port": 6379,
        "auth": null,
        "db": 0,
        "cleanupInterval": 15
    },

    "email": {
        "enabled": false,
        "templateDir": "email_templates",
        "disableTemplates": [],
        "variables": {
            "POOL_HOST": "poolhost.com"
        },
        "fromAddress": "your@email.com",
        "transport": "sendmail",
        "sendmail": {
            "path": "/usr/sbin/sendmail"
        },
        "smtp": {
            "host": "smtp.example.com",
            "port": 587,
            "secure": false,
            "auth": {
                "user": "username",
                "pass": "password"
            }
        },
        "mailgun": {
            "key": "your-private-key",
            "domain": "mg.yourdomain"
        }
    },

    "telegram": {
        "enabled": false,
        "token": "",
        "channel": ""
    },
    
    "monitoring": {
        "daemon": {
            "checkInterval": 60,
            "rpcMethod": "getblockcount"
        },
        "wallet": {
            "checkInterval": 60,
            "rpcMethod": "getbalance"
        }
    },

    "prices": {
        "source": "tradeogre",
        "currency": "USD"
    },
    
    "charts": {
        "pool": {
            "hashrate": {
                "enabled": true,
                "updateInterval": 60,
                "stepInterval": 1800,
                "maximumPeriod": 86400
            },
            "miners": {
                "enabled": true,
                "updateInterval": 60,
                "stepInterval": 1800,
                "maximumPeriod": 86400
            },
            "workers": {
                "enabled": true,
                "updateInterval": 60,
                "stepInterval": 1800,
                "maximumPeriod": 86400
            },
            "difficulty": {
                "enabled": true,
                "updateInterval": 1800,
                "stepInterval": 10800,
                "maximumPeriod": 604800
            },
            "price": {
                "enabled": true,
                "updateInterval": 1800,
                "stepInterval": 10800,
                "maximumPeriod": 604800
            },
            "profit": {
                "enabled": true,
                "updateInterval": 1800,
                "stepInterval": 10800,
                "maximumPeriod": 604800
            }
        },
        "user": {
            "hashrate": {
                "enabled": true,
                "updateInterval": 180,
                "stepInterval": 1800,
                "maximumPeriod": 86400
            },
            "payments": {
                "enabled": true
            }
        }
    }
}
`

**Comment by dvandal** [comment]
Is coin daemon in sync with the network? Orphaned blocks are often due to bad synchronisation.

**Comment by dvandal** [comment]
I looked at the link, this is an issue with the coin that you need to manually fix in pool daemon:

This can be temporarily fixed by changing line 62 of blockUnlocker.js from
apiInterfaces.rpcDaemon('getblockheaderbyheight', {height: **block.height**}, function(error, result){
to
apiInterfaces.rpcDaemon('getblockheaderbyheight', {height: **block.height + 1**}, function(error, result){

**Comment by dvandal** [comment]
Can you try and let me know if this works with this coin?

**Comment by flychicken123** [comment]
@coolsd how did you fix this issue? and how did you reprocess all the blocks. I am facing same issue right now

**Comment by SomeFixItDude** [comment]
I would like to reprocess all my blocks has anyone done this??  @flychicken123 @coolsd

**Comment by muscovydux** [comment]
@coolsd @flychicken123 @dvandal @SomeFixItDude 
I also had a bunch of false orphans for my turtlecoin pool. Is there any way to have these reprocessed and paid out? Or do I have to somehow figure payouts manually?
