### ISSUE TITLE
cannot find block

### ISSUE THREAD

**Issue by fakeptolemei** [dvandal/cryptonote-nodejs-pool#470]
Pool started and working fine without any errors but I cannot find block, Effort already 300%.
I'm mining Monero with nicehash on my pool with static diff 3000000. Can someone answer the question:  This is because static diff I cannot find any block yet, or it is only bad luck?

**Comment by hypeboard** [comment]
honestly probably bad luck. There is a lot of other hashers on the XMR
network and you are competing with them all to find a block.

**Comment by trasherdk** [comment]
To form an opinion,  your pool hashrate must be known.

**Comment by fakeptolemei** [comment]
200-500kh/s

**Comment by trasherdk** [comment]
Well, with that much hash, you could, if being extremely lucky, find a solo block, but probably not often enough to make it profitable.

You would be better off joining a mining pool.

**Comment by fakeptolemei** [comment]
After a bad luck, blocks will find with good effort i think.  I only had a question: static diff somehow affects? or it is not important with what difficulty you take shares.

Thanks for response!

**Comment by trasherdk** [comment]
I think it's a balance act. Normally I would let the miners and pool auto-adjust the diff. They are pretty good at it.

But if you insist on a fixed diff, then find the diff, where you get the most accepted shares on the pool.
It's not necessarily the same diff for each miner.
