### ISSUE TITLE
Website average luck

### ISSUE THREAD

**Issue by ossii79** [dvandal/cryptonote-nodejs-pool#476]
/#pool_blocks does that just show the average luck based on the blocks shown on the initial list?
If yes, how to change it to show alltime?

Maybe even better, still only if yes to the above question:
/#pool_blocks shows average luck based on the list of blocks shown, dynamicly.
If you click show more blocks the average luck adjusts based on the blocks shown.
Then on the top line along with Network, Pool and Your hashrate have a pool average luck (all time).

-Osi

**Comment by muscleman** [comment]
you could change config.api.blocks to -1 which will bring back every block you have collected.

or you could edit api.js between 190 and 202 and add another call to redis to get all blocks and recalculate this

                for (var i = 0; i < data.blocks.length; i++){
                    var block = data.blocks[i].split(':');
                    if (block[5]) {
                        var blockShares = parseInt(block[3]);
                        var blockDiff = parseInt(block[2]);
                        data.totalDiff += blockDiff;
                        data.totalShares += blockShares;
                    }
                }

**Comment by ossii79** [comment]
@muscleman Any chance of a bit more "hold my hand details" on updating the /#pool_blocks page with the average luck when you click "load more"?

Also, I'd like to put on the top bar along with Network: .. Pool: ... You: ... Avg. Luck. ...
Where Avg. Luck is an all time average luck, or a set number of blocks (last 10000 for example).

Bit more details on the points then I might manage :)

-Osi

**Comment by muscleman** [comment]
https://github.com/dvandal/cryptonote-nodejs-pool/blob/master/config_examples/arqma.json#L143
add a parameter "luckBlocks": 1000


https://github.com/dvandal/cryptonote-nodejs-pool/blob/master/lib/api.js#L203
add another redis command
['zrange', config.coin + ':blocks:matured', 0, config.api.luckBlocks ? config.api.luckBlocks : -1, 'WITHSCORES']


then change line 236 to read.

for (var i = 0; i < replies[3].concat(replies[12]).length; i++)

https://github.com/dvandal/cryptonote-nodejs-pool/blob/master/website_example/index.html#L75

add this
<div id="section"><span tkey="luck">You</span>: <strong><span id="g_poolLuck"><span tkey="na">N/A</span></span></strong></div>

https://github.com/dvandal/cryptonote-nodejs-pool/blob/master/website_example/index.html#L147
add the following

    if (lastStats.pool.totalDiff && lastStats.pool.totalShares)
	updateText('g_poolLuck', formatLuck(lastStats.pool.totalDiff, lastStats.pool.totalShares));

so, now i'm at this point i just added this myself.

M.

**Comment by ossii79** [comment]
Hmm, getting this:

/lib/api.js:245
                }
                ^

SyntaxError: missing ) after argument list
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:617:28)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/crypto/ombpool/init.js:38:13)

**Comment by muscleman** [comment]
try that, i missed a {, lack of coffee

**Comment by ossii79** [comment]
for (var i = 0; i < replies[3].concat(replies[12]).length; i++){ <-- added it here as I see the others got.
Then error changed to:

> TypeError: Cannot read property 'split' of undefined
>     at Multi.callback (/home/crypto/ombpool/lib/api.js:238:48)
>     at multi_callback (/home/crypto/ombpool/node_modules/redis/lib/multi.js:89:14)
>     at Command.callback (/home/crypto/ombpool/node_modules/redis/lib/multi.js:116:9)
>     at normal_reply (/home/crypto/ombpool/node_modules/redis/index.js:726:21)
>     at RedisClient.return_reply (/home/crypto/ombpool/node_modules/redis/index.js:824:9)
>     at JavascriptRedisParser.returnReply (/home/crypto/ombpool/node_modules/redis/index.js:192:18)
>     at JavascriptRedisParser.execute (/home/crypto/ombpool/node_modules/redis-parser/lib/parser.js:553:10)
>     at Socket.<anonymous> (/home/crypto/ombpool/node_modules/redis/index.js:274:27)
>     at emitOne (events.js:116:13)
>     at Socket.emit (events.js:211:7)
>     at addChunk (_stream_readable.js:263:12)
>     at readableAddChunk (_stream_readable.js:250:11)
>     at Socket.Readable.push (_stream_readable.js:208:10)
>     at TCP.onread (net.js:601:20)
>

**Comment by ossii79** [comment]
Ok, grabbed the api.js from github directly. works now.
However the website got weird:
Network: 24.50 kH/sec
Pool: 0.00 H/sec
You: N/A
You: <span class="luckMid">105%</span>

**Comment by ossii79** [comment]
Seems I got it, skipped the coloring it seems by changing:
`updateText('g_poolLuck', formatLuck(lastStats.pool.totalDiff, lastStats.pool.totalShares));`

to
`$('#g_poolLuck').html(formatLuck(lastStats.pool.totalDiff, lastStats.pool.totalShares));`

**Comment by muscleman** [comment]
yeah, i forgot formatLuck returns html
