### ISSUE TITLE
Pool Name problem.

### ISSUE THREAD

**Issue by PsychoSterope** [dvandal/cryptonote-nodejs-pool#48]
With the latest update the pool name in the top left corner gets over written. 
This is what happens with the live version: (wrong)
![wrong](https://user-images.githubusercontent.com/22012344/39424952-acfd437a-4c3e-11e8-9680-9fa0fe166267.png)

This is what happens with the non-live version: (right)
![right](https://user-images.githubusercontent.com/22012344/39424980-d3b62fc2-4c3e-11e8-92f7-31c3b6671346.png)

I can't for the life of me figure out where the setting is to stop it from being overwritten. I even setup a 100% fresh VM thinking my live pool was the problem, but even the brand new setup does the same thing.  

Any ideas?

**Comment by dvandal** [comment]
Just remove the span inside <a></a> and replace it with your content. 
"coinSymbol" is automatically replaced by the setting in pool config and tkey="miningPool" is automatially replaced from translation file.

**Comment by PsychoSterope** [comment]
Worked perfect! Thanks!
