### ISSUE TITLE
XtendCash

### ISSUE THREAD

**Issue by RavenHuginn** [dvandal/cryptonote-nodejs-pool#482]
hi
Please send me config.json for XtendCash coin

**Comment by muscleman** [comment]
how about i teach you to fish instead. then you can set these up yourself and help the community out.
1) find dvandal pool that uses same software, try at miningpoolstats.com
2) go to pool, lets use https://pool.xtendcash.com/
3) in chrome open dev tools f12
4) select network tab
5) refresh https://pool.xtendcash.com/ while the network tab is open
6) select the entry from the list called [stats]
7) in the right panel, select preview
8) in preview tab, select the config section to observe the setup for that pool.
9) make a base version from the turtlecoin version on the dvandal site
10) copy settings from step 8 into your base version
11) test pool
12) pull request to add to dvandal config examples.

**Comment by RavenHuginn** [comment]
Thank you so much
