### ISSUE TITLE
Binding pool to IP

### ISSUE THREAD

**Issue by ossii79** [dvandal/cryptonote-nodejs-pool#487]
Is it possible to bind the service to a specific IP?
Say I have 4 IPs on a server and I want to service 4 different pools on among other ports, a common port of 80 and 443.

-Osi

**Comment by trasherdk** [comment]
This can be done using DNS and reverse proxy on one IP address.

**Comment by ossii79** [comment]
@trasherdk ok? nginx for example works also on the mining ports?

**Comment by trasherdk** [comment]
You can use `nginx`/`apache` or anything that support reverse proxy.

Or you can dive into [/lib/pool.js](https://github.com/dvandal/cryptonote-nodejs-pool/blob/dc125a8700b1df0d4c19e4bae54af896294bd081/lib/pool.js#L1064) and reference [net](https://nodejs.org/api/net.html) documentation.

**Comment by ossii79** [comment]
That's only for the API, I tried that one. Was hoping for a way to implement the same for the pools mining ports as well.
