### ISSUE TITLE
Adding support for Aeon v8 k12 POW

### ISSUE THREAD

**Issue by BigslimVdub** [dvandal/cryptonote-nodejs-pool#488]
Hello,

Aeon will be forking to k12 POW on the next network upgrade. Will you offer official pool software support for this? We currently have Cryptonote-universal set up and it seems to be working ok. Since K12 will have substantially higher hash rates than Crypto-night light the diff settings need to be set for higher values on specific ports compared to cryptonight. 

I noticed many pool operators use NodeJs based pools including this version. Thanks for the support.

**Comment by muscleman** [comment]
Yes, believe i contacted you on discord. we'll pick up and get a solution for this

**Comment by muscleman** [comment]
Added config_examples/aeon-k12.

Should be good.

**Comment by BigslimVdub** [comment]
Thank you for your support.
