### ISSUE TITLE
support integratedaddress

### ISSUE THREAD

**Issue by minhnt812018** [dvandal/cryptonote-nodejs-pool#49]
Hi, could you please build a new version to support integrate address like DERO wallet 
 in https://stocks.exchange
this is wallet from stocks.exchange:
dERimZr1Af9CjQCCUTZQakNLqgDPQCnMfUdTH5fLWoBAg3JnU79jNkFarUVGqwJc6R5NW2qLE5iuocmSHgQWgHop47bTJCr1LvK7Bf2A78pJU

**Comment by dvandal** [comment]
The code has been updated to better handle integrated address and a new setting "intAddressPrefix" has been added to pool server configuration. 

In your case, for dero you should set:

```
    "poolServer": {
        "intAddressPrefix": 659160,
```

**Comment by Chinsusu** [comment]
@dvandal How about this 
LPgFQMuQ7ZXDEnKR9V28ugBk8GoiSa2sxV4zju8YXG8Tii7EZbSPJMDcdTPcsiWBFeYLGjvhjFDxf1QazFxtoJYwUyArBDrfLmV8ymf8DU
Loki bro
