### ISSUE TITLE
I have issue with hvs1j started wallets

### ISSUE THREAD

**Issue by mk148a** [dvandal/cryptonote-nodejs-pool#490]
Hi there,
This pool is work with hvxy3BWhzEV19J8pijvqnrUkeAeP8Rvr4XyfDMGJcarhbL15KgYKM1hN7kiHMu3fer5k8JJ8YRLKCahDKFgLFgJM84YtzPkJm5 addresss. But when i try hvs1j3FZjc1MbSs7c4evMPCEahNaKzXyvKgoMVkTtSSK5Dgn9aKCEBvRyC2iq2ki8BRdHS6Api1PuCYFX6yy5aqf52PTu9JgUc address its getting error:
 Invalid address used for login (prefix: 1235316): hvs1j3FZjc1MbSs7c4evMPCEahNaKzXyvKgoMVkTtSSK5Dgn9aKCEBvRyC2iq2ki8BRdHS6Api1PuCYFX6yy5aqf52PTu9JgUc

How to fix it?

**Comment by muscleman** [comment]
"IntAddressPrefix":1235316

**Comment by muscleman** [comment]
in the config.json file
