### ISSUE TITLE
DERO Pool - Malformed message when miners connet

### ISSUE THREAD

**Issue by mannie65** [dvandal/cryptonote-nodejs-pool#492]
Just setup a DERO pool - using Cryptonight, 0, 0 for the settings - but miners get a Malformed message when they connect.

Any ideas - what am i missing ?

    "daemonType": "default",
    "cnAlgorithm": "cryptonight",
    "cnVariant": 0,
    "cnBlobType": 0,

**Comment by muscleman** [comment]
yeah, you'll need a custom version of dvandal that used kecaak

**Comment by muscleman** [comment]
i have this sitting around some place, might fish it out

**Comment by mannie65** [comment]
@muscleman That would be great if you could - ill send through a small donation :-)
