### ISSUE TITLE
"Bad hash from miner" when turtlecoin

### ISSUE THREAD

**Issue by tatarenko** [dvandal/cryptonote-nodejs-pool#497]
So i made this steps:
1) Got fresh ubuntu 18.04 (also tryed 19.04).
2) Install turtlecoin daemon as described in turtlecoin github README.
3) Made everything step by step as described in README of this pool.
4) Copy turtlecoin.json from config-example folder.
5) Put my address in config.

Pool is starting but got 
```
2019-07-22 03:16:13 [pool] (Thread 3) Mining pool algorithm: cryptonight_pico variant 2, Hard fork version: 1
2019-07-22 03:16:13 [pool] (Thread 3) Bad hash from miner TRTL{miner TRTL address}@::ffff:xx.xxx.xxx.xx
2019-07-22 03:16:13 [pool] (Thread 3) Share trust broken by TRTL{miner TRTL address}@::ffff:xx.xxx.xxx.xx

```

And 
```
[2019-07-22 04:16:08] : New block detected.
[2019-07-22 04:16:13] : Result rejected by the pool.
[2019-07-22 04:16:14] : Result rejected by the pool.

```

**Comment by muscleman** [comment]
what miner and what algo.

**Comment by tatarenko** [comment]
xmr-stak 
"currency" : "turtlecoin"
It mine perfectly on other pools, dvandal based included.

**Comment by muscleman** [comment]
hmm, try pinning the monero ocean packages in package.json to a version say last week.

**Comment by muscleman** [comment]
one other thing. you got the config from the config_examples directory of the turtle-chukwa directory?

**Comment by muscleman** [comment]
nvm, i see cryptonight_pico

**Comment by tatarenko** [comment]
ok, this way does not work:
```
        "cryptoforknote-util": "git://github.com/MoneroOcean/node-cryptoforknote-util.git#v4.1.0",
        "cryptonight-hashing": "git://github.com/MoneroOcean/node-cryptonight-hashing.git#v10.0.0",

```

This way does not work too:
```
        "cryptoforknote-util": "git://github.com/MoneroOcean/node-cryptoforknote-util.git#v4.0.2",
        "cryptonight-hashing": "git://github.com/MoneroOcean/node-cryptonight-hashing.git#v9.0.2",
```
)

**Comment by muscleman** [comment]
i believe this was a bad miner
