### ISSUE TITLE
Daemon  Unauthorized error 401 

### ISSUE THREAD

**Issue by mostafa-helmy13** [dvandal/cryptonote-nodejs-pool#498]
when running pool i receive error code 401 Unauthorized  json request to monero daemon 
i use rpc login to monerod daemon and wallet-rpc daemon 

in my pool config i used this config 

 "daemon": {
        "host": "127.0.0.1",
        "port": 18081,
	"username" : "mem" ,
	"password" : "xxx"
    },

    "wallet": {
        "host": "127.0.0.1",
        "port": 28081 ,
	"username" : "mem",
	"password" : "xxx"
    },

is something wrong in config !!

**Comment by mostafa-helmy13** [comment]
note : when i remove login it works

**Comment by muscleman** [comment]
Correct. The username and password implementation sucks and is currently under testing with a new rpc package

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
