### ISSUE TITLE
Hey bytecoin walletd new api

### ISSUE THREAD

**Issue by Unkownman086** [dvandal/cryptonote-nodejs-pool#499]
Hello i am trying to make merged mining pool with BCN and in your payment processor you are using SendTransaction (tx details) instead send_transaction (binary tx) and your pool isn't making payments on bytecoin please fix it. You probbably still have old walletd api.

You can find how new api works here: https://documenter.getpostman.com/view/5281660/RztfvWnb?version=latest#c3894df3-c6e4-40e0-ab90-6d7d35a11f46

**Comment by muscleman** [comment]
new directory in config_examples, try it
