### ISSUE TITLE
Payment Processor Issue - Appending workers Name

### ISSUE THREAD

**Issue by sexontoastGraft** [dvandal/cryptonote-nodejs-pool#5]
│2018-03-03 22:54:04.240 [RPC0]  ERROR   net.dns src/common/dns_utils.cpp:407    wrong address: G6VA4BGzR5r6tFfXxJMu5xVThXfsNPDTt1aSLJssv59Q1Nqvf23j7XHNybUy4e7jGT9g3Ga4FhuCJJV45nwnehXyPeyYM5t+gaming_pc

It seems to be appending the workers name for payment, anyone know how I can fix it ?

**Comment by dvandal** [comment]
I had an issue with workers by name feature in 1.2.0 that has been fixed in 1.2.1 the next day. Can you contact me directly by email at daniel@vandal.ca or on Telegram (look for " dvandal " / Daniel Vandal) ?

**Comment by dvandal** [comment]
I added a fix in 1.2.2 version to fix the payments issue and workers balance.
