### ISSUE TITLE
Payment error SUMO

### ISSUE THREAD

**Issue by Cideg** [dvandal/cryptonote-nodejs-pool#500]
Hi, when using a payment ID, a payout is not possible. the error occurs only with SUMO. Does somebody has any idea?

[payments] Error with transfer RPC request to wallet daemon {"code":-5,"message":"Payment id has invalid format: \"1f5069983ab2ea0f\", expected 64 character string"}

**Comment by muscleman** [comment]
i enforce 16 characters.
https://github.com/dvandal/cryptonote-nodejs-pool/blob/master/lib/pool.js#L589

looks like you need 64 characters

**Comment by ossii79** [comment]
Indeed, same as monero and other updated forks its now 64 chars. However the whole payment ID system is being removed, start using integrated addresses.

**Comment by muscleman** [comment]
so do we need a flag in the config to turn off paymentid
