### ISSUE TITLE
Reject Shares from xmrig-proxy v3.1.1

### ISSUE THREAD

**Issue by Sevilla404** [dvandal/cryptonote-nodejs-pool#509]
The latest xmrig-proxy version its being rejecting shares from the pool..
2019-09-25 13:50:02 (Thread 8) Bad hash from miner .. .. . ...
2019-09-25 13:50:02 (Thread 8) Share trust broken by .. .. . .. . . .

**Comment by muscleman** [comment]
Might need to take a look

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by Sevilla404** [comment]
Maybe could be from the 3.0.0 release:

Changelog...
Algorithm cn/msr renamed to cn/fast.

**Comment by muscleman** [comment]
![xmrig-proxy](https://user-images.githubusercontent.com/4632339/66018631-87c3be80-e4a5-11e9-8be9-7f961d97b413.PNG)

**Comment by muscleman** [comment]
so the above is an image of xmr-stak communicating with xmrig-proxy and successfully sending shares to test2.smartcoinpool.net my sumokoin test pool.

**Comment by muscleman** [comment]
![testpool](https://user-images.githubusercontent.com/4632339/66018740-e4bf7480-e4a5-11e9-85be-fc8652dad176.PNG)

**Comment by muscleman** [comment]
3.2 works

**Comment by Sevilla404** [comment]
Yes.. Tested  over fresh install.  Need to specify new criptonight3 and
variant 9 for masari.
