### ISSUE TITLE
MASARI ALGO Not Showing Well at Example Webpage

### ISSUE THREAD

**Issue by Sevilla404** [dvandal/cryptonote-nodejs-pool#510]
The example config.json for masari its configurated for use cnVariant 9, but in the "getting_started" example webpage its not exist that option to show the real Algo running:

   if (cnVariant === 1) {
                algorithm = 'Cryptonight (Monero v7)';
                xmrstakAlgo = 'cryptonight_v7';
            } else if (cnVariant === 3) {
                algorithm = 'Cryptonight (Stellite v7)';
                xmrstakAlgo = 'cryptonight_v7_stellite';
            } else if (cnVariant === 4) {
                algorithm = 'Cryptonight Fast (Masari)';
                xmrstakAlgo = 'cryptonight_masari';
     

            } else {
                algorithm = 'Cryptonight (Original)';
                xmrstakAlgo = 'cryptonight';
            }
        }

Need to add cnVariant 9 or change cnVariant from 4 to 9

       } else if (cnVariant === 9) {
                algorithm = 'Cryptonight Fast (Masari)';
                xmrstakAlgo = 'cryptonight_v8_half';

**Comment by hypeboard** [comment]
make a pull request

**Comment by croniccorey** [comment]
I am adding a handful of missing algo info in coming PR.

**Comment by croniccorey** [comment]
Addressed in #521
