### ISSUE TITLE
is it possible to get through api only the last block, the reward for it and the number of hashes? 

### ISSUE THREAD

**Issue by xmrschool** [dvandal/cryptonote-nodejs-pool#511]
greetings! Such a question: is it possible to get through api only the last block, the reward for it and the number of hashes? and where can I read about all the possible options for requests to api pool?

**Comment by trasherdk** [comment]
You have to understand, this is open source software. People will submit pull requests, but accepted, or not, they will never bother to document whatever changes they propose, or actually get adopted.
It's a case of `use the source`, until someone actually spend the time to document the software.

**Comment by muscleman** [comment]
i believe if you set this

https://github.com/muscleman/cryptonote-nodejs-pool/blob/master/config_examples/arqma.json#L139

to 1 this may get you want you want.
