### ISSUE TITLE
Developer donations...

### ISSUE THREAD

**Issue by croniccorey** [dvandal/cryptonote-nodejs-pool#517]
I notice in commit 005de99 the devDonation option is killed and a mandatory 0.2% donation is added with no mention of this in commit message, i also notice this donation is hidden from website frontend and logs.

All curious refer to commit https://github.com/funwithcrypto/cryptonote-nodejs-pool/commit/fab32e93af5ed77e009be64eb7f889e7a03d80ba, It revives the devDonation setting with a minimum 0.2% donation.

**Comment by muscleman** [comment]
So u thought it neccessary to share a way around the dev fee?
Guess your also saying you dont want solo mining. Merge mining support added too.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by croniccorey** [comment]
No, as a developer myself i believe you deserve something for your work, i just think you should be upfront about this sort of change, not bury it in a unrelated commit.. docs mention nothing about it and it misleads people to believe the option is configurable in json as the original developer made it.

Thanks for your continued work on this project.

**Comment by croniccorey** [comment]
@muscleman I have prepared a PR that deals with donations a bit more properly and allows a donation greater then 0.2% to be configured at users will.

I did not intend to cheat your donations or show people how, your work on this project is appreciated by meny including myself.

**Comment by trasherdk** [comment]
@croniccorey Good catch. Thank you.

@muscleman This kind of behavior is **NOT** cool. When dealing with open source software, one should be able to trust, that contributors does not implement hidden features.

In general, users of open source software do appreciate developers work, and don't mind donating to the principal stewards. Something like this will surface eventually, when users start noticing that numbers don't match up.

**Comment by dvandal** [comment]
Developper fees should optional, enforcing donations is not the way that we should go, this is open source software and I don’t accept this. I will check the commits.

**Comment by trasherdk** [comment]
Maybe enforcing PR review? Limiting who can do merges?

**Comment by croniccorey** [comment]
> Maybe enforcing PR review? Limiting who can do merges?

Indeed a better review process could avoided this kinda thing form happening.
