### ISSUE TITLE
IPBC problem

### ISSUE THREAD

**Issue by Chinsusu** [dvandal/cryptonote-nodejs-pool#52]
Hi, would you pls help me to config for IPBC?
Idk how to do that
Thanks

**Comment by Chinsusu** [comment]
I did, following the ipbc config from their pool. But which any algo I chose, when the miner connected, It said: Error: Failed to parse block

**Comment by uekdyr** [comment]
Failed to parse block has to do wether your daemon is synced with the blockchain or not.

Check their explorer and confirm that your daemon is on the same "Height".

**Comment by Chinsusu** [comment]
daemon is fully synced. I currently running  cryptonote-forknote-pool. I use this daemon to run cryptonote-nodejs-pool. I confirm that daemon is running fine.

**Comment by Chinsusu** [comment]
@dvandal IPBC is different. I try to use all of these algo but doesnt work.
http://italo.asiapool.space/
this is my pool using yours. very good. 
this pool use yours too but I cant ask him how.
http://ipbc.allpool.io/

**Comment by dvandal** [comment]
Hi,

Please upgrade to lastest release 1.3.2 and set "cnAlgorithm" to "cryptonight_light" and "cnVariant" to "2" for IPBC.

**Comment by Chinsusu** [comment]
@dvandal
 Error: Failed to parse block
    at Error (native)
    at Object.BlockTemplate.nextBlob (/root/pool/lib/pool.js:154:29)
    at Object.Miner.getJob (/root/pool/lib/pool.js:330:41)
    at handleMinerMethod (/root/pool/lib/pool.js:464:28)
    at handleMessage (/root/pool/lib/pool.js:828:13)
    at Socket.<anonymous> (/root/pool/lib/pool.js:882:25)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:153:18)
    at Socket.Readable.push (_stream_readable.js:111:10)
it doesnt work bro

**Comment by Chinsusu** [comment]
remove node_modules, npm update. it works. thanks bro

**Comment by dvandal** [comment]
Great! :)

**Comment by Chinsusu** [comment]
I get this problem again when a miner connect to the pool. 
everything is ok if there is no miner
Error: Failed to parse block
