### ISSUE TITLE
New config.json for monero next algo: randomX

### ISSUE THREAD

**Issue by Tupeipei** [dvandal/cryptonote-nodejs-pool#522]
Is there any example for monero next algo randomx ？

**Comment by trasherdk** [comment]
After the latest (unreviewd) mass merges, I have no clear idea of what state the code is in.
But, a look at the source code, it looks like the configuration aligns with xmr-stak and MoneroOcean.

**Comment by croniccorey** [comment]
I think your best bet would be to follow the example loki config (it uses a randomX algorithm variant), adjust the values based on monero source code, wiki for this repo has some information on preparing a new coin.

Config For monero you want cnVariant 0 and algo hold be randomx.

If I have time and no one else does.. I'll PR a config for new monero.

**Comment by muscleman** [comment]
Well trasherdk I pushed my codebase that has 6 month of production testing and numerous hours of test environment testing.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by muscleman** [comment]
Code has always used monero ocean hashing  packages. No changes there.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by muscleman** [comment]
changed monero.json to randomx.  need to confirm variant type

**Comment by Tupeipei** [comment]
I just figured out that config for monero new algo is:
cnAlgorithm: randomx
cnVariant: 0
cnBlobType:0

But my hashrate is too smal for mining. So I am not guaranteed to be correct.
