### ISSUE TITLE
ITNS Cryptonight Variant Issue

### ISSUE THREAD

**Issue by mannie65** [dvandal/cryptonote-nodejs-pool#53]
I have deployed this pool for use with Intensecoin - using variant 1 initially, and using the V4 forked daemon. It worked fine for almost a day , when it started rejected miners shares and BAD. Restarting all components did not solve the issue - but changing the variant back to 0 and restarting the pool did. Shares accepted - but not sure it will be able to submit a solved block.

Any ideas - anyone else seeing this ?

**Comment by uekdyr** [comment]
Have you got the new Daemon, think they updated it yesterday or something?

**Comment by uekdyr** [comment]
Could you post your coinconfig? Don't know what could be wrong then :/

And your daemon height is the same as itns explorer says?

**Comment by PsychoSterope** [comment]
Do you need to adjust the convertBlob?

**Comment by mannie65** [comment]
@PsychoSterope  - I don't think so as this release has a Coin Variant variable in config.json to allow you to define the type. Checked pool.js and can't see the requirement to change  although I could be wrong.

**Comment by mannie65** [comment]
@uekdyr - miners updated - support monero7 and have been tested and run fine against Graft forked pool  with no issues. Yes daemon height seems fine - its in sync with explorer and main pool. What part of the coinconfig would you like to see ?

**Comment by PsychoSterope** [comment]
@mannie65 It does, I had to change it for my Masari pool.

**Comment by PsychoSterope** [comment]
@mannie65 Ok, just suggested it because I had to change the Blob for the new Masari fork.

**Comment by dvandal** [comment]
For Masari the "moneroVariant" setting was deprecated and replaced by "cnVariant: 1"

**Comment by PsychoSterope** [comment]
Hmm, I had to manually change the Blob, otherwise all the blocks after 170,000 were rejected.

**Comment by dvandal** [comment]
What did you change?

**Comment by PsychoSterope** [comment]
var cn_variant = convertedBlob[0] >= 7 ? 1 : 0;
became
var cn_variant = convertedBlob[0] >= 5 ? 4 : 0;

**Comment by dvandal** [comment]
settings cnVariant to "1" should have worked

**Comment by PsychoSterope** [comment]
I think I missed that setting, where should I have seen it?

**Comment by dvandal** [comment]
In your config.json

**Comment by PsychoSterope** [comment]
OK.. I am blind >.< I have been focused on trying to figure out how to use the Telegram and Mailgun settings and missed that one.

**Comment by PsychoSterope** [comment]
Ok, Now I understand why I missed it. I downloaded 1.3.0 last night and this is what is in the masari.json example:

"coin": "masari",
    "symbol": "MSR",
    "coinUnits": 1000000000000,
    "coinDifficultyTarget": 120,
    "cnAlgorithm": "cryptonight",
    "moneroVariant": false,

**Comment by dvandal** [comment]
Yes was fixed 1 hour ago.

**Comment by PsychoSterope** [comment]
Oh LOL. I will update later tonight. You're awesome! Thanks for the pool !
