### ISSUE TITLE
Bad hash from miner - monero

### ISSUE THREAD

**Issue by dantenous** [dvandal/cryptonote-nodejs-pool#533]
I have a problem with:

Mining pool algorithm: cryptonight variant 13, Hard fork version: 11

    "daemonType": "default",
    "cnAlgorithm": "cryptonight",
    "cnVariant": 13,
    "cnBlobType": 0,
    "includeHeight": true,

miner - XMRig/5.0.1 -  cpu  rejected (0/1) diff 25000 "Rejected share: invalid result"

**Comment by dantenous** [comment]
I check it. Wownero have same error.

**Comment by croniccorey** [comment]
Monero uses RandomX, Wownero uses RandomWOW, I have Multiple pools running without issue on latest release.. Make sure configs you use are upto date some are not.

**Comment by dantenous** [comment]
Ok. A I check it again. Which pool have you? Dvandal or Muscleman?

**Comment by croniccorey** [comment]
I use a fork of Dvandal repo, https://github.com/funwithcrypto/cryptonote-nodejs-pool .. you can checkout my configs and use them to update yours.

**Comment by muscovydux** [comment]
Is your monero pool working? It appears to be down. I am having a hell of a time getting my monero pool up. Everything SEEMS to work perfectly except I am getting connection rejections within xmrig for all miners attempting to connect. I don't know if it's related but it was working perfectly fine prior to randomx and I have changed none of my firewall rules.

**Comment by VanGrx** [comment]
> I have a problem with:
> 
> Mining pool algorithm: cryptonight variant 13, Hard fork version: 11
> 
> ```
> "daemonType": "default",
> "cnAlgorithm": "cryptonight",
> "cnVariant": 13,
> "cnBlobType": 0,
> "includeHeight": true,
> ```
> 
> miner - XMRig/5.0.1 - cpu rejected (0/1) diff 25000 "Rejected share: invalid result"

Try adding 
`hash = cryptoNight(convertedBlob, Buffer.from(blockTemplate.seed_hash, 'hex'), cnVariant);`
instead of
`hash = cryptoNight(convertedBlob, Buffer.from(blockTemplate.seed_hash, 'hex'));`
in lib/pool.js in function processShare.
As I think this is a bug in that part of the code.

**Comment by muscleman** [comment]
try cnvariant 0, blobtype 0, cnAlgorithm randomx

**Comment by muscleman** [comment]
thanks for spotting that VanGrx
