### ISSUE TITLE
Does anyone actually have a RandomX pool going yet?

### ISSUE THREAD

**Issue by muscovydux** [dvandal/cryptonote-nodejs-pool#534]
I have everything seemingly up and running except miners cannot connect to the pool. The mining ports will not accept any connections and I am out of ideas at this point. The pool was running just fine prior to the RandomX fork earlier today and now, no miners can connect.

Any insight would be very much appreciated.

**Comment by croniccorey** [comment]
Ive tried RandomXL, Loki pool on latest https://funwithcrypto.tk/loki code.. RandomX should be pretty much the same could you provide a copy of your config?

**Comment by rplant8** [comment]
current version work, 2 found xmr blocks on new pool
