### ISSUE TITLE
bug?

### ISSUE THREAD

**Issue by drorow** [dvandal/cryptonote-nodejs-pool#537]
1.Can't show child CURRENT EFFORT,child CONNECTED MINERS on home pages.
2.Can't show child Worker Statistics on worker_stats pages.

**Comment by drorow** [comment]
https://btcmz.miningpool.fun/

**Comment by muscleman** [comment]
do you have your child coins api running and configured to access the same redis database?

**Comment by drorow** [comment]
Yes,I do.It can show the child coin's network states correctly.Another issue that I found the child coins can submit shares but can't find blocks.Thanks.

**Comment by muscleman** [comment]
What coins

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by drorow** [comment]
parent: BTCMZ
child: NINJA

**Comment by muscleman** [comment]
is anyone else doing that combination of coins

**Comment by drorow** [comment]
Yes,https://argon2.minercountry.com/

**Comment by muscleman** [comment]
i have no idea

**Comment by drorow** [comment]
It's ok.Thanks.
