### ISSUE TITLE
Almost all blocks get rejected when mining Talleo...

### ISSUE THREAD

**Issue by mtl1979** [dvandal/cryptonote-nodejs-pool#539]
Due to Talleo's unique block validation rules, nodejs-pool and almost all mining pool software have small logic flaw that results in almost all blocks getting rejected on pools with small hashing power.

Around line https://github.com/dvandal/cryptonote-nodejs-pool/blob/master/lib/pool.js#L1283 where it fails to submit block to node daemon, it should invalidate the block template and send a new job to miners as the block template is most likely stale. This is due to logic flaw when caching the block template and blindly comparing just block heights. As rejected blocks don't increase block height, it will never invalidate the block template unless some other pool or solo miner successfully solves a block.

**Comment by muscleman** [comment]
so whats your fix?

**Comment by mtl1979** [comment]
@muscleman Like I said, only fix that really works is to set the cached block template to null as that forces the pool to refresh it.

**Comment by muscleman** [comment]
But blocktemplate creation is driven by a thread that queries the daemon. Is removing the blocktemplate correct when [n] number of miners will also be submitting their solutions.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by muscleman** [comment]
Disposing of the current block would mean no further jobs for miners until the next block is created by the daemon and pulled into the pool software

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by mtl1979** [comment]
@muscleman in forknote-pool based software it will explicitly send new job after the previous one is discarded. This is same behavior as when it retargets the miner difficulty.

I'm not sure if it should be enabled always or a configuration option as I have never used nodejs-pool myself because honestly forknote-pool works a lot better with newer Bytecoin-based coins. But bigger pools use it, because it can support multiple coins and merge mining.

**Comment by mtl1979** [comment]
@PorkyForky Can you explain how this can be fixed in nodejs-pool?

**Comment by muscleman** [comment]
waiting pr or explanation of pr

**Comment by mtl1979** [comment]
We added num_transactions field in the RPC reply when querying for new block template. If block height is same but that field changes from zero to non-zero, the block template is refreshed and new job is sent to miner.

**Comment by croniccorey** [comment]
Fixed in PR #545
