### ISSUE TITLE
bug workername

### ISSUE THREAD

**Issue by minhnt812018** [dvandal/cryptonote-nodejs-pool#54]
the worker with special char cannot show in Worker status, please view a 
![bug](https://user-images.githubusercontent.com/37006960/39526999-8fe52358-4e4a-11e8-8270-a7864efb0adc.png)
picture

**Comment by minhnt812018** [comment]
thank you for you reply, i know how to use wallet and worker name. this is a bug when i try to use some special char in woker and in Worker statistics can not show right worker name and last share submit

**Comment by dvandal** [comment]
I added a patch to accept - and _ characters in worker name.
