### ISSUE TITLE
Bad hash submitted on CN/R

### ISSUE THREAD

**Issue by ilie1988** [dvandal/cryptonote-nodejs-pool#540]
i am updating the pool and now CN/R is not working anymore on italocoin, you think you could take a look? Thanks

![image](https://user-images.githubusercontent.com/56231050/70716442-ae477680-1cec-11ea-8a5f-e705e670f0f8.png)

**Comment by muscleman** [comment]
ain't italocoin randomx

**Comment by ilie1988** [comment]
Hello?

**Comment by muscleman** [comment]
think i got the config changed to support the new pool format. try again

**Comment by ilie1988** [comment]
> think i got the config changed to support the new pool format. try again

Unfortunately still won't work, i still get "Bad hash from miner ipPJ..."

**Comment by muscleman** [comment]
okay, found and fixed the bug.
you can test it here.
https://multi-miner.smartcoinpool.net/
