### ISSUE TITLE
Lethean

### ISSUE THREAD

**Issue by swa74** [dvandal/cryptonote-nodejs-pool#544]
"cnAlgorithm": "",
    "cnVariant": ,
    "cnBlobType": ,

What values to put in config.json servers for Lethean

**Comment by swa74** [comment]
Can from whom there is ready lethean.json ?

**Comment by jvmatamu** [comment]
`    "cnAlgorithm": "cryptonight",
    "cnVariant": 13,
    "cnBlobType": 0,`

**Comment by swa74** [comment]
Thank you very much
