### ISSUE TITLE
No subordinate API transmission

### ISSUE THREAD

**Issue by Danniel0815** [dvandal/cryptonote-nodejs-pool#547]
Hello I started a merge pool, both coins find coins. But for the child coin I don't get an API transfer.

I saved the port in the config for both.
parentCoin = api port 8989
the demon also shows this and transfers the data. [api] API started & listening on 0.0.0.0 port 8989

for the child coin I have deposited it as indicated: "api": "https://your.pool.host/apiMerged1",

"http: //177.xxx.xx.xx/8333"

but i don't get any transmission on this port. do I have to do anything else?

**Comment by muscleman** [comment]
Blockunlocker and payments are done by second pool module running child config with pool server disabled.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by Danniel0815** [comment]
Thank you I tried, but I think the problem lies in the redis record.

 "childPools" : [{"poolAddress":"XXXXXXXXXXX",
                     "intAddressPrefix": null,
                     "coin": "ELPH",


mergeconfig:    "coin": "ELPH"

however, there is no recording or playback
The api probably won't find any recorded data,

**Comment by muscleman** [comment]
post your configs

**Comment by Danniel0815** [comment]
@Muscleman thx.

```
{
     "poolHost": "167.86.100.xxx",

    "coin": "Worktips",
    "symbol": "WTIP",
     "coinUnits": 100000000,
    "coinDecimalPlaces": 4,
    "coinDifficultyTarget": 120,
    "blockchainExplorer": "http://explorer2.elphyrecoin.xyz/?hash={id}#blockchain_block",
    "transactionExplorer": "http://explorer2.elphyrecoin.xyz/?hash={id}#blockchain_transaction",

    "daemonType": "default",
    "previousOffset": null,
    "cnAlgorithm": "cryptonight_pico",
    "isRandomX": false,
    "cnVariant": 0,
    "cnBlobType": 5,
    "includeHeight": false,
    "includeAlgo": false,

    "logging": {
        "files": {
            "level": "info",
            "directory": "logs",
            "flushInterval": 5
        },
        "console": {
            "level": "info",
            "colors": true
        }
    },

    "childPools": [{ "poolAddress": "elphxxxxxxxxxxxxxxxxxxxxxx",
                     "intAddressPrefix": null,
                     "coin": "ELPH",
                     "childDaemon": {
                            "host": "127.0.0.1",
                            "port": 11246
                     },
                     "pattern": "^ELPH",
                     "blockchainExplorer": "http://explorer2.elphyrecoin.xyz/?hash={id}#blockchain_block",
                     "transactionExplorer": "http://explorer2.elphyrecoin.xyz/?hash={id}#blockchain_transaction",
                     "api": "167.86.100.xxx:8125",
                     "enabled": true
                   }
    ],

    "poolServer": {
        "enabled": true,
        "mergedMining": true,
        "clusterForks": "auto",
        "poolAddress": "Wtmab5QwEit7PwNDWyHT4ZRSsxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
        "intAddressPrefix": null,
        "blockRefreshInterval": 1000,
        "minerTimeout": 900,
        "sslCert": "cert.pem",
        "sslKey": "privkey.pem",
        "sslCA": "chain.pem",
        "ports":
````

**Comment by Danniel0815** [comment]
for API:  start init.js -config=config_elph.json


 "coin": "ELPH",
    "symbol": "ELPH",
    "coinUnits": 100000000,
    "coinDecimalPlaces": 4,
    "coinDifficultyTarget": 120,

    "cnAlgorithm": "cryptonight_pico",
    "cnVariant": 2,
    "cnBlobType": 2,

    "logging": {
        "files": {
            "level": "info",
            "directory": "logs",
            "flushInterval": 5
        },
        "console": {
            "level": "info",
            "colors": true
        }
    },

    "poolServer": {
        "enabled": false,
        "clusterForks": "auto",
        "poolAddress": "xxxxxxxxxxxxxxxxx",

XXXXXXXX

"api": {
        "enabled": false,
        "hashrateWindow": 600,
        "updateInterval": 5,
        "bindIp": "0.0.0.0",
        "port": 8125,
        "blocks": 30,
        "payments": 30,
        "password": "your_password",
        "ssl": false,
        "sslPort": 8888,
        "sslCert": "./cert.pem",
        "sslKey": "./privkey.pem",
        "sslCA": "./chain.pem",
        "trustProxyIP": true
    },

**Comment by muscleman** [comment]
so here's my nginx config file.
`server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name multi-miner.smartcoinpool.net www.multi-miner.smartcoinpool.net;

    # Use the Lets Encrypt certificates
    ssl_certificate /etc/letsencrypt/live/aeon.smartcoinpool.net-0001/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/aeon.smartcoinpool.net-0001/privkey.pem; # managed by Certbot

    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    # Set files location
    root /var/www/geem/;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }

    location ~ ^/apiMerged1/(.*) {
        proxy_pass http://127.0.0.1:9117/$1$is_args$args;
    }

    location ~ ^/api/(.*) {
        proxy_pass http://127.0.0.1:8217/$1$is_args$args;
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
`
and the corresponding child coins entry.

`    "childPools": [
                  {"poolAddress":"QQQ1RhC6h1pBWA8vGoD7VyTWhfRsBosvrR6HkWZzGuHy1VbqaYeEWf52VNFCv1ScXQD7hYJYGhTRYWKqLd2iZvPx4neG6VMg96",
                     "intAddressPrefix": 1897867,
                     "coin": "Krypton",
                     "childDaemon": {
                            "host": "127.0.0.1",
                            "port": 12888
                       },
                     "pattern": "^QQQ",
                     "blockchainExplorer": "https://explorer.kryptonchain.org/?hash={id}#blockchain_block",
                     "transactionExplorer": "https://explorer.kryptonchain.org/?hash={id}#blockchain_transaction",
                     "api": "https://multi-miner.smartcoinpool.net/apiMerged1",
                     "enabled": true
                    }
                  ],
`

**Comment by muscleman** [comment]
note the ^/apiMerged1 match the "api": "https://multi-miner.smartcoinpool.net/apiMerged1" so calls to https://multi-miner.smartcoinpool.net/apiMerged1 are directed by nginx to 127.0.0.1.8217

**Comment by muscleman** [comment]
so did you fix this?

**Comment by TheDevMinerTV** [comment]
Any update on this?
