### ISSUE TITLE
turtlecoin fee-per-byte payment system

### ISSUE THREAD

**Issue by copbidi** [dvandal/cryptonote-nodejs-pool#558]
What changes do I need to make to the turtlecoin.json file for the fee-per-byte system?

**Comment by muscleman** [comment]
looks like it we will use the lazy expensive version until a patch is written.

https://blog.turtlecoin.lol/archives/migrating-from-fixed-fees-to-fee-per-byte-a-developers-guide/

**Comment by copbidi** [comment]
It is saying
**However, this is not the cheapest way. In addition, if the minimum fee per byte is increased in a later fork, you will have to update your code again. Booooo!**

I understand that this way we will have to use the highest payment fee (2430 TRTL) for all payments.

Can you do **the cheaper way**?

**Comment by muscleman** [comment]
so i started working on a change in the payment-abstractions branch
