### ISSUE TITLE
Worker Statistics "Worker Name" is undefined on website

### ISSUE THREAD

**Issue by RoggyDog** [dvandal/cryptonote-nodejs-pool#562]
I'm setting up my 4th pool and am having some problems with the pool website working correctly. The first 3 went fine, but this XEQ pool is behaving badly. I have 2 workers connected but the Worker Statistics page doesn't display the individual workers. I've reinstalled multiple versions of the pool but always have this issue. I've run out of ideas on how to fix it.

![workerStats](https://user-images.githubusercontent.com/35351263/72480810-96b94d00-37c6-11ea-8346-b64389ed08a3.PNG)

The charts_crash.log shows...

2020-01-15 18:35:34
TypeError: values.forEach is not a function
    at storeCollectedValue (/home/xeqpool/XEQ-pool/lib/charts.js:101:9)
    at /home/xeqpool/XEQ-pool/lib/charts.js:137:4
    at fn (/home/xeqpool/XEQ-pool/node_modules/async/lib/async.js:746:34)
    at /home/xeqpool/XEQ-pool/node_modules/async/lib/async.js:1213:16
    at /home/xeqpool/XEQ-pool/node_modules/async/lib/async.js:166:37
    at /home/xeqpool/XEQ-pool/node_modules/async/lib/async.js:706:43
    at /home/xeqpool/XEQ-pool/node_modules/async/lib/async.js:167:37
    at /home/xeqpool/XEQ-pool/node_modules/async/lib/async.js:1209:30
    at /home/xeqpool/XEQ-pool/lib/charts.js:301:3
    at /home/xeqpool/XEQ-pool/lib/market.js:69:46

**Comment by muscleman** [comment]
is your miner supplying a workername?

**Comment by muscleman** [comment]
try pulling latest master.
i just made a fix 1605ea2277a01d585bfd7c74c23ff5157bd623f6

**Comment by RoggyDog** [comment]
Yeah, I'm supplying worker name. I'll try fix and let you know how it works out.

**Comment by RoggyDog** [comment]
Using xmr-stak I put worker name in rig_id, pool_password and after wallet addy as .workername, it still shows as undefined. The pool console shows ...
2020-01-16 08:27:58 [charts] worker_hashrate:<my wallet address>~undefined chart collected value 12633. Total sets count 133

and I still get this in charts_crash.log...
2020-01-16 08:13:56
TypeError: values.forEach is not a function
    at storeCollectedValue (/home/xeqpool/XEQpool/lib/charts.js:101:9)
    at /home/xeqpool/XEQpool/lib/charts.js:137:4
    at fn (/home/xeqpool/XEQpool/node_modules/async/lib/async.js:746:34)
    at /home/xeqpool/XEQpool/node_modules/async/lib/async.js:1213:16
    at /home/xeqpool/XEQpool/node_modules/async/lib/async.js:166:37
    at /home/xeqpool/XEQpool/node_modules/async/lib/async.js:706:43
    at /home/xeqpool/XEQpool/node_modules/async/lib/async.js:167:37
    at /home/xeqpool/XEQpool/node_modules/async/lib/async.js:1209:30
    at /home/xeqpool/XEQpool/lib/charts.js:301:3
    at /home/xeqpool/XEQpool/lib/market.js:69:46

**Comment by muscleman** [comment]
prolly a valid bug that come from this pools being re-purposed as a merged mining pool and always expecting the worker name from the password field after the secondary coins address

**Comment by RoggyDog** [comment]
I always put worker name in rig_id before, password was always just x, so that makes sense.

**Comment by croniccorey** [comment]
You need to have '@' before password since merged mining support to have it recognized.. If you want worker name 'x' then you should have password field set as '@x'.

**Comment by RoggyDog** [comment]
The @ before is new to me, but in xmr-stak I made...
"rig_id": "",
"pool_password": "@Worker1",
and that seems to have fixed it. Now the workers are listed and the undefined hashrate is decaying, so all is good. Thanks, I think the pool is working 100% now.
