### ISSUE TITLE
Equilibria XEQ pool blocks webpage displays wrong

### ISSUE THREAD

**Issue by RoggyDog** [dvandal/cryptonote-nodejs-pool#563]
So my 4th pool is working correctly, I'm finding blocks and pool is paying them out. It's just that the pool webpage displays the pool block info incorrectly...

![poolBlocks](https://user-images.githubusercontent.com/35351263/72481608-10523a80-37c9-11ea-9679-45608d193fa5.PNG)

I've tried different pool config.json settings trying to fix it, but currently am using the example provided with pool since that works best. All I can think is it might have something to do with XEQ or cn-gpu? I'm out of ideas to try.

**Comment by muscleman** [comment]
use the new frontend, blockdefinition in redis changed and now has 2 additional fields
