### ISSUE TITLE
cn-gpu algo

### ISSUE THREAD

**Issue by RoggyDog** [dvandal/cryptonote-nodejs-pool#565]
I just wanted to let you know, cn-gpu algo still doesn't work with latest master version. I can make it work using ryo-currency/node-cryptonight-hashing instead of MoneroOcean/node-cryptonight-hashing in package.json

**Comment by muscleman** [comment]
cool, i knew you needed their node-cryptonight-hashing

**Comment by muscleman** [comment]
maybe i make a ryo folder and make custom package.json
