### ISSUE TITLE
New website frontend dashboard displays stats twice

### ISSUE THREAD

**Issue by RoggyDog** [dvandal/cryptonote-nodejs-pool#566]
Just tried new website, looks nice. The dashboard panels initially are displayed correctly initially....
(FYI, these screenshots were taken from different browsers at different times, stats won't be consistent)

![initialfrontend](https://user-images.githubusercontent.com/35351263/72531511-a163f880-383f-11ea-930d-8d307fc42b47.PNG)

but after stats update it shows this...

![newfrontendPNG](https://user-images.githubusercontent.com/35351263/72531619-db34ff00-383f-11ea-8d46-bb6f3223d2d6.PNG)

Now, after a few minutes it appears the second row of panels doesn't update.

![newfrontendafterminutes](https://user-images.githubusercontent.com/35351263/72531937-7cbc5080-3840-11ea-9dc3-05e540ce323c.PNG)

and on further observation it looks like only the 3rd row updates regularly. On top row only Pool Hash Rate updates. Not sure on 4th row.

**Comment by muscleman** [comment]
check config.js for the website. ensure ParentCoin is the same as Coin in config.json for the backend.

also whats the F12 console output. are there errors

**Comment by RoggyDog** [comment]
Thanks, that seemed to fix it. I had xeq in for ParentCoin. So much to learn. These darn cn-gpu coins seem to be the only ones that give me headaches. Thanks again for quick reply.
