### ISSUE TITLE
Download

### ISSUE THREAD

**Issue by pool2mine** [dvandal/cryptonote-nodejs-pool#568]
Hi, I was trying to install this pool but can't see it anymore, is it private now? please let me know, Thanks!

**Comment by muscleman** [comment]
private

**Comment by trasherdk** [comment]
https://github.com/trasherdk/cryptonote-nodejs-pool

**Comment by pool2mine** [comment]
I really like this pool, nice front end and lots of coins... is any contributor planning to give support for ethereum?

**Comment by trasherdk** [comment]
Probably not. It looks like this repository is closed.

**Comment by trasherdk** [comment]
Check this out for a active fork:
https://techgaun.github.io/active-forks/index.html#dvandal/cryptonote-nodejs-pool

**Comment by pool2mine** [comment]
thanks!!
