### ISSUE TITLE
WRKZCoin

### ISSUE THREAD

**Issue by swa74** [dvandal/cryptonote-nodejs-pool#571]
Who will tell you what to put for WRKZCoin

    "cnAlgorithm": "argon2", ?
    "cnVariant": 2, ?
    "cnBlobType": 2, ?

**Comment by blockinator** [comment]
"cnAlgorithm": "argon2",
"cnVariant": 1, 
"cnBlobType": 2,

**Comment by swa74** [comment]
Thanks !
