### ISSUE TITLE
Zelerius

### ISSUE THREAD

**Issue by swa74** [dvandal/cryptonote-nodejs-pool#572]
"includeAlgo": "cn/zls",
    "daemonType": "bytecoin",
    "cnAlgorithm": "cryptonight",
    "cnVariant": 15,
    "cnBlobType": 2,

Launched a ZLS pool. It accepts hashes, finds blocks, but all the blocks are empty ...
There are no errors in the logs
The blocks are all correct, checked according to the exlorer and on the miningpoolstats.stream website are marked behind my pool
![Снимок](https://user-images.githubusercontent.com/34404806/74229632-d561fa80-4cd3-11ea-9d76-05ee816748d4.PNG)

**Comment by swa74** [comment]
Who will tell you where to look?

**Comment by trasherdk** [comment]
You will need to dive in to the source code, and give a hint about what's not working.
Then maybe  someone will take a look,
