### ISSUE TITLE
Can't mine Monero with sub address

### ISSUE THREAD

**Issue by pool2mine** [dvandal/cryptonote-nodejs-pool#575]
Hi @dvandal, I see the subAddressPrefix on some configs but not on "Monero". is it possible to mine monero to a subaddress (8XXXX)? if so, please let me know what value to add on subAddressPrefix. thanks in advance!

**Comment by Cideg** [comment]
set prefix 42

**Comment by pool2mine** [comment]
hi @Cideg ,

i have "intAddressPrefix": 19

should i change this value to 42? or should i add "subAddressPrefix": 42 ?

i currently have no "subAddressPrefix" in my actual config

Thanks!

**Comment by Cideg** [comment]
```
 subaddress (8XXXX)?
´``
"subAddressPrefix": 42

**Comment by pool2mine** [comment]
thank you @Cideg
