### ISSUE TITLE
npm update error

### ISSUE THREAD

**Issue by citizenz7** [dvandal/cryptonote-nodejs-pool#579]
System: ubuntu 18.04
I have followed the steps to setup this pool but always fail when --> `npm update`
It always ends with :
make: Entering directory '/home/mumbly/funky-turtle-pool/node_modules/turtlecoin-cryptonote-util/build'
  CXX(target) Release/obj.target/cryptonote/src/main.o
../src/main.cc: In function ‘Nan::NAN_METHOD_RETURN_TYPE cryptonoteutil::convert_blob(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/main.cc:91:46: error: no matching function for call to ‘v8::Value::ToObject()’
     Local<Object> target = info[0]->ToObject();
                                              ^
../..

cryptonote.target.mk:128: recipe for target 'Release/obj.target/cryptonote/src/main.o' failed
make: *** [Release/obj.target/cryptonote/src/main.o] Error 1
make: Leaving directory '/home/mumbly/funky-turtle-pool/node_modules/turtlecoin-cryptonote-util/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:311:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Linux 4.15.0-91-generic
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/mumbly/funky-turtle-pool/node_modules/turtlecoin-cryptonote-util
gyp ERR! node -v v12.16.1
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! turtlecoin-cryptonote-util@0.0.6 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the turtlecoin-cryptonote-util@0.0.6 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/mumbly/.npm/_logs/2020-03-16T12_07_43_724Z-debug.log

**Comment by trasherdk** [comment]
It's a but in upstream. Try:
```
npm install git://github.com/MoneroOcean/node-cryptonight-hashing.git#v17.0.3
```
And you'll see the error.

Anyways. All dependencies in this thing is seriously outdated/deprecated.

**Comment by LOUD-Mining** [comment]
@trasherdk I agree that the deps in this software are very deprecated...  If I knew more about coding I would try to tackle helping to update everything...  I've just honestly started coding with JavaScript so I CAN pick through code and sort of understand what is going on...  But I definitely still need some hand holding...

**Comment by trasherdk** [comment]
I'm not using this software, so I'm not going to dive in.
Maybe on of the other guys around here wants to give it a go.

**Comment by pool2mine** [comment]
i had some installation issues then i saw i missed some dependencies... try:

sudo apt-get install libssl-dev
sudo apt-get install libboost-all-dev

then again

npm update

**Comment by trasherdk** [comment]
Installing random software is not going to solve this issue.

**Comment by muscleman** [comment]
npm uninstall turtlecoin-multi-hashing

**Comment by trasherdk** [comment]
It seems like the upstream MoneroOcean repository, that was the probem before, has been fixed.

**Comment by saymissme** [comment]
try nodejs 11

**Comment by lseparatio** [comment]
I can confirm nodejs 10 and 11 are working. 12 not yet hope will work in future because i choose to use version 10x because of LTS.
