### ISSUE TITLE
Integrated addresses

### ISSUE THREAD

**Issue by dvandal** [dvandal/cryptonote-nodejs-pool#58]
I'm working to fix issues with integrated addresses validations, if possible please provides me for the different coins a normal address and an integrated address so that I can test each different cases. Thanks!

**Comment by Chinsusu** [comment]
Deposit address: | LDyaPZ5uWJ1DEnKR9V28ugBk8GoiSa2sxV4zju8YXG8Tii7EZbSPJMDcdTPcsiWBFeYLGjvhjFDxf1QazFxtoJYwKvXSnWi
-- | --
Payment ID: | 366032a9c08f4046
  |  
Integrated address (deposit address + Payment ID): | LPgFQMuQ7ZXDEnKR9V28ugBk8GoiSa2sxV4zju8YXG8Tii7EZbSPJMDcdTPcsiWBFeYLGjvhjFDxf1QazFxtoJYwUyArBDrfLmV8ymf8DU

Loki coin bro

**Comment by appkoders** [comment]
Hi,

What issues did you encounter when using integrated address? I am also developing my own pool and would like to know what issues you encountered so I know what to expect. I tried to implement it on my own but so far no issues yet on my codes.

Best regards,

**Comment by dvandal** [comment]
I already fixed support for integrated address using a validation method that works with all coins.
