### ISSUE TITLE
We haven't seen that IP for that wallet address in our record

### ISSUE THREAD

**Issue by hznovich** [dvandal/cryptonote-nodejs-pool#582]
Hi all. Help please.
Latest git version.
coin: Conceal (CCX)

Verification fields does not work. IP will exactly match the address, looked at the redis, and in the logs.
Address with payment id (address.paymentID). I tried it through + too.
There are no errors in the logs other than: INTERNAL ERROR: found reserve offset in unexpected place (found at 198, expected at 199).
What could be the problem?

**Comment by muscleman** [comment]
Should read about offset and previousoffset used in blocktemplate creation

**Comment by hznovich** [comment]
I think that is not the point. On a NIOBIO CASH (NBR) pool with similar settings, the same error (INTERNAL ERROR: found reserve offset in unexpected place), but the miner settings are applied and there is no such problem with the inability to find IP.
