### ISSUE TITLE
Block hash not being stored for monero

### ISSUE THREAD

**Issue by LOUD-Mining** [dvandal/cryptonote-nodejs-pool#583]
We're using your software to try to start up a Monero Pool..  The pool found a block and only reporting prop as the block hash...  Can you help?!?!?

**Comment by Cideg** [comment]
how do you start the pool or what is your config.json?

**Comment by LOUD-Mining** [comment]
> how do you start the pool or what is your config.json?

The pool found a block, but in redis, it was stored with prop at the front of the string and that is what the front-end was reading and displaying was prop as the block hash.  If you would like to chat about this, I am on discord. We have a server for the pool...  Here's the invite link.  

https://discord.gg/rvTZV5F

I am only available from approx 0600 CDT - 0900 CDT Mon. through Thurs. weekends are a different story but I am mostly up at night due to the fact that I work 3rd shift...  Thanks for the reply I look forward to hearing from you again @Cideg

**Comment by muscleman** [comment]
New block format for redis actually stores 2 extra values. 1. Prop or solo 2. Obfuscated miner address.
