### ISSUE TITLE
double widget in homepage

### ISSUE THREAD

**Issue by mrongoz** [dvandal/cryptonote-nodejs-pool#586]
how do i fix this, here is double information, which part should i fix, thanks
![Capture+_2020-04-17-10-37-27](https://user-images.githubusercontent.com/6456480/79526486-f5c58100-8097-11ea-8f9c-8776c5acfa34.png)

**Comment by Cideg** [comment]
delete the entry from config:  let parentCoin = "Arqma"

**Comment by polar-it** [comment]
Is not an issue, the website files included in the repo are an example, and are build for supporting merged mining as default option. To use for single coin mining you have to rewrite or customize your own web page. But if you set in config.js
 let parentCoin = ""
you have revert some website part as single coin ..  try it

**Comment by muscleman** [comment]
not sure you know what your talking about. this pool runs single or multi just fine.
config.json => "coin": "Arqma"

must match with case in 

config.js

let parentCoin = "Arqma"

simple

**Comment by polar-it** [comment]
I'm talking about web interface some undergoing pages faq etc are designed for merged mining. Sure works fine for single coin, this isn't the poin. If there is a typo error or mismach on parentCoin (config.js) vs coin (config.json) double widget stats are present on home page.  For a signle coin configuration works also with parentCoin ="" .. tested, but for sure your comment explain the right way to avoid the "double widget" thanks.

**Comment by lseparatio** [comment]
> not sure you know what your talking about. this pool runs single or multi just fine.
> config.json => "coin": "Arqma"
> 
> must match with case in
> 
> config.js
> 
> let parentCoin = "Arqma"
> 
> Then make sure to refresh the browsers cache.
> 
> simple

Correct solution!
