### ISSUE TITLE
Haven (XHV) payment issue

### ISSUE THREAD

**Issue by SixLitr** [dvandal/cryptonote-nodejs-pool#588]
Has anyone successfully used this repo (recently - it was working fine many months ago) to build a Haven pool that correctly issues payments? The daemon and wallet are sync'd fine, and I can manually make payments from the wallet-cli, but the pool will not initiate a payment automatically. Trying to find error logs and none seem to be helping. Any assistance is appreciated!

**Comment by muscleman** [comment]
my changes to this software did not change payment implementation in this pool upto and including v2.0.0 

eg) has not changed since v1.3

**Comment by SixLitr** [comment]
The problem seems to lie with a "bad ring size, invalid input" error in the config.json - its a poolside issue. The haven daemon and wallet are up to date and function properly, but the pools rpc commands are not correct. I tried changing the "mixin" value default of 5 to 11, swapping with "ring_ct" of 11 (which is correct according to devs) and even using both values and variables at the same time. None of these produce a successful transaction.

**Comment by SixLitr** [comment]
> The problem seems to lie with a "bad ring size, invalid input" error in the config.json - its a poolside issue. The haven daemon and wallet are up to date and function properly, but the pools rpc commands are not correct. I tried changing the "mixin" value default of 5 to 11, swapping with "ring_ct" of 11 (which is correct according to devs) and even using both values and variables at the same time. None of these produce a successful transaction.

Found The Problem:

The default config.json uses `"mixin": 5,`

This needs to be changed to `"ringSize": 11,`

Note: the issue was using `ring_size` instead of `ringSize` - this was changed at some point apparently.

**Comment by saymissme** [comment]
i use "mixin": 11
not work 
got this info

> {"code":-4,"message":"An output in this transaction was previously spent on another chain with ring size 17, it cannot be spent now with ring size 11 as it is smaller: use a higher ring size"}
change mixin to 17
got 
> tx verification failed: bad ring size, invalid input

how to fix it?

**Comment by saymissme** [comment]
[https://github.com/haven-protocol-org/haven-protocol/issues/4](url)

fixed
thx

**Comment by nons-pool** [comment]
does anybody know if it should be ring_size, ringSize, or mixin? Based on the discussion on Haven issue 4, it is a size of 11, but the variable doesn't seem to get passed on to the rpc call.  I get errors when paying out with ringSize, but I'm still using the code from before the wipe-out, should I update to the new one?

**Comment by SixLitr** [comment]
> > The problem seems to lie with a "bad ring size, invalid input" error in the config.json - its a poolside issue. The haven daemon and wallet are up to date and function properly, but the pools rpc commands are not correct. I tried changing the "mixin" value default of 5 to 11, swapping with "ring_size" of 11 (which is correct according to devs) and even using both values and variables at the same time. None of these produce a successful transaction.
> 
> Found The Problem:
> 
> The default config.json uses `"mixin": 5,`
> 
> This needs to be changed to `"ringSize": 11,`
> 
> Note: the issue was using `ring_size` instead of `ringSize` - this was changed at some point apparently.

**Comment by SixLitr** [comment]
> > The problem seems to lie with a "bad ring size, invalid input" error in the config.json - its a poolside issue. The haven daemon and wallet are up to date and function properly, but the pools rpc commands are not correct. I tried changing the "mixin" value default of 5 to 11, swapping with "ring_size" of 11 (which is correct according to devs) and even using both values and variables at the same time. None of these produce a successful transaction.
> 
> Found The Problem:
> 
> The default config.json uses `"mixin": 5,`
> 
> This needs to be changed to `"ringSize": 11,`
> 
> Note: the issue was using `ring_size` instead of `ringSize` - this was changed at some point apparently.

Please read above.

**Comment by nons-pool** [comment]
Thank you for your response, unfortunately ringSize didn't work so it wasn't clear for me. I'm going to look over your fork and see if everything lines up. Maybe I need to delete that shared-ring hidden folder before starting everything again.
