### ISSUE TITLE
Graft current config.

### ISSUE THREAD

**Issue by lseparatio** [dvandal/cryptonote-nodejs-pool#593]
Hi, any of you know graft config? I have tried plenty of but still bad shares raported by xmrig. Do i start the pool, no errors. Connected xmrig with: cn/rwz algo but pool and xmrig are raporting bad shares. I suspect the settings from config pool are not up to date. The lines:     "cnVariant": 15,
                                 "cnBlobType": 0,
Thank you for your time.

**Comment by RoggyDog** [comment]
Last time I had my Graft pool running I used ...
 "cnAlgorithm": "cryptonight",
 "cnVariant": 14,
 "cnBlobType": 0,

Try that and see if it works.

**Comment by lseparatio** [comment]
Yes is working thank you very much. Kind Regards.

**Comment by lseparatio** [comment]
I can confirm i was able to mine some blocks with:
"cnAlgorithm": "cryptonight",
"cnVariant": 14,
"cnBlobType": 1,

Thanks to all. I will close now.
