### ISSUE TITLE
Telegram Bot Notifications 

### ISSUE THREAD

**Issue by SoapyFresh** [dvandal/cryptonote-nodejs-pool#594]
Is there a way to turn off notifications of a block being unlocked/mined, but keep the ones that are found?

**Comment by lseparatio** [comment]
I am not 100% but you can try in /lib/notification.js to delete unwanted variable in this lines:
/**
 * Send global notification
 **/
exports.sendToAll = function (id, variables) {
	// Send telegram to channel
	sendToTelegramChannel(id, variables);

	// Send blocks notifications to telegram
	if (id === "blockFound" || id === "blockUnlocked" || id === "blockOrphaned") {
		sendBlockTelegram(id, variables);
	}

you can see: id === "blockFound"  ,  id === "blockUnlocked" ,  id === "blockOrphaned" . Just try to delete what you don't want.
