### ISSUE TITLE
nvm update error . I need some help

### ISSUE THREAD

**Issue by tieanminer** [dvandal/cryptonote-nodejs-pool#597]
Can someone help me to install this pool on ubuntu18.04/16.04

I tried many times, tried many ways, I found a lot of tutorials, but they are all old tutorials, not suitable for this swimming pool project

Some steps Follow the tutorial
source ~/.profile
nvm install 0.10.48
nvm use 0.10.48
nvm alias default 0.10.48
nvm use default

Node.js v11.0+ / Node.js v8.0+  Have tried

nvm update  Many errors occurred

and, where can I find the version 2.1.1 or higher

my email address : tieanminer@gmail.com

Please help me . A little more detail setp by setp is Better . thank you

**Comment by tieanminer** [comment]
problem solved

**Comment by bounce77** [comment]
What did you do to solve this problem?

**Comment by tieanminer** [comment]
i use nodejs v11.x

bounce77 <notifications@github.com>于2020年8月5日 周三13:33写道：

**Comment by tieanminer** [comment]
ubuntu 16.04

miner Tiean <tieanminer@gmail.com>于2020年8月6日 周四13:46写道：
