### ISSUE TITLE
npm update issue

### ISSUE THREAD

**Issue by bounce77** [dvandal/cryptonote-nodejs-pool#598]
I'm installing on Ubuntu Server 20.04 LTS.

I've tried node.js 11+ and 10+ (on a completely fresh copy).

During "npm update" both versions produce:

make: Entering directory '/home/miningpool/pool/node_modules/cryptoforknote-util/build'In file included from ../src/cryptonote_core/cryptonote_basic.h:28,
from ../src/main.cc:8:
../src/ringct/rctTypes.h:39:10: fatal error: sodium/crypto_verify_32.h: No such file or directory
39 | #include <sodium/crypto_verify_32.h>

**Comment by cloudmb** [comment]
apt-get install -y libsodium-dev
