### ISSUE TITLE
Intense coin ports

### ISSUE THREAD

**Issue by nutsplus** [dvandal/cryptonote-nodejs-pool#60]
Hi.
Where I can see wallet and daemon ports for INTS?
"daemon": {
        "host": "127.0.0.1",
        "port": ???
    },

    "wallet": {
        "host": "127.0.0.1",
        "port": ???
    },

**Comment by dvandal** [comment]
For daemon default RPC port is 48782 and for wallet it is set by you in your config when you start the RPC wallet daemon, for example 48783

**Comment by nutsplus** [comment]
![screenshot_2018-05-03-16-54-21-784_com yandex browser](https://user-images.githubusercontent.com/38542260/39580875-d97af814-4ef2-11e8-929c-be173bc6ae7a.png)
