### ISSUE TITLE
Telegram Stats Interval

### ISSUE THREAD

**Issue by uekdyr** [dvandal/cryptonote-nodejs-pool#61]
Having issues that the Telegram bot only posts the Pool Stats when I start the pool, it sends it one time and doesn't send it again after 5 minutes, any ideas?

The test in Admin panel works perfectly.

config:

        "channelStats": {
            "enabled": true,
            "interval": 5
        },

**Comment by dvandal** [comment]
Thanks, issue has been fixed.

**Comment by uekdyr** [comment]
Thanks! Believe it's in seconds now instead of minutes? ;)

Spamming like hell, using "5" in interval.

**Comment by uekdyr** [comment]
Works! Cheers @dvandal!
