### ISSUE TITLE
Merged Mining

### ISSUE THREAD

**Issue by SoapyFresh** [dvandal/cryptonote-nodejs-pool#611]
Does this software support merged mining? I thought it did at one point, but I don’t see any documentation.

**Comment by muscleman** [comment]
believe so

**Comment by fm407** [comment]
> Does this software support merged mining? I thought it did at one point, but I don’t see any documentation.

merged mining doesnt work

**Comment by xmrminers** [comment]
> Does this software support merged mining? I thought it did at one point, but I don’t see any documentation.

It does, you have to use a combination of Parent+childs (for example WTIP/XTOR/COTE can be parents to IRD/TTNZ/CIRQ/CMRA/BTCH/MNG/PXL/ZUM/ZTC/FTS/STCH/XKR) same goes for cryptonight variants, i will post a working configs so you can take a look.

The pool doesn't support mining all the coins at once as is, you can just pick 1 to combine with parent, the pool can be modded to take multiple child coins in the password field (me thinks with same blob type too?) i believe campurro's code allows same blob type merged mining.
