### ISSUE TITLE
Haven wrapper issue

### ISSUE THREAD

**Issue by fm407** [dvandal/cryptonote-nodejs-pool#612]
Is the haven wrapper issue going to ever get fixed? there is no way to compile it

**Comment by cryptomaxsun** [comment]
A similar problem

**Comment by Imlulle** [comment]
I went back on all changes made for Haven, got bunch of people running it. Made a request to fi it. 

Check my repo out https://github.com/Imlulle/cryptonote-nodejs-pool

**Comment by cryptomaxsun** [comment]
The solution to the problem is to use the pool of the old version 1.40. I had an old version of this pool, everything started there.

**Comment by fm407** [comment]
Removing the haven stuff is not a fix though, this should be addressed

**Comment by cryptomaxsun** [comment]
> Removing the haven stuff is not a fix though, this should be addressed

I agree with you, use the old version of the pool.

**Comment by fm407** [comment]
> > Removing the haven stuff is not a fix though, this should be addressed
> 
> I agree with you, use the old version of the pool.

That is not a solution either, using outdated software is a security blackhole, as I said there are v2 pools running haven, it just needs to be addressed in a non lazy way

**Comment by Imlulle** [comment]
Well you can run the new version without haven

**Comment by muscleman** [comment]
how the hell did that bHaven bull shit get in there. version 2.0.0 works fine if you configure it correctly, without the haven

**Comment by fm407** [comment]
> lol, how the hell did that bHaven bull shit get in there. version 2.0.0 works fine if you configure it correctly, without the haven junk

do you happen to have a link to a good v2? thanks!

**Comment by muscleman** [comment]
looks like Imlulle has a pull request to remove all the haven bullshit. then you can run with the correct cnblobtype = 11 and cnvariant = 1 from the moneroocean packages.

**Comment by fm407** [comment]
i have tried using lmlulle's repo and used algo cryptonight_heavy blob 11 and variant 1, it wont work, shares submitted are invalid

**Comment by fm407** [comment]
nan

**Comment by goodthebest** [comment]
@fm407 where is **cn-heavy/xhv in xmrig**, can you please explain the fix, which file needs to be corrected?

**Comment by fm407** [comment]
> @fm407 where is **cn-heavy/xhv in xmrig**, can you please explain the fix, which file needs to be corrected?

```
 "pools": [
        {
            "algo": "cn-heavy/xhv",
            "coin": null,
```

in xmrig config.json

**Comment by goodthebest** [comment]
Haven issue is when building/compiling it, npm install or update

**Comment by fm407** [comment]
> Thank you for your feedback but Haven issue is when building/compiling it, npm install or update

not sure,  @Imlulle repo compiles and works just fine if properly configured
