### ISSUE TITLE
intergrate address

### ISSUE THREAD

**Issue by Chinsusu** [dvandal/cryptonote-nodejs-pool#63]
How can I know which  "intAddressPrefix": is used for each coin?

**Comment by dvandal** [comment]
When you login with an integrated address, the pool will return an "Invalid login" error and will also include the address prefix. Just copy the numeric value.

**Comment by Invisys** [comment]
Another way:
In config.json under "poolServer" section add:
**"integratedAddress": "<any integrated address of coin>",**

In pool.js change:
**var integratedAddressBase58Prefix = addressBase58Prefix + 1;** 
to
**_var integratedAddressBase58Prefix = cnUtil.address_decode(new Buffer(config.poolServer.integratedAddress));_**


But this is temporary fix. Also some coins(like Masari) require totally another changes.

**Comment by dvandal** [comment]
Invisys, this is for old code, not compatible with current code which use a new method to check for integrated address (use same approach as in nodejs-pool)
