### ISSUE TITLE
Just cloned and setup config.json. Pool wont run.

### ISSUE THREAD

**Issue by mymininglife** [dvandal/cryptonote-nodejs-pool#646]
I think im dumb. nvm use 11. npm update. node init.js. then this error. I used the sumokoin example config and tried others but same error. Any advice? Thank you!!!

I have an old version of the pool running for the uPlexa coin. Wanted to get this newer maintained one going.

[chartsDataCollector] Started
buffer.js:200
    throw new ERR_INVALID_ARG_TYPE(
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be one of type string, Buffer, ArrayBuffer, Array, or Array-like Object. Received type undefined
    at Function.from (buffer.js:200:11)
    at new Buffer (buffer.js:175:17)
    at Object.<anonymous> (/sumo/pool/lib/utils.js:28:52)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Module.require (internal/modules/cjs/loader.js:723:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at Object.<anonymous> (/sumo/pool/lib/daemon.js:1:13)

**Comment by SuperBlockchain-Pool** [comment]
There is a code error in one of the last accepted pull requests. Something went wrong and it generates that error when trying to run with the init.js node. 

I have to analyze the code. To see where exactly the problem is, but surely in some file there are some ";" the rest. 

You can install the software from this commit, this one works.

https://github.com/dvandal/cryptonote-nodejs-pool/tree/97104b28a4d873e6e4a2cb9cab5fdd7da8940bd5

**Comment by abualsaudm** [comment]
I am also having the exact same issue. Any luck in getting this out of the way?

**Comment by abualsaudm** [comment]
btw, the commit is no longer available

**Comment by SuperBlockchain-Pool** [comment]
[cryptonote-nodejs-pool-97104b28a4d873e6e4a2cb9cab5fdd7da8940bd5.zip](https://github.com/dvandal/cryptonote-nodejs-pool/files/5832321/cryptonote-nodejs-pool-97104b28a4d873e6e4a2cb9cab5fdd7da8940bd5.zip)

**Comment by shopglobal** [comment]
I think it is a line which can be removed

**Comment by abualsaudm** [comment]
Yes, I found the issue to be in parsing the address to base64 in ./lib/util.js. The issue is now resolved. Thanks
