### ISSUE TITLE
Internal Error

### ISSUE THREAD

**Issue by OptimusBlue** [dvandal/cryptonote-nodejs-pool#649]
Hi

The setup is for Conceal (CCX) but I get the following error when I start the pool:

[pool] (Thread 1) INTERNAL ERROR: found reserve offset in unexpected place (found at 126, expected at 127)
[pool] (Thread 2) INTERNAL ERROR: found reserve offset in unexpected place (found at 126, expected at 127)

I am using the latest release.

**Comment by berghemhack** [comment]
Look around line 100 of pool.js in thise zone:

let previousOffset = config.previousOffset || 7;
let offset = config.offset || 3;
config.daemonType = config.daemonType || 'default';
if (config.daemonType === 'bytecoin') {
	previousOffset = config.previousOffset || 2;
	offset = config.offset || 3;
}
