### ISSUE TITLE
networt hash rate update

### ISSUE THREAD

**Issue by nutsplus** [dvandal/cryptonote-nodejs-pool#65]
Hi. Network hash rate and Last Hash is not update on my pool! http://intense.rocketpool.pro
Why? Thx

**Comment by Invisys** [comment]
Check your daemon. Seems it stuck.

**Comment by nutsplus** [comment]
Why so slow ./intensecoind sync? How I can do it faster?

**Comment by Invisys** [comment]
Sync speed depends on network speed and cpu usage. Check that your server is not overloaded
