### ISSUE TITLE
[daemon] monero error from daemon

### ISSUE THREAD

**Issue by dodois** [dvandal/cryptonote-nodejs-pool#662]
Awesome project, thank you for your dedication.

I installed the repository without any problem, but the following error occurs with ```node init.js```.

I am a newbie, please give me help, thanks.

![image](https://user-images.githubusercontent.com/73285310/109594234-627d2900-7b4d-11eb-8560-8c33dc8c674a.png)

**Comment by dvandal** [comment]
try changing port from 18981 to 18081, pool is unable to communicate with your Monero RPC port

**Comment by dvandal** [comment]
You should try using the monero.json file in config_examples/ to set initial monero configuration.

**Comment by dodois** [comment]
Thank you for your reply, I have tried this solution
![image](https://user-images.githubusercontent.com/73285310/109741163-79805180-7c07-11eb-968a-dc855cee1419.png)

**Comment by dodois** [comment]
node: v11.15.0
npm: 6.7.0
Run in docker

**Comment by dvandal** [comment]
Monero daemon is running ?

**Comment by dodois** [comment]
Where should I find out?

**Comment by mahdiamer** [comment]
> Awesome project, thank you for your dedication.
> 
> I installed the repository without any problem, but the following error occurs with `node init.js`.
> 
> I am a newbie, please give me help, thanks.
> 
> ![image](https://user-images.githubusercontent.com/73285310/109594234-627d2900-7b4d-11eb-8560-8c33dc8c674a.png)
