### ISSUE TITLE
Add support for Haven (XHV)

### ISSUE THREAD

**Issue by TechDev43** [dvandal/cryptonote-nodejs-pool#672]
Why was haven removed?
Please add it back!

[pool] (Thread 1) Malformed message from ::ffff:1.1.1.1 generated an exception. Message: {"id":1,"jsonrpc":"2.0","method":"login","params":{"login":"*XHV address*","pass":"x","agent":"XMRig/6.10.0 (Windows NT 10.0; Win64; x64) libuv/1.41.0 gcc/10.1.0","algo":["cn/1","cn/2","cn/r","cn/fast","cn/half","cn/xao","cn/rto","cn/rwz","cn/zls","cn/double","cn-lite/1","cn-heavy/0","cn-heavy/tube","cn-heavy/xhv","cn-pico","cn-pico/tlo","cn/ccx","rx/0","rx/wow","rx/arq","rx/sfx","rx/keva","argon2/chukwa","argon2/chukwav2","argon2/wrkz","astrobwt"]}}

[pool] (Thread 1) Exception: Failed to parse block

**Comment by Cideg** [comment]
Which blob and cn-variant do you use?

**Comment by TechDev43** [comment]
@Cideg
I used the ones from the haven.json example config.

"cnAlgorithm": "cryptonight_heavy",
"cnVariant": null,
"cnBlobType": 0,

**Comment by Cideg** [comment]
that's where the mistake lies

**Comment by TechDev43** [comment]
@Cideg
So this should work?

"cnVariant": 1,
"cnBlobType": 11,
