### ISSUE TITLE
Pool fee

### ISSUE THREAD

**Issue by PsychoSterope** [dvandal/cryptonote-nodejs-pool#68]
I was wondering what I needed to do to have the website show the total fee, pool fee + dev fee.

**Comment by dvandal** [comment]
The pool already show the total (pool + dev fees) ?

**Comment by PsychoSterope** [comment]
I've never gotten it to show the total fee, only the pool fee. I have it set to 0.25% pool and 0.25% dev but it only shows 0.25% on the home page. Take a look http://www.masaripool.us/

**Comment by dvandal** [comment]
Ok, this is not that it doesn't works, its because I don't have a masari wallet in donation settings and so donation doesn't apply.

**Comment by PsychoSterope** [comment]
Ahh ok. Well I tried :D

**Comment by dvandal** [comment]
I just created new wallets and added them to config.

**Comment by PsychoSterope** [comment]
Thanks!
