### ISSUE TITLE
New ItaloCoin

### ISSUE THREAD

**Issue by swa74** [dvandal/cryptonote-nodejs-pool#71]
config.json

    "coin": "Italocoin",
    "symbol": "ITA",
    "coinUnits": 1000000000000,
    "coinDifficultyTarget": 180,
    "cnAlgorithm": "cryptonight",
    "cnVariant": 1,

    "intAddressPrefix": 257,

    "payments": {
        "enabled": true,
        "interval": 300,
        "maxAddresses": 50,
        "mixin": 7,
        "priority": 0,
        "transferFee": 20000000,
        "dynamicTransferFee": true,
        "minerPayFee" : true,
        "minPayment": 1000000000000,
        "maxTransactionAmount": 0,
        "denomination": 100000000000
    },

    "daemon": {
        "host": "127.0.0.1",
        "port": 13102
    },

    "wallet": {
        "host": "127.0.0.1",
        "port": 8082
    },

Полностью рабочий пул http://ita.minexmr24.ru

**Comment by dvandal** [comment]
Thanks, configuration example added.
