### ISSUE TITLE
Is working for Monero RandomX?

### ISSUE THREAD

**Issue by lioncrypter** [dvandal/cryptonote-nodejs-pool#718]
Work with new daemon and RandomX?

**Comment by Cideg** [comment]
yes

**Comment by lioncrypter** [comment]
> yes

I think not for me, i have error when try npm update

**Comment by Cideg** [comment]
what is displayed, or what errors are the current?

**Comment by lioncrypter** [comment]
> what is displayed, or what errors are the current?

At global scope:
cc1plus: warning: unrecognized command line option ‘-Wno-unused-private-field’
  CC(target) Release/obj.target/multihashing/bcrypt.o
  CC(target) Release/obj.target/multihashing/blake.o
  CXX(target) Release/obj.target/multihashing/boolberry.o
../boolberry.cc:2:10: fatal error: crypto/cryptonote_core/cryptonote_format_utils.h: No existe el archivo o el directorio
 #include "crypto/cryptonote_core/cryptonote_format_utils.h"
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
multihashing.target.mk:177: fallo en las instrucciones para el objetivo 'Release/obj.target/multihashing/boolberry.o'
make: *** [Release/obj.target/multihashing/boolberry.o] Error 1
make: se sale del directorio '/home/poolxmr/pool/node_modules/turtlecoin-multi-hashing/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:193:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:255:12)
gyp ERR! System Linux 5.4.0-84-generic
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/poolxmr/pool/node_modules/turtlecoin-multi-hashing
gyp ERR! node -v v11.15.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! turtlecoin-multi-hashing@0.0.19 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the turtlecoin-multi-hashing@0.0.19 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/poolxmr/.npm/_logs/2022-12-24T16_34_03_287Z-debug.log

i change turtle in package.json and put this 
"turtlecoin-multi-hashing": "git+https://github.com/BlackPeter13/node8-multihashing.git",
