### ISSUE TITLE
How update turtlecoin? Chukwa2

### ISSUE THREAD

**Issue by lioncrypter** [dvandal/cryptonote-nodejs-pool#720]
i no found how can i work turtlecoin because they change algo

**Comment by Cideg** [comment]
static xmrig::cn_hash_fun get_argon2_fn(const int algo) {

https://github.com/MoneroOcean/node-cryptonight-hashing/blob/ffb88e68a3f928112a843318d0120a2ccd00ad34/multihashing.cc#L253

"cnAlgorithm": "argon2",

**Comment by lioncrypter** [comment]
> static xmrig::cn_hash_fun get_argon2_fn(const int algo) {
> 
> https://github.com/MoneroOcean/node-cryptonight-hashing/blob/ffb88e68a3f928112a843318d0120a2ccd00ad34/multihashing.cc#L253
> 
> "cnAlgorithm": "argon2",

so i need change all multihashing.cc copy and paste, or only add 
static xmrig::cn_hash_fun get_argon2_fn(const int algo) {
"cnAlgorithm": "argon2",

**Comment by Cideg** [comment]
?????????????????????????????????????????????????????????????????????
config.js
```
	
    "coin": "TurtleCoin",
    "symbol": "TRTL",
    "coinUnits": 100,
    "coinDecimalPlaces": 4,
    "coinDifficultyTarget": 30,
    "blockchainExplorer": "https://explorer.turtlecoin.lol/block.html?hash={id}",
    "transactionExplorer": "https://explorer.turtlecoin.lol/transaction.html?hash={id}",

    "daemonType": "bytecoin",
    "cnAlgorithm": "argon1",
    "cnVariant": 2,
    "cnBlobType": 2,
```
