### ISSUE TITLE
How did intAddressPrefix get the answer?

### ISSUE THREAD

**Issue by youzidebaba** [dvandal/cryptonote-nodejs-pool#74]
![image](https://user-images.githubusercontent.com/37879101/39666485-c8e7005c-50d6-11e8-8bb7-de282f21bb97.png)
If I want to open a pool, how should I fill in here? Where can I get this value?

**Comment by swa74** [comment]
В зависимости от монеты, но как правило тут - /home/USER/COIN/src/cryptonote_config.h

**Comment by youzidebaba** [comment]
But how can I decrypt him?
He is the encryption of base58

**Comment by swa74** [comment]
For starters, it does not prevent to run the pool in test mode - this is an integrated address that includes a payment ID for exchanges and exchangers. For a regular purse it is not needed and not important

**Comment by youzidebaba** [comment]
![image](https://user-images.githubusercontent.com/37879101/39667045-5da575c6-50e0-11e8-87f7-d3102c8664c5.png)
I found the address of this parameter, but I couldn't figure out how 28822 was calculated.

**Comment by swa74** [comment]
I today launched a pool of italocoin coins with a default value and the pool worked fine

**Comment by youzidebaba** [comment]
May I see it?

**Comment by swa74** [comment]
Of course
http://ita.minexmr24.ru
The configuration file is added to the samples today.

**Comment by youzidebaba** [comment]
It looks great! Can you send your config.json?

**Comment by swa74** [comment]
https://github.com/dvandal/cryptonote-nodejs-pool/blob/master/config_examples/italocoin.json
This is my

**Comment by swa74** [comment]
Initially, there were 28,822 and the first few blocks the pool found and processed with this value

**Comment by youzidebaba** [comment]
thanks

**Comment by swa74** [comment]
swa74@mail.ru
Write, I'll try to help than I can

**Comment by youzidebaba** [comment]
That's great. Thank you, my friend.

**Comment by appkoders** [comment]
`I found the address of this parameter, but I couldn't figure out how 28822 was calculated.`

0x7096 is in hex just convert it into decimal and you will get 28822
