### ISSUE TITLE
web frontend  - no stats 

### ISSUE THREAD

**Issue by rut78HR** [dvandal/cryptonote-nodejs-pool#76]
Hello 

ubuntu 16.04 - nginx as web server
when i connect to pool i got empty page 
![screenshot-2018-5-5 cryptonote mining pool](https://user-images.githubusercontent.com/22094734/39667923-2006191a-50c1-11e8-81d0-9221b14dfa57.png)

but when i open worker statistic and type enter on adress tab i got statistic on screen. Im i missing somthing on nginx ?
![screenshot-2018-5-6 cryptonote mining pool](https://user-images.githubusercontent.com/22094734/39667934-77f902c2-50c1-11e8-867b-bafae761b542.png)
![screenshot-2018-5-6 cryptonote mining pool 1](https://user-images.githubusercontent.com/22094734/39667936-7c94b7c2-50c1-11e8-8696-2a339ff9bde0.png)

**Comment by rut78HR** [comment]
nobody ?? look at first screenshoot it says : Mining Pool  and no stats. But when i click on worker statistic and send enter it says XMR Mining Pool and evrything is ok. But if i reload page it stuck again with Mining Pool. It looks like no data is fetch from api on reloading page.

**Comment by swa74** [comment]
"bindIp": "0.0.0.0",
        "port": 8118,

var api = "http://minexmr24.ru:8118";
var poolHost = "pool.minexmr24.ru";

in configuration files and on the router everything is spelled out?
Try the browser in incognito mode, maybe because of the cache

**Comment by swa74** [comment]
var telegram = "https://t.me/YourPool";
var discord = "https://discordapp.com/invite/YourPool";

and return these settings back

**Comment by rut78HR** [comment]
Tnx but i managed to fix these. In web_frontend config.js i removed before lines for telegram and discord. Reverting back these fixed issue

**Comment by dvandal** [comment]
Code has been patched to fix this issue.

**Comment by teamsimplecrypto** [comment]
I'm having this same issue and mine is updated
