### ISSUE TITLE
Error: Failed to parse block

### ISSUE THREAD

**Issue by youzidebaba** [dvandal/cryptonote-nodejs-pool#81]
Plese help, i'm using qwerty.

Error: Failed to parse block
    at Error (native)
    at Object.BlockTemplate.nextBlob (/root/DATA/qwc/lib/pool.js:155:29)
    at Object.Miner.getJob (/root/DATA/qwc/lib/pool.js:331:41)
    at handleMinerMethod (/root/DATA/qwc/lib/pool.js:465:28)
    at handleMessage (/root/DATA/qwc/lib/pool.js:832:13)
    at Socket.<anonymous> (/root/DATA/qwc/lib/pool.js:886:25)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:153:18)
    at Socket.Readable.push (_stream_readable.js:111:10)
![image](https://user-images.githubusercontent.com/37879101/39676293-c1e2157a-519a-11e8-9b7f-82c5886b87f4.png)

**Comment by jbnl** [comment]
Same issue for me

**Comment by dvandal** [comment]
This issue occur when using wrong cryptonight algorithm. First update to lastest release 1.3.2 then try different algorithms. I'm not sure but I think qwerty coin is using "cryptonight_heavy".

**Comment by leisegang** [comment]
when i get it to compile the node_modules it hangs on connection to the pool:


PM2        | App name:pool id:12 online
12|pool    | Failed to read config file config.json
12|pool    | SyntaxError: Unexpected string
12|pool    | ReferenceError: config is not defined
12|pool    |     at Object.<anonymous> (/pinkstar/pool/lib/logger.js:29:14)
12|pool    |     at Module._compile (module.js:409:26)
12|pool    |     at Object.Module._extensions..js (module.js:416:10)
12|pool    |     at Module.load (module.js:343:32)
12|pool    |     at Function.Module._load (module.js:300:12)
12|pool    |     at Module.require (module.js:353:17)
12|pool    |     at require (internal/module.js:12:17)
12|pool    |     at Object.<anonymous> (/pinkstar/pool/init.js:17:1)
12|pool    |     at Module._compile (module.js:409:26)
12|pool    |     at Object.Module._extensions..js (module.js:416:10)
PM2        | App [pool] with id [12] and pid [13330], exited with code [1] via signal [SIGINT]
PM2        | Script /pinkstar/pool/init.js had too many unstable restarts (16). Stopped. "errored"

**Comment by youzidebaba** [comment]
![1 1](https://user-images.githubusercontent.com/37879101/39740668-3be668d8-52c9-11e8-9d43-6fc85621d1b6.png)
![1](https://user-images.githubusercontent.com/37879101/39740669-3c6adf3c-52c9-11e8-915b-3312875edfbd.png)
![2 2](https://user-images.githubusercontent.com/37879101/39740670-3cb506a2-52c9-11e8-909c-d30a5cc313e0.png)
![2](https://user-images.githubusercontent.com/37879101/39740673-3d8111c0-52c9-11e8-8b2b-048bebdde6ac.png)
![3 3](https://user-images.githubusercontent.com/37879101/39740674-3dca7892-52c9-11e8-925f-873686052c4b.png)
![3](https://user-images.githubusercontent.com/37879101/39740675-3e17c69c-52c9-11e8-99f1-9350533415d8.png)
![333](https://user-images.githubusercontent.com/37879101/39740780-c58462c0-52c9-11e8-9322-c617fd48d7d7.png)

Changing the algorithm is not feasible. I asked the author that the algorithm is cryptonight 2.0

But using this program can run https://github.com/qwertycoin-org/qwertycoin-pool.git well.
Can you help me see why? I don't want to use his program. His program functions are too few!

**Comment by youzidebaba** [comment]
![1 1](https://user-images.githubusercontent.com/37879101/39740867-21ca240c-52ca-11e8-8ec7-de45eb73bfcf.png)
![1](https://user-images.githubusercontent.com/37879101/39740868-2215873a-52ca-11e8-9a50-6615148a40f2.png)
![2 2](https://user-images.githubusercontent.com/37879101/39740869-225efcc6-52ca-11e8-8d36-22cb1f78ad83.png)
![2](https://user-images.githubusercontent.com/37879101/39740871-22a78414-52ca-11e8-9994-e66d3b74fec4.png)
![3 3](https://user-images.githubusercontent.com/37879101/39740872-22ef8c5a-52ca-11e8-9d0a-b92efda02761.png)
![3](https://user-images.githubusercontent.com/37879101/39740873-233a1aa4-52ca-11e8-81af-84f4f21a601d.png)
![333](https://user-images.githubusercontent.com/37879101/39740874-23cf637a-52ca-11e8-92d9-106c934cf5dd.png)



But using this program can run https://github.com/qwertycoin-org/qwertycoin-pool.git well.
Can you help me see why? I don't want to use his program. His program functions are too few!


@dvandal

**Comment by dvandal** [comment]
Please try lastest code, all issues should be fixed. You may need to set new cnBlobType setting.
