### ISSUE TITLE
algorithm

### ISSUE THREAD

**Issue by swa74** [dvandal/cryptonote-nodejs-pool#82]
It would not be bad to add an algorithm

![default](https://user-images.githubusercontent.com/34404806/39692926-051522d8-51eb-11e8-800e-70e8c23f87ed.JPG)

    
    <div id="top-bar">
        <div id="section"><span tkey="network">Network</span>: <strong><span id="g_networkHashrate"><span tkey="na">N/A</span></span></strong></div>
        <div id="section"><span tkey="pool">Pool</span>: <strong><span id="g_poolHashrate"><span tkey="na">N/A</span></span></strong></div>
        <div id="section"><span tkey="you">You</span>: <strong><span id="g_userHashrate"><span tkey="na">N/A</span></span></strong></div>
        <div id="section"><span id="statsUpdated"><span tkey="statsUpdated">Stats Updated</span> &nbsp;<i class="fa fa-bolt"></i></span></div>
        <div id="section"><span>CryptoNight v7</span></div>
	<div id="langSelector"></div>

**Comment by swa74** [comment]
So it is visible with what algorithm the pool works, otherwise users start to connect everything

**Comment by dvandal** [comment]
Thanks for suggesting, this has been added to Getting Started page.
