### ISSUE TITLE
Last response:{"bytesParsed" :0,"code" :"HPE_INVALID_CONSTANT" }

### ISSUE THREAD

**Issue by muhamadridwanid** [dvandal/cryptonote-nodejs-pool#87]
I am get this error when using masari..
please help me.

Last response:{"bytesParsed" :0,"code" :"HPE_INVALID_CONSTANT" }

![image](https://user-images.githubusercontent.com/20136946/39744125-5cf38764-52cd-11e8-83d7-c7b55cb99ab3.png)

**Comment by dvandal** [comment]
Your wallet is running as RPC server ?

**Comment by rut78HR** [comment]
u need to run monero-wallet-rpc --wallet-file xxxxx --password xxxxx  --rpc-bind-ip 127.0.0.1 --rpc-bind-port 8082 --disable-rpc-login  (if monerod is running on separate server u need to provide  --daemon-address host:port)
and in config.json provide port for wallet : 8082 (8082 in this example)

**Comment by PsychoSterope** [comment]
Actually for Masari, with the current wallet-rpc, it needs to be:
./masari-wallet-rpc --wallet-file xxxx --password xxxx --rpc-bind-ip 127.0.0.1 --rpc-bind-port 38083 --disable-rpc-login

**Comment by muhamadridwanid** [comment]
rpc server is running but invalid port in config.json..  thank you all

**Comment by userid2018** [comment]
@rut78HR 

I am running the  monero-wallet-rpc --wallet-file xxxxx --password xxxxx --rpc-bind-ip 127.0.0.1 --rpc-bind-port 8082 --disable-rpc-login .

monero daemon is on same server but i am still getting this error. Any pointers. I have opened another issue as well for this  https://github.com/dvandal/cryptonote-nodejs-pool/issues/230
