### ISSUE TITLE
Error on build - after git pull for update

### ISSUE THREAD

**Issue by bruceleeon** [dvandal/cryptonote-nodejs-pool#88]
pooldaemon@loki:~/pool$ npm update
npm WARN deprecated nodemailer@2.7.2: All versions below 4.0.1 of Nodemailer are deprecated. See https://nodemailer.com/status/
npm ERR! Error while executing:
npm ERR! /usr/bin/git ls-remote -h -t git://github.com/dvandal/node-cryptonight-hashing.git
npm ERR!
npm ERR! fatal: remote error:
npm ERR!   Repository not found.
npm ERR!
npm ERR! exited with error code: 128

**Comment by dvandal** [comment]
Are you sure that you did "git pull" ? It should have updated the package.json to new modules.

What is the content of your  package.json file ?

**Comment by bruceleeon** [comment]
{
    "name": "cryptonote-nodejs-pool",
    "version": "1.3.2",
    "license": "GPL-2.0",
    "author": "Daniel Vandal",
    "repository": {
        "type": "git",
        "url": "https://github.com/dvandal/cryptonote-nodejs-pool.git"
    },
    "dependencies": {
        "bignum": "*",
        "async": "1",
        "redis": "*",
        "cli-color": "*",
        "dateformat": "*",
        "time-ago": "*",
        "base58-native": "*",
        "socket.io": "*",
        "nodemailer": "2.7.2",
        "nodemailer-sendmail-transport": "*",
        "mailgun.js": "*",
        "node-telegram-bot-api": "*",
        "cryptoforknote-util": "git://github.com/MoneroOcean/node-cryptoforknote-util",
        "cryptonight-hashing": "git://github.com/MoneroOcean/node-cryptonight-hashing.git"
    },
    "engines": {
        "node": ">=4.0"
    }
}

**Comment by dvandal** [comment]
The lastest package.json file should be:

> {
    "name": "cryptonote-nodejs-pool",
    "version": "1.3.2",
    "license": "GPL-2.0",
    "author": "Daniel Vandal",
    "repository": {
        "type": "git",
        "url": "https://github.com/dvandal/cryptonote-nodejs-pool.git"
    },
    "dependencies": {
        "bignum": "*",
        "async": "1",
        "redis": "*",
        "cli-color": "*",
        "dateformat": "*",
        "time-ago": "*",
        "base58-native": "*",
        "socket.io": "*",
        "nodemailer": "2.7.2",
        "nodemailer-sendmail-transport": "*",
        "mailgun.js": "*",
        "node-telegram-bot-api": "*",
        "cryptoforknote-util": "git://github.com/MoneroOcean/node-cryptoforknote-util",
        "cryptonight-hashing": "git://github.com/MoneroOcean/node-cryptonight-hashing"
    },
    "engines": {
        "node": ">=4.0"
    }
}

**Comment by dvandal** [comment]
Remove your node_modules/ folder then do npm update again

**Comment by bruceleeon** [comment]
i did that, rm -rf node_modules

drwxrwxr-x  9 pooldaemon pooldaemon 4.0K May  8 13:56 .
drwxr-xr-x 18 pooldaemon pooldaemon 4.0K May  7 17:04 ..
-rw-rw-r--  1 pooldaemon pooldaemon 1.7K May  8 13:40 cert.key
-rw-r--r--  1 pooldaemon pooldaemon 1.3K May  8 13:40 cert.pem
drwxrwxr-x  2 pooldaemon pooldaemon 4.0K May  8 13:46 config_examples
-rw-rw-r--  1 pooldaemon pooldaemon 8.6K May  8 13:38 config.json
drwxrwxr-x  2 pooldaemon pooldaemon 4.0K May  6 18:59 email_templates
drwxrwxr-x  8 pooldaemon pooldaemon 4.0K May  8 13:56 .git
-rw-rw-r--  1 pooldaemon pooldaemon   73 May  6 18:59 .gitignore
-rw-rw-r--  1 pooldaemon pooldaemon 8.2K May  6 18:59 init.js
drwxrwxr-x  2 pooldaemon pooldaemon 4.0K May  8 13:46 lib
-rw-rw-r--  1 pooldaemon pooldaemon  18K May  6 18:59 LICENSE
drwxrwxr-x  2 pooldaemon pooldaemon 4.0K May  8 01:49 logs
-rw-rw-r--  1 pooldaemon pooldaemon  842 May  8 13:49 package.json
-rw-rw-r--  1 pooldaemon pooldaemon  81K May  6 19:01 package-lock.json
-rw-rw-r--  1 pooldaemon pooldaemon  933 May  6 19:01 packageold.json
-rw-r--r--  1 pooldaemon pooldaemon 1.7K May  8 13:17 privkey.pem
-rw-rw-r--  1 pooldaemon pooldaemon  29K May  8 13:46 README.md
drwxrwxr-x  2 pooldaemon pooldaemon 4.0K May  6 18:59 utils
drwxrwxr-x  6 pooldaemon pooldaemon 4.0K May  8 13:46 website_example

**Comment by bruceleeon** [comment]
the funny thing about it is that the package.json calles for moneroicean, but the error is for git://github.com/dvandal/node-cryptonight-hashing.git, which returns a 404 when i visit github.com/dvandal/node-cryptonight-hashing.git

**Comment by bruceleeon** [comment]
163 http fetch GET 304 https://registry.npmjs.org/nodemailer-sendmail-transport 284ms (from cache)
164 silly pacote version manifest for redis@2.8.0 fetched in 285ms
165 silly pacote version manifest for nodemailer-sendmail-transport@1.0.2 fetched in 286ms
166 silly pacote git manifest for undefined@git://github.com/MoneroOcean/node-cryptonight-hashing.git fetched in 214ms
167 silly pacote git manifest for undefined@git://github.com/MoneroOcean/node-cryptoforknote-util.git fetched in 231ms
168 silly install loadIdealTree
169 silly install cloneCurrentTreeToIdealTree
170 silly install loadShrinkwrap
171 silly fetchPackageMetaData error for cryptonight-hashing@git://github.com/dvandal/node-cryptonight-hashing.git#32df050b305b9011a513f5c0b5bd11b1b76aa849 Error while executing:
171 silly fetchPackageMetaData /usr/bin/git ls-remote -h -t git://github.com/dvandal/node-cryptonight-hashing.git
171 silly fetchPackageMetaData
171 silly fetchPackageMetaData fatal: remote error:
171 silly fetchPackageMetaData   Repository not found.
171 silly fetchPackageMetaData
171 silly fetchPackageMetaData exited with error code: 128

**Comment by dvandal** [comment]
Remove package-lock.json and packageold.json ?

**Comment by bruceleeon** [comment]
had to remove package-lock.json
