### ISSUE TITLE
Guidance on SSL with Pool Api

### ISSUE THREAD

**Issue by bruceleeon** [dvandal/cryptonote-nodejs-pool#89]
Server running apache
let's encrypt installed for apache: 

**config.json:**
```
    "api": {
        "enabled": true,
        "hashrateWindow": 600,
        "updateInterval": 30,
        "bindIp": "0.0.0.0",
        "port": 8117,
        "blocks": 30,
        "payments": 30,
        "password": "something",
        "ssl": true,
        "sslPort": 8119,
        "sslCert": "./cert.pem",
        "sslKey": "./privkey.pem",
        "sslCA": "./chain.pem",
        "trustProxyIP": false
    },
```

```
sudo cp /etc/letsencrypt/live/mysite.com/cert.pem ~/pool/
sudo cp /etc/letsencrypt/live/mysite.com/privkey.pem ~/pool/
sudo cp /etc/letsencrypt/live/mysite.com/fullchain.pem ~/pool/
chown pooldaemon:pooldaemon ~/pool/*.pem
```

**Apache directives:**
```
SSLCertificateFile /etc/letsencrypt/live/mysite.com/fullchain.pem
SSLCertificateKeyFile /etc/letsencrypt/live/mysite.com/privkey.pem
Include /etc/letsencrypt/options-ssl-apache.conf

<Location "/api">
ProxyPass http://127.0.0.1:8119
ProxyPassReverse http://127.0.0.1:8119
ProxyPass http://mysite.com:8119
</Location>
```

**Config.js**

```
var api = "//mysite.com:8119";
var poolHost = "mysite.com";
```

But... I just can't seem to get it to work, API just spins and spins

**Comment by dvandal** [comment]
You are redirecting /api to the API port, then you can set api in config.js (front-end) to:
var api = "/api";

**Comment by dvandal** [comment]
You can test if API is working by going to https://mysite.com/api/stats

**Comment by bruceleeon** [comment]
That api port redirect doesn't seem to work, the api just spins. 

If I load //mysite.com:8119 into config.js all seems well. It is working now, looks like it was the fullchain.pem file that was missing and causing no ssl to operate at all.

In the last 10 mins, you have been super helpful! donation on its way!

**Comment by dvandal** [comment]
I prefer NGINX instead of Apache to run the pool (better HTTP/2 support, load balancing, etc), apache is great and I use it on my hosting servers but generally only when PHP is needed and behind an NGINX proxy.

**Comment by bruceleeon** [comment]
I may make the switch to NGINX, thanks for the advice.

**Comment by bruceleeon** [comment]
One more question, how would I go about moving this install from vps to dedicated? I have the servers. With nodejs-pool (snipa) everything is in sql and lmdb... here. I am lost!

**Comment by bruceleeon** [comment]
If I use the following: openssl req -subj "/C=IT/ST=Pool/L=Daemon/O=Mining Pool/CN=mining.pool" -newkey rsa:2048 -nodes -keyout cert.key -x509 -out cert.pem -days 36500

How can I easily create the chain.pem file?
