### ISSUE TITLE
API crashes 

### ISSUE THREAD

**Issue by tr4nscr1pt** [dvandal/cryptonote-nodejs-pool#9]
API module crashes when users opens workers stats on pool few times.

<--- Last few GCs --->

   96629 ms: Scavenge 1401.4 (1456.9) -> 1401.4 (1456.9) MB, 61.6 / 0 ms (+ 46.5 ms in 1 steps since last GC) [allocation failure] [incremental marking delaying mark-sweep].
  101854 ms: Mark-sweep 1401.4 (1456.9) -> 1397.5 (1452.9) MB, 5224.7 / 0 ms (+ 415.0 ms in 805 steps since start of marking, biggest step 46.5 ms) [last resort gc].
  106600 ms: Mark-sweep 1397.5 (1452.9) -> 1397.3 (1456.9) MB, 4745.6 / 0 ms [last resort gc].

<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x12b6e1137399 <JS Object>
    1: convertPaymentsDataToChart(aka convertPaymentsDataToChart) [/var/www/pool/cryptonote-nodejs-pool/lib/charts.js:~39] [pc=0x227cba999ce7] (this=0x12b6e1104131 <undefined>,paymentsData=0x128f76e4e781 <JS Array[60]>)
    2: /* anonymous */(aka /* anonymous */) [/var/www/pool/cryptonote-nodejs-pool/lib/charts.js:59] [pc=0x227cba93742c] (this=0x12b6e1104131 <undefined>,callback=0x2b0625e80b71 ...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory
2018-03-20 13:43:21 [master] API died, spawning replacement...
2018-03-20 13:43:21 [charts] Unable to get API data for stats: Error: read ECONNRESET
2018-03-20 13:43:21 [charts] Unable to get API data for stats: Error: read ECONNRESET

**Comment by dvandal** [comment]
The error is: FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory

By default Node.JS limit memory usage, you will need to increase the limit.

For 2GB limit:
node --max_old_space_size=2048 init.js

For 4GB limit:
node --max_old_space_size=4096 init.js

For 8GB limit:
node --max_old_space_size=8192 init.js

Etc.
