### ISSUE TITLE
Update ItaloCoin

### ISSUE THREAD

**Issue by swa74** [dvandal/cryptonote-nodejs-pool#91]
Starting with the block 20.000 ItaloCoin passes to the algorithm CryptoNight-Heavy

    "coin": "Italocoin",
    "symbol": "ITA",
    "coinUnits": 1000000000000,
    "coinDifficultyTarget": 120,
    "cnAlgorithm": "cryptonight_heavy",
    "cnVariant": null,

Update pls config.json

If you can add my pool to the list using this script ita.minexmr24.ru

**Comment by dvandal** [comment]
This has been done and I updated the wiki page also: https://github.com/dvandal/cryptonote-nodejs-pool/wiki/Cryptonote-Coins
