### ISSUE TITLE
User payment graph : numbers too big ?

### ISSUE THREAD

**Issue by citizenz7** [dvandal/cryptonote-nodejs-pool#92]
Hi !
In the user payment graph (on worker_stats page), user payments are shown in the "atomic" format. I mean, they are good but seem to be based on the Coin Unit  : 38,599,900,000 instead of 3,859.99 (this is a pool for SOLACE COIN - Coin unit : 10,000,000 - cryptonight heavy).
See [the image](https://framapic.org/gallery#D7mlp1H67UNz/JqKJkIuq6a9D.jpg).
Is it possible to change it ?
Thanx for all !

**Comment by dvandal** [comment]
Thanks! It has been fixed now.
