### ISSUE TITLE
E-mail not send to everyone is no telegram channel configured

### ISSUE THREAD

**Issue by jagerman** [dvandal/cryptonote-nodejs-pool#96]
I have a telegram bot set up, but it doesn't have an announcement channel.  In current master, when e-mails are supposed to be send out to everyone (e.g. for a block unlocked) they don't get sent.

In `notifications.js` the condition for telegram does:
```
if (!channel) { 
    log(...);
    return;
}
```
but that `return` also ends up skipping the e-mail sending that follows.

**Comment by dvandal** [comment]
Fixed. Thanks!
