### ISSUE TITLE
Admin Password

### ISSUE THREAD

**Issue by itsmylife44** [dvandal/cryptonote-nodejs-pool#99]
Hi , where i can set the password of the admin panel ? 

thanks

**Comment by avense** [comment]
config.json.....

 "api": {
        "enabled": true,
        "hashrateWindow": 600,
        "updateInterval": 5,
        "bindIp": "0.0.0.0",
        "port": 8117,
        "blocks": 30,
        "payments": 30,
        `"password": "your_password",`
        "ssl": false,
        "sslPort": 8119,
        "sslCert": "./cert.pem",
        "sslKey": "./privkey.pem",
        "sslCA": "./chain.pem",
        "trustProxyIP": true
